// Code generated by ent, DO NOT EDIT.

package governanceevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldID, id))
}

// OperationID applies equality check predicate on the "operation_id" field. It's identical to OperationIDEQ.
func OperationID(v uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldOperationID, v))
}

// EventSequence applies equality check predicate on the "event_sequence" field. It's identical to EventSequenceEQ.
func EventSequence(v int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldEventSequence, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldActorUserID, v))
}

// DeploymentOperatorID applies equality check predicate on the "deployment_operator_id" field. It's identical to DeploymentOperatorIDEQ.
func DeploymentOperatorID(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldDeploymentOperatorID, v))
}

// TargetKind applies equality check predicate on the "target_kind" field. It's identical to TargetKindEQ.
func TargetKind(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldTargetKind, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldTargetID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldAction, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldReason, v))
}

// RecoveryNonceFingerprint applies equality check predicate on the "recovery_nonce_fingerprint" field. It's identical to RecoveryNonceFingerprintEQ.
func RecoveryNonceFingerprint(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldRecoveryNonceFingerprint, v))
}

// GatewayRequestID applies equality check predicate on the "gateway_request_id" field. It's identical to GatewayRequestIDEQ.
func GatewayRequestID(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldGatewayRequestID, v))
}

// SafeErrorSummary applies equality check predicate on the "safe_error_summary" field. It's identical to SafeErrorSummaryEQ.
func SafeErrorSummary(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldSafeErrorSummary, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// OperationIDEQ applies the EQ predicate on the "operation_id" field.
func OperationIDEQ(v uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldOperationID, v))
}

// OperationIDNEQ applies the NEQ predicate on the "operation_id" field.
func OperationIDNEQ(v uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldOperationID, v))
}

// OperationIDIn applies the In predicate on the "operation_id" field.
func OperationIDIn(vs ...uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldOperationID, vs...))
}

// OperationIDNotIn applies the NotIn predicate on the "operation_id" field.
func OperationIDNotIn(vs ...uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldOperationID, vs...))
}

// OperationIDGT applies the GT predicate on the "operation_id" field.
func OperationIDGT(v uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldOperationID, v))
}

// OperationIDGTE applies the GTE predicate on the "operation_id" field.
func OperationIDGTE(v uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldOperationID, v))
}

// OperationIDLT applies the LT predicate on the "operation_id" field.
func OperationIDLT(v uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldOperationID, v))
}

// OperationIDLTE applies the LTE predicate on the "operation_id" field.
func OperationIDLTE(v uuid.UUID) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldOperationID, v))
}

// EventSequenceEQ applies the EQ predicate on the "event_sequence" field.
func EventSequenceEQ(v int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldEventSequence, v))
}

// EventSequenceNEQ applies the NEQ predicate on the "event_sequence" field.
func EventSequenceNEQ(v int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldEventSequence, v))
}

// EventSequenceIn applies the In predicate on the "event_sequence" field.
func EventSequenceIn(vs ...int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldEventSequence, vs...))
}

// EventSequenceNotIn applies the NotIn predicate on the "event_sequence" field.
func EventSequenceNotIn(vs ...int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldEventSequence, vs...))
}

// EventSequenceGT applies the GT predicate on the "event_sequence" field.
func EventSequenceGT(v int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldEventSequence, v))
}

// EventSequenceGTE applies the GTE predicate on the "event_sequence" field.
func EventSequenceGTE(v int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldEventSequence, v))
}

// EventSequenceLT applies the LT predicate on the "event_sequence" field.
func EventSequenceLT(v int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldEventSequence, v))
}

// EventSequenceLTE applies the LTE predicate on the "event_sequence" field.
func EventSequenceLTE(v int) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldEventSequence, v))
}

// ActorKindEQ applies the EQ predicate on the "actor_kind" field.
func ActorKindEQ(v ActorKind) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldActorKind, v))
}

// ActorKindNEQ applies the NEQ predicate on the "actor_kind" field.
func ActorKindNEQ(v ActorKind) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldActorKind, v))
}

// ActorKindIn applies the In predicate on the "actor_kind" field.
func ActorKindIn(vs ...ActorKind) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldActorKind, vs...))
}

// ActorKindNotIn applies the NotIn predicate on the "actor_kind" field.
func ActorKindNotIn(vs ...ActorKind) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldActorKind, vs...))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotNull(FieldActorUserID))
}

// DeploymentOperatorIDEQ applies the EQ predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDNEQ applies the NEQ predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDNEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDIn applies the In predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldDeploymentOperatorID, vs...))
}

// DeploymentOperatorIDNotIn applies the NotIn predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDNotIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldDeploymentOperatorID, vs...))
}

// DeploymentOperatorIDGT applies the GT predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDGT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDGTE applies the GTE predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDGTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDLT applies the LT predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDLT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDLTE applies the LTE predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDLTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDContains applies the Contains predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDContains(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContains(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDHasPrefix applies the HasPrefix predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDHasPrefix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasPrefix(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDHasSuffix applies the HasSuffix predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDHasSuffix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasSuffix(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDIsNil applies the IsNil predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDIsNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIsNull(FieldDeploymentOperatorID))
}

// DeploymentOperatorIDNotNil applies the NotNil predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDNotNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotNull(FieldDeploymentOperatorID))
}

// DeploymentOperatorIDEqualFold applies the EqualFold predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDEqualFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEqualFold(FieldDeploymentOperatorID, v))
}

// DeploymentOperatorIDContainsFold applies the ContainsFold predicate on the "deployment_operator_id" field.
func DeploymentOperatorIDContainsFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContainsFold(FieldDeploymentOperatorID, v))
}

// TargetKindEQ applies the EQ predicate on the "target_kind" field.
func TargetKindEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldTargetKind, v))
}

// TargetKindNEQ applies the NEQ predicate on the "target_kind" field.
func TargetKindNEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldTargetKind, v))
}

// TargetKindIn applies the In predicate on the "target_kind" field.
func TargetKindIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldTargetKind, vs...))
}

// TargetKindNotIn applies the NotIn predicate on the "target_kind" field.
func TargetKindNotIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldTargetKind, vs...))
}

// TargetKindGT applies the GT predicate on the "target_kind" field.
func TargetKindGT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldTargetKind, v))
}

// TargetKindGTE applies the GTE predicate on the "target_kind" field.
func TargetKindGTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldTargetKind, v))
}

// TargetKindLT applies the LT predicate on the "target_kind" field.
func TargetKindLT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldTargetKind, v))
}

// TargetKindLTE applies the LTE predicate on the "target_kind" field.
func TargetKindLTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldTargetKind, v))
}

// TargetKindContains applies the Contains predicate on the "target_kind" field.
func TargetKindContains(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContains(FieldTargetKind, v))
}

// TargetKindHasPrefix applies the HasPrefix predicate on the "target_kind" field.
func TargetKindHasPrefix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasPrefix(FieldTargetKind, v))
}

// TargetKindHasSuffix applies the HasSuffix predicate on the "target_kind" field.
func TargetKindHasSuffix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasSuffix(FieldTargetKind, v))
}

// TargetKindEqualFold applies the EqualFold predicate on the "target_kind" field.
func TargetKindEqualFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEqualFold(FieldTargetKind, v))
}

// TargetKindContainsFold applies the ContainsFold predicate on the "target_kind" field.
func TargetKindContainsFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContainsFold(FieldTargetKind, v))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldTargetID, vs...))
}

// TargetIDGT applies the GT predicate on the "target_id" field.
func TargetIDGT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldTargetID, v))
}

// TargetIDGTE applies the GTE predicate on the "target_id" field.
func TargetIDGTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldTargetID, v))
}

// TargetIDLT applies the LT predicate on the "target_id" field.
func TargetIDLT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldTargetID, v))
}

// TargetIDLTE applies the LTE predicate on the "target_id" field.
func TargetIDLTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldTargetID, v))
}

// TargetIDContains applies the Contains predicate on the "target_id" field.
func TargetIDContains(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContains(FieldTargetID, v))
}

// TargetIDHasPrefix applies the HasPrefix predicate on the "target_id" field.
func TargetIDHasPrefix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasPrefix(FieldTargetID, v))
}

// TargetIDHasSuffix applies the HasSuffix predicate on the "target_id" field.
func TargetIDHasSuffix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasSuffix(FieldTargetID, v))
}

// TargetIDEqualFold applies the EqualFold predicate on the "target_id" field.
func TargetIDEqualFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEqualFold(FieldTargetID, v))
}

// TargetIDContainsFold applies the ContainsFold predicate on the "target_id" field.
func TargetIDContainsFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContainsFold(FieldTargetID, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContainsFold(FieldAction, v))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v Result) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v Result) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...Result) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...Result) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldResult, vs...))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContainsFold(FieldReason, v))
}

// BeforeSummaryIsNil applies the IsNil predicate on the "before_summary" field.
func BeforeSummaryIsNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIsNull(FieldBeforeSummary))
}

// BeforeSummaryNotNil applies the NotNil predicate on the "before_summary" field.
func BeforeSummaryNotNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotNull(FieldBeforeSummary))
}

// AfterSummaryIsNil applies the IsNil predicate on the "after_summary" field.
func AfterSummaryIsNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIsNull(FieldAfterSummary))
}

// AfterSummaryNotNil applies the NotNil predicate on the "after_summary" field.
func AfterSummaryNotNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotNull(FieldAfterSummary))
}

// RecoveryNonceFingerprintEQ applies the EQ predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintNEQ applies the NEQ predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintNEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintIn applies the In predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldRecoveryNonceFingerprint, vs...))
}

// RecoveryNonceFingerprintNotIn applies the NotIn predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintNotIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldRecoveryNonceFingerprint, vs...))
}

// RecoveryNonceFingerprintGT applies the GT predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintGT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintGTE applies the GTE predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintGTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintLT applies the LT predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintLT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintLTE applies the LTE predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintLTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintContains applies the Contains predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintContains(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContains(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintHasPrefix applies the HasPrefix predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintHasPrefix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasPrefix(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintHasSuffix applies the HasSuffix predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintHasSuffix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasSuffix(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintIsNil applies the IsNil predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintIsNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIsNull(FieldRecoveryNonceFingerprint))
}

// RecoveryNonceFingerprintNotNil applies the NotNil predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintNotNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotNull(FieldRecoveryNonceFingerprint))
}

// RecoveryNonceFingerprintEqualFold applies the EqualFold predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintEqualFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEqualFold(FieldRecoveryNonceFingerprint, v))
}

// RecoveryNonceFingerprintContainsFold applies the ContainsFold predicate on the "recovery_nonce_fingerprint" field.
func RecoveryNonceFingerprintContainsFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContainsFold(FieldRecoveryNonceFingerprint, v))
}

// GatewayRequestIDEQ applies the EQ predicate on the "gateway_request_id" field.
func GatewayRequestIDEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldGatewayRequestID, v))
}

// GatewayRequestIDNEQ applies the NEQ predicate on the "gateway_request_id" field.
func GatewayRequestIDNEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldGatewayRequestID, v))
}

// GatewayRequestIDIn applies the In predicate on the "gateway_request_id" field.
func GatewayRequestIDIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldGatewayRequestID, vs...))
}

// GatewayRequestIDNotIn applies the NotIn predicate on the "gateway_request_id" field.
func GatewayRequestIDNotIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldGatewayRequestID, vs...))
}

// GatewayRequestIDGT applies the GT predicate on the "gateway_request_id" field.
func GatewayRequestIDGT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldGatewayRequestID, v))
}

// GatewayRequestIDGTE applies the GTE predicate on the "gateway_request_id" field.
func GatewayRequestIDGTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldGatewayRequestID, v))
}

// GatewayRequestIDLT applies the LT predicate on the "gateway_request_id" field.
func GatewayRequestIDLT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldGatewayRequestID, v))
}

// GatewayRequestIDLTE applies the LTE predicate on the "gateway_request_id" field.
func GatewayRequestIDLTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldGatewayRequestID, v))
}

// GatewayRequestIDContains applies the Contains predicate on the "gateway_request_id" field.
func GatewayRequestIDContains(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContains(FieldGatewayRequestID, v))
}

// GatewayRequestIDHasPrefix applies the HasPrefix predicate on the "gateway_request_id" field.
func GatewayRequestIDHasPrefix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasPrefix(FieldGatewayRequestID, v))
}

// GatewayRequestIDHasSuffix applies the HasSuffix predicate on the "gateway_request_id" field.
func GatewayRequestIDHasSuffix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasSuffix(FieldGatewayRequestID, v))
}

// GatewayRequestIDIsNil applies the IsNil predicate on the "gateway_request_id" field.
func GatewayRequestIDIsNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIsNull(FieldGatewayRequestID))
}

// GatewayRequestIDNotNil applies the NotNil predicate on the "gateway_request_id" field.
func GatewayRequestIDNotNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotNull(FieldGatewayRequestID))
}

// GatewayRequestIDEqualFold applies the EqualFold predicate on the "gateway_request_id" field.
func GatewayRequestIDEqualFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEqualFold(FieldGatewayRequestID, v))
}

// GatewayRequestIDContainsFold applies the ContainsFold predicate on the "gateway_request_id" field.
func GatewayRequestIDContainsFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContainsFold(FieldGatewayRequestID, v))
}

// SafeErrorSummaryEQ applies the EQ predicate on the "safe_error_summary" field.
func SafeErrorSummaryEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryNEQ applies the NEQ predicate on the "safe_error_summary" field.
func SafeErrorSummaryNEQ(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryIn applies the In predicate on the "safe_error_summary" field.
func SafeErrorSummaryIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldSafeErrorSummary, vs...))
}

// SafeErrorSummaryNotIn applies the NotIn predicate on the "safe_error_summary" field.
func SafeErrorSummaryNotIn(vs ...string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldSafeErrorSummary, vs...))
}

// SafeErrorSummaryGT applies the GT predicate on the "safe_error_summary" field.
func SafeErrorSummaryGT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryGTE applies the GTE predicate on the "safe_error_summary" field.
func SafeErrorSummaryGTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryLT applies the LT predicate on the "safe_error_summary" field.
func SafeErrorSummaryLT(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryLTE applies the LTE predicate on the "safe_error_summary" field.
func SafeErrorSummaryLTE(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryContains applies the Contains predicate on the "safe_error_summary" field.
func SafeErrorSummaryContains(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContains(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryHasPrefix applies the HasPrefix predicate on the "safe_error_summary" field.
func SafeErrorSummaryHasPrefix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasPrefix(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryHasSuffix applies the HasSuffix predicate on the "safe_error_summary" field.
func SafeErrorSummaryHasSuffix(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldHasSuffix(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryIsNil applies the IsNil predicate on the "safe_error_summary" field.
func SafeErrorSummaryIsNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIsNull(FieldSafeErrorSummary))
}

// SafeErrorSummaryNotNil applies the NotNil predicate on the "safe_error_summary" field.
func SafeErrorSummaryNotNil() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotNull(FieldSafeErrorSummary))
}

// SafeErrorSummaryEqualFold applies the EqualFold predicate on the "safe_error_summary" field.
func SafeErrorSummaryEqualFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEqualFold(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryContainsFold applies the ContainsFold predicate on the "safe_error_summary" field.
func SafeErrorSummaryContainsFold(v string) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldContainsFold(FieldSafeErrorSummary, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.FieldLTE(FieldOccurredAt, v))
}

// HasActor applies the HasEdge predicate on the "actor" edge.
func HasActor() predicate.GovernanceEvent {
	return predicate.GovernanceEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActorTable, ActorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActorWith applies the HasEdge predicate on the "actor" edge with a given conditions (other predicates).
func HasActorWith(preds ...predicate.User) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(func(s *sql.Selector) {
		step := newActorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GovernanceEvent) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GovernanceEvent) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GovernanceEvent) predicate.GovernanceEvent {
	return predicate.GovernanceEvent(sql.NotPredicates(p))
}
