// Code generated by ent, DO NOT EDIT.

package auditinteraction

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the auditinteraction type in the database.
	Label = "audit_interaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGatewayRequestID holds the string denoting the gateway_request_id field in the database.
	FieldGatewayRequestID = "gateway_request_id"
	// FieldWorkSessionID holds the string denoting the work_session_id field in the database.
	FieldWorkSessionID = "work_session_id"
	// FieldSubjectUserID holds the string denoting the subject_user_id field in the database.
	FieldSubjectUserID = "subject_user_id"
	// FieldSubjectEmailSnapshot holds the string denoting the subject_email_snapshot field in the database.
	FieldSubjectEmailSnapshot = "subject_email_snapshot"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAPIKeyFingerprint holds the string denoting the api_key_fingerprint field in the database.
	FieldAPIKeyFingerprint = "api_key_fingerprint"
	// FieldProfileVersion holds the string denoting the profile_version field in the database.
	FieldProfileVersion = "profile_version"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldTransport holds the string denoting the transport field in the database.
	FieldTransport = "transport"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldResolvedModel holds the string denoting the resolved_model field in the database.
	FieldResolvedModel = "resolved_model"
	// FieldRequestOutcome holds the string denoting the request_outcome field in the database.
	FieldRequestOutcome = "request_outcome"
	// FieldRequestOutcomeVersion holds the string denoting the request_outcome_version field in the database.
	FieldRequestOutcomeVersion = "request_outcome_version"
	// FieldContentState holds the string denoting the content_state field in the database.
	FieldContentState = "content_state"
	// FieldContentStateVersion holds the string denoting the content_state_version field in the database.
	FieldContentStateVersion = "content_state_version"
	// FieldDownstreamStatus holds the string denoting the downstream_status field in the database.
	FieldDownstreamStatus = "downstream_status"
	// FieldDownstreamWriteResult holds the string denoting the downstream_write_result field in the database.
	FieldDownstreamWriteResult = "downstream_write_result"
	// FieldAdmittedAt holds the string denoting the admitted_at field in the database.
	FieldAdmittedAt = "admitted_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldLastActivityAt holds the string denoting the last_activity_at field in the database.
	FieldLastActivityAt = "last_activity_at"
	// FieldRequestSha256 holds the string denoting the request_sha256 field in the database.
	FieldRequestSha256 = "request_sha256"
	// FieldResponseSha256 holds the string denoting the response_sha256 field in the database.
	FieldResponseSha256 = "response_sha256"
	// FieldRequestPartCount holds the string denoting the request_part_count field in the database.
	FieldRequestPartCount = "request_part_count"
	// FieldResponsePartCount holds the string denoting the response_part_count field in the database.
	FieldResponsePartCount = "response_part_count"
	// FieldSafeErrorSummary holds the string denoting the safe_error_summary field in the database.
	FieldSafeErrorSummary = "safe_error_summary"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeContentParts holds the string denoting the content_parts edge name in mutations.
	EdgeContentParts = "content_parts"
	// Table holds the table name of the auditinteraction in the database.
	Table = "audit_interactions"
	// ContentPartsTable is the table that holds the content_parts relation/edge.
	ContentPartsTable = "audit_content_parts"
	// ContentPartsInverseTable is the table name for the AuditContentPart entity.
	// It exists in this package in order to avoid circular dependency with the "auditcontentpart" package.
	ContentPartsInverseTable = "audit_content_parts"
	// ContentPartsColumn is the table column denoting the content_parts relation/edge.
	ContentPartsColumn = "interaction_id"
)

// Columns holds all SQL columns for auditinteraction fields.
var Columns = []string{
	FieldID,
	FieldGatewayRequestID,
	FieldWorkSessionID,
	FieldSubjectUserID,
	FieldSubjectEmailSnapshot,
	FieldAPIKeyID,
	FieldAPIKeyFingerprint,
	FieldProfileVersion,
	FieldProtocol,
	FieldEndpoint,
	FieldMethod,
	FieldTransport,
	FieldRequestedModel,
	FieldResolvedModel,
	FieldRequestOutcome,
	FieldRequestOutcomeVersion,
	FieldContentState,
	FieldContentStateVersion,
	FieldDownstreamStatus,
	FieldDownstreamWriteResult,
	FieldAdmittedAt,
	FieldCompletedAt,
	FieldExpiresAt,
	FieldLastActivityAt,
	FieldRequestSha256,
	FieldResponseSha256,
	FieldRequestPartCount,
	FieldResponsePartCount,
	FieldSafeErrorSummary,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SubjectEmailSnapshotValidator is a validator for the "subject_email_snapshot" field. It is called by the builders before save.
	SubjectEmailSnapshotValidator func(string) error
	// APIKeyFingerprintValidator is a validator for the "api_key_fingerprint" field. It is called by the builders before save.
	APIKeyFingerprintValidator func(string) error
	// ProfileVersionValidator is a validator for the "profile_version" field. It is called by the builders before save.
	ProfileVersionValidator func(string) error
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// ResolvedModelValidator is a validator for the "resolved_model" field. It is called by the builders before save.
	ResolvedModelValidator func(string) error
	// DefaultRequestOutcomeVersion holds the default value on creation for the "request_outcome_version" field.
	DefaultRequestOutcomeVersion int64
	// DefaultContentStateVersion holds the default value on creation for the "content_state_version" field.
	DefaultContentStateVersion int64
	// DefaultRequestPartCount holds the default value on creation for the "request_part_count" field.
	DefaultRequestPartCount int
	// DefaultResponsePartCount holds the default value on creation for the "response_part_count" field.
	DefaultResponsePartCount int
	// SafeErrorSummaryValidator is a validator for the "safe_error_summary" field. It is called by the builders before save.
	SafeErrorSummaryValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Protocol defines the type for the "protocol" enum field.
type Protocol string

// Protocol values.
const (
	ProtocolAnthropic Protocol = "anthropic"
	ProtocolOpenai    Protocol = "openai"
)

func (pr Protocol) String() string {
	return string(pr)
}

// ProtocolValidator is a validator for the "protocol" field enum values. It is called by the builders before save.
func ProtocolValidator(pr Protocol) error {
	switch pr {
	case ProtocolAnthropic, ProtocolOpenai:
		return nil
	default:
		return fmt.Errorf("auditinteraction: invalid enum value for protocol field: %q", pr)
	}
}

// Transport defines the type for the "transport" enum field.
type Transport string

// Transport values.
const (
	TransportHTTP Transport = "http"
	TransportSse  Transport = "sse"
)

func (t Transport) String() string {
	return string(t)
}

// TransportValidator is a validator for the "transport" field enum values. It is called by the builders before save.
func TransportValidator(t Transport) error {
	switch t {
	case TransportHTTP, TransportSse:
		return nil
	default:
		return fmt.Errorf("auditinteraction: invalid enum value for transport field: %q", t)
	}
}

// RequestOutcome defines the type for the "request_outcome" enum field.
type RequestOutcome string

// RequestOutcomeProcessing is the default value of the RequestOutcome enum.
const DefaultRequestOutcome = RequestOutcomeProcessing

// RequestOutcome values.
const (
	RequestOutcomeProcessing          RequestOutcome = "processing"
	RequestOutcomeRejectedPreUpstream RequestOutcome = "rejected_pre_upstream"
	RequestOutcomeCompleted           RequestOutcome = "completed"
	RequestOutcomeUpstreamFailed      RequestOutcome = "upstream_failed"
	RequestOutcomeInterrupted         RequestOutcome = "interrupted"
)

func (ro RequestOutcome) String() string {
	return string(ro)
}

// RequestOutcomeValidator is a validator for the "request_outcome" field enum values. It is called by the builders before save.
func RequestOutcomeValidator(ro RequestOutcome) error {
	switch ro {
	case RequestOutcomeProcessing, RequestOutcomeRejectedPreUpstream, RequestOutcomeCompleted, RequestOutcomeUpstreamFailed, RequestOutcomeInterrupted:
		return nil
	default:
		return fmt.Errorf("auditinteraction: invalid enum value for request_outcome field: %q", ro)
	}
}

// ContentState defines the type for the "content_state" enum field.
type ContentState string

// ContentStateRecording is the default value of the ContentState enum.
const DefaultContentState = ContentStateRecording

// ContentState values.
const (
	ContentStateRecording  ContentState = "recording"
	ContentStateComplete   ContentState = "complete"
	ContentStateIncomplete ContentState = "incomplete"
	ContentStateExpired    ContentState = "expired"
)

func (cs ContentState) String() string {
	return string(cs)
}

// ContentStateValidator is a validator for the "content_state" field enum values. It is called by the builders before save.
func ContentStateValidator(cs ContentState) error {
	switch cs {
	case ContentStateRecording, ContentStateComplete, ContentStateIncomplete, ContentStateExpired:
		return nil
	default:
		return fmt.Errorf("auditinteraction: invalid enum value for content_state field: %q", cs)
	}
}

// DownstreamWriteResult defines the type for the "downstream_write_result" enum field.
type DownstreamWriteResult string

// DownstreamWriteResultNotApplicable is the default value of the DownstreamWriteResult enum.
const DefaultDownstreamWriteResult = DownstreamWriteResultNotApplicable

// DownstreamWriteResult values.
const (
	DownstreamWriteResultNotApplicable DownstreamWriteResult = "not_applicable"
	DownstreamWriteResultPending       DownstreamWriteResult = "pending"
	DownstreamWriteResultSucceeded     DownstreamWriteResult = "succeeded"
	DownstreamWriteResultFailed        DownstreamWriteResult = "failed"
	DownstreamWriteResultUnknown       DownstreamWriteResult = "unknown"
)

func (dwr DownstreamWriteResult) String() string {
	return string(dwr)
}

// DownstreamWriteResultValidator is a validator for the "downstream_write_result" field enum values. It is called by the builders before save.
func DownstreamWriteResultValidator(dwr DownstreamWriteResult) error {
	switch dwr {
	case DownstreamWriteResultNotApplicable, DownstreamWriteResultPending, DownstreamWriteResultSucceeded, DownstreamWriteResultFailed, DownstreamWriteResultUnknown:
		return nil
	default:
		return fmt.Errorf("auditinteraction: invalid enum value for downstream_write_result field: %q", dwr)
	}
}

// OrderOption defines the ordering options for the AuditInteraction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGatewayRequestID orders the results by the gateway_request_id field.
func ByGatewayRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayRequestID, opts...).ToFunc()
}

// ByWorkSessionID orders the results by the work_session_id field.
func ByWorkSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkSessionID, opts...).ToFunc()
}

// BySubjectUserID orders the results by the subject_user_id field.
func BySubjectUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectUserID, opts...).ToFunc()
}

// BySubjectEmailSnapshot orders the results by the subject_email_snapshot field.
func BySubjectEmailSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectEmailSnapshot, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAPIKeyFingerprint orders the results by the api_key_fingerprint field.
func ByAPIKeyFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyFingerprint, opts...).ToFunc()
}

// ByProfileVersion orders the results by the profile_version field.
func ByProfileVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileVersion, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByTransport orders the results by the transport field.
func ByTransport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransport, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByResolvedModel orders the results by the resolved_model field.
func ByResolvedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedModel, opts...).ToFunc()
}

// ByRequestOutcome orders the results by the request_outcome field.
func ByRequestOutcome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestOutcome, opts...).ToFunc()
}

// ByRequestOutcomeVersion orders the results by the request_outcome_version field.
func ByRequestOutcomeVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestOutcomeVersion, opts...).ToFunc()
}

// ByContentState orders the results by the content_state field.
func ByContentState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentState, opts...).ToFunc()
}

// ByContentStateVersion orders the results by the content_state_version field.
func ByContentStateVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentStateVersion, opts...).ToFunc()
}

// ByDownstreamStatus orders the results by the downstream_status field.
func ByDownstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownstreamStatus, opts...).ToFunc()
}

// ByDownstreamWriteResult orders the results by the downstream_write_result field.
func ByDownstreamWriteResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownstreamWriteResult, opts...).ToFunc()
}

// ByAdmittedAt orders the results by the admitted_at field.
func ByAdmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdmittedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByLastActivityAt orders the results by the last_activity_at field.
func ByLastActivityAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActivityAt, opts...).ToFunc()
}

// ByRequestPartCount orders the results by the request_part_count field.
func ByRequestPartCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestPartCount, opts...).ToFunc()
}

// ByResponsePartCount orders the results by the response_part_count field.
func ByResponsePartCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponsePartCount, opts...).ToFunc()
}

// BySafeErrorSummary orders the results by the safe_error_summary field.
func BySafeErrorSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSafeErrorSummary, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByContentPartsCount orders the results by content_parts count.
func ByContentPartsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newContentPartsStep(), opts...)
	}
}

// ByContentParts orders the results by content_parts terms.
func ByContentParts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContentPartsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newContentPartsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContentPartsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ContentPartsTable, ContentPartsColumn),
	)
}
