// Code generated by ent, DO NOT EDIT.

package auditinteraction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldID, id))
}

// GatewayRequestID applies equality check predicate on the "gateway_request_id" field. It's identical to GatewayRequestIDEQ.
func GatewayRequestID(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldGatewayRequestID, v))
}

// WorkSessionID applies equality check predicate on the "work_session_id" field. It's identical to WorkSessionIDEQ.
func WorkSessionID(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldWorkSessionID, v))
}

// SubjectUserID applies equality check predicate on the "subject_user_id" field. It's identical to SubjectUserIDEQ.
func SubjectUserID(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldSubjectUserID, v))
}

// SubjectEmailSnapshot applies equality check predicate on the "subject_email_snapshot" field. It's identical to SubjectEmailSnapshotEQ.
func SubjectEmailSnapshot(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldSubjectEmailSnapshot, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyFingerprint applies equality check predicate on the "api_key_fingerprint" field. It's identical to APIKeyFingerprintEQ.
func APIKeyFingerprint(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldAPIKeyFingerprint, v))
}

// ProfileVersion applies equality check predicate on the "profile_version" field. It's identical to ProfileVersionEQ.
func ProfileVersion(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldProfileVersion, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldEndpoint, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldMethod, v))
}

// RequestedModel applies equality check predicate on the "requested_model" field. It's identical to RequestedModelEQ.
func RequestedModel(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestedModel, v))
}

// ResolvedModel applies equality check predicate on the "resolved_model" field. It's identical to ResolvedModelEQ.
func ResolvedModel(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldResolvedModel, v))
}

// RequestOutcomeVersion applies equality check predicate on the "request_outcome_version" field. It's identical to RequestOutcomeVersionEQ.
func RequestOutcomeVersion(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestOutcomeVersion, v))
}

// ContentStateVersion applies equality check predicate on the "content_state_version" field. It's identical to ContentStateVersionEQ.
func ContentStateVersion(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldContentStateVersion, v))
}

// DownstreamStatus applies equality check predicate on the "downstream_status" field. It's identical to DownstreamStatusEQ.
func DownstreamStatus(v int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldDownstreamStatus, v))
}

// AdmittedAt applies equality check predicate on the "admitted_at" field. It's identical to AdmittedAtEQ.
func AdmittedAt(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldAdmittedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldCompletedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldExpiresAt, v))
}

// LastActivityAt applies equality check predicate on the "last_activity_at" field. It's identical to LastActivityAtEQ.
func LastActivityAt(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldLastActivityAt, v))
}

// RequestSha256 applies equality check predicate on the "request_sha256" field. It's identical to RequestSha256EQ.
func RequestSha256(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestSha256, v))
}

// ResponseSha256 applies equality check predicate on the "response_sha256" field. It's identical to ResponseSha256EQ.
func ResponseSha256(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldResponseSha256, v))
}

// RequestPartCount applies equality check predicate on the "request_part_count" field. It's identical to RequestPartCountEQ.
func RequestPartCount(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestPartCount, v))
}

// ResponsePartCount applies equality check predicate on the "response_part_count" field. It's identical to ResponsePartCountEQ.
func ResponsePartCount(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldResponsePartCount, v))
}

// SafeErrorSummary applies equality check predicate on the "safe_error_summary" field. It's identical to SafeErrorSummaryEQ.
func SafeErrorSummary(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldSafeErrorSummary, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldUpdatedAt, v))
}

// GatewayRequestIDEQ applies the EQ predicate on the "gateway_request_id" field.
func GatewayRequestIDEQ(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldGatewayRequestID, v))
}

// GatewayRequestIDNEQ applies the NEQ predicate on the "gateway_request_id" field.
func GatewayRequestIDNEQ(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldGatewayRequestID, v))
}

// GatewayRequestIDIn applies the In predicate on the "gateway_request_id" field.
func GatewayRequestIDIn(vs ...uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldGatewayRequestID, vs...))
}

// GatewayRequestIDNotIn applies the NotIn predicate on the "gateway_request_id" field.
func GatewayRequestIDNotIn(vs ...uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldGatewayRequestID, vs...))
}

// GatewayRequestIDGT applies the GT predicate on the "gateway_request_id" field.
func GatewayRequestIDGT(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldGatewayRequestID, v))
}

// GatewayRequestIDGTE applies the GTE predicate on the "gateway_request_id" field.
func GatewayRequestIDGTE(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldGatewayRequestID, v))
}

// GatewayRequestIDLT applies the LT predicate on the "gateway_request_id" field.
func GatewayRequestIDLT(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldGatewayRequestID, v))
}

// GatewayRequestIDLTE applies the LTE predicate on the "gateway_request_id" field.
func GatewayRequestIDLTE(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldGatewayRequestID, v))
}

// WorkSessionIDEQ applies the EQ predicate on the "work_session_id" field.
func WorkSessionIDEQ(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldWorkSessionID, v))
}

// WorkSessionIDNEQ applies the NEQ predicate on the "work_session_id" field.
func WorkSessionIDNEQ(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldWorkSessionID, v))
}

// WorkSessionIDIn applies the In predicate on the "work_session_id" field.
func WorkSessionIDIn(vs ...uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldWorkSessionID, vs...))
}

// WorkSessionIDNotIn applies the NotIn predicate on the "work_session_id" field.
func WorkSessionIDNotIn(vs ...uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldWorkSessionID, vs...))
}

// WorkSessionIDGT applies the GT predicate on the "work_session_id" field.
func WorkSessionIDGT(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldWorkSessionID, v))
}

// WorkSessionIDGTE applies the GTE predicate on the "work_session_id" field.
func WorkSessionIDGTE(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldWorkSessionID, v))
}

// WorkSessionIDLT applies the LT predicate on the "work_session_id" field.
func WorkSessionIDLT(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldWorkSessionID, v))
}

// WorkSessionIDLTE applies the LTE predicate on the "work_session_id" field.
func WorkSessionIDLTE(v uuid.UUID) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldWorkSessionID, v))
}

// WorkSessionIDIsNil applies the IsNil predicate on the "work_session_id" field.
func WorkSessionIDIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldWorkSessionID))
}

// WorkSessionIDNotNil applies the NotNil predicate on the "work_session_id" field.
func WorkSessionIDNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldWorkSessionID))
}

// SubjectUserIDEQ applies the EQ predicate on the "subject_user_id" field.
func SubjectUserIDEQ(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldSubjectUserID, v))
}

// SubjectUserIDNEQ applies the NEQ predicate on the "subject_user_id" field.
func SubjectUserIDNEQ(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldSubjectUserID, v))
}

// SubjectUserIDIn applies the In predicate on the "subject_user_id" field.
func SubjectUserIDIn(vs ...int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldSubjectUserID, vs...))
}

// SubjectUserIDNotIn applies the NotIn predicate on the "subject_user_id" field.
func SubjectUserIDNotIn(vs ...int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldSubjectUserID, vs...))
}

// SubjectUserIDGT applies the GT predicate on the "subject_user_id" field.
func SubjectUserIDGT(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldSubjectUserID, v))
}

// SubjectUserIDGTE applies the GTE predicate on the "subject_user_id" field.
func SubjectUserIDGTE(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldSubjectUserID, v))
}

// SubjectUserIDLT applies the LT predicate on the "subject_user_id" field.
func SubjectUserIDLT(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldSubjectUserID, v))
}

// SubjectUserIDLTE applies the LTE predicate on the "subject_user_id" field.
func SubjectUserIDLTE(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldSubjectUserID, v))
}

// SubjectUserIDIsNil applies the IsNil predicate on the "subject_user_id" field.
func SubjectUserIDIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldSubjectUserID))
}

// SubjectUserIDNotNil applies the NotNil predicate on the "subject_user_id" field.
func SubjectUserIDNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldSubjectUserID))
}

// SubjectEmailSnapshotEQ applies the EQ predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotNEQ applies the NEQ predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotNEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotIn applies the In predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldSubjectEmailSnapshot, vs...))
}

// SubjectEmailSnapshotNotIn applies the NotIn predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotNotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldSubjectEmailSnapshot, vs...))
}

// SubjectEmailSnapshotGT applies the GT predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotGT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotGTE applies the GTE predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotGTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotLT applies the LT predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotLT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotLTE applies the LTE predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotLTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotContains applies the Contains predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotContains(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContains(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotHasPrefix applies the HasPrefix predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotHasPrefix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasPrefix(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotHasSuffix applies the HasSuffix predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotHasSuffix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasSuffix(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotIsNil applies the IsNil predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldSubjectEmailSnapshot))
}

// SubjectEmailSnapshotNotNil applies the NotNil predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldSubjectEmailSnapshot))
}

// SubjectEmailSnapshotEqualFold applies the EqualFold predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotEqualFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEqualFold(FieldSubjectEmailSnapshot, v))
}

// SubjectEmailSnapshotContainsFold applies the ContainsFold predicate on the "subject_email_snapshot" field.
func SubjectEmailSnapshotContainsFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContainsFold(FieldSubjectEmailSnapshot, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldAPIKeyID))
}

// APIKeyFingerprintEQ applies the EQ predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintNEQ applies the NEQ predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintNEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintIn applies the In predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldAPIKeyFingerprint, vs...))
}

// APIKeyFingerprintNotIn applies the NotIn predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintNotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldAPIKeyFingerprint, vs...))
}

// APIKeyFingerprintGT applies the GT predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintGT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintGTE applies the GTE predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintGTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintLT applies the LT predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintLT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintLTE applies the LTE predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintLTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintContains applies the Contains predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintContains(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContains(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintHasPrefix applies the HasPrefix predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintHasPrefix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasPrefix(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintHasSuffix applies the HasSuffix predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintHasSuffix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasSuffix(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintIsNil applies the IsNil predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldAPIKeyFingerprint))
}

// APIKeyFingerprintNotNil applies the NotNil predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldAPIKeyFingerprint))
}

// APIKeyFingerprintEqualFold applies the EqualFold predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintEqualFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEqualFold(FieldAPIKeyFingerprint, v))
}

// APIKeyFingerprintContainsFold applies the ContainsFold predicate on the "api_key_fingerprint" field.
func APIKeyFingerprintContainsFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContainsFold(FieldAPIKeyFingerprint, v))
}

// ProfileVersionEQ applies the EQ predicate on the "profile_version" field.
func ProfileVersionEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldProfileVersion, v))
}

// ProfileVersionNEQ applies the NEQ predicate on the "profile_version" field.
func ProfileVersionNEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldProfileVersion, v))
}

// ProfileVersionIn applies the In predicate on the "profile_version" field.
func ProfileVersionIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldProfileVersion, vs...))
}

// ProfileVersionNotIn applies the NotIn predicate on the "profile_version" field.
func ProfileVersionNotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldProfileVersion, vs...))
}

// ProfileVersionGT applies the GT predicate on the "profile_version" field.
func ProfileVersionGT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldProfileVersion, v))
}

// ProfileVersionGTE applies the GTE predicate on the "profile_version" field.
func ProfileVersionGTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldProfileVersion, v))
}

// ProfileVersionLT applies the LT predicate on the "profile_version" field.
func ProfileVersionLT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldProfileVersion, v))
}

// ProfileVersionLTE applies the LTE predicate on the "profile_version" field.
func ProfileVersionLTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldProfileVersion, v))
}

// ProfileVersionContains applies the Contains predicate on the "profile_version" field.
func ProfileVersionContains(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContains(FieldProfileVersion, v))
}

// ProfileVersionHasPrefix applies the HasPrefix predicate on the "profile_version" field.
func ProfileVersionHasPrefix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasPrefix(FieldProfileVersion, v))
}

// ProfileVersionHasSuffix applies the HasSuffix predicate on the "profile_version" field.
func ProfileVersionHasSuffix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasSuffix(FieldProfileVersion, v))
}

// ProfileVersionEqualFold applies the EqualFold predicate on the "profile_version" field.
func ProfileVersionEqualFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEqualFold(FieldProfileVersion, v))
}

// ProfileVersionContainsFold applies the ContainsFold predicate on the "profile_version" field.
func ProfileVersionContainsFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContainsFold(FieldProfileVersion, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v Protocol) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v Protocol) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...Protocol) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...Protocol) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldProtocol, vs...))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContainsFold(FieldEndpoint, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContainsFold(FieldMethod, v))
}

// TransportEQ applies the EQ predicate on the "transport" field.
func TransportEQ(v Transport) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldTransport, v))
}

// TransportNEQ applies the NEQ predicate on the "transport" field.
func TransportNEQ(v Transport) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldTransport, v))
}

// TransportIn applies the In predicate on the "transport" field.
func TransportIn(vs ...Transport) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldTransport, vs...))
}

// TransportNotIn applies the NotIn predicate on the "transport" field.
func TransportNotIn(vs ...Transport) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldTransport, vs...))
}

// RequestedModelEQ applies the EQ predicate on the "requested_model" field.
func RequestedModelEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestedModel, v))
}

// RequestedModelNEQ applies the NEQ predicate on the "requested_model" field.
func RequestedModelNEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldRequestedModel, v))
}

// RequestedModelIn applies the In predicate on the "requested_model" field.
func RequestedModelIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldRequestedModel, vs...))
}

// RequestedModelNotIn applies the NotIn predicate on the "requested_model" field.
func RequestedModelNotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldRequestedModel, vs...))
}

// RequestedModelGT applies the GT predicate on the "requested_model" field.
func RequestedModelGT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldRequestedModel, v))
}

// RequestedModelGTE applies the GTE predicate on the "requested_model" field.
func RequestedModelGTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldRequestedModel, v))
}

// RequestedModelLT applies the LT predicate on the "requested_model" field.
func RequestedModelLT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldRequestedModel, v))
}

// RequestedModelLTE applies the LTE predicate on the "requested_model" field.
func RequestedModelLTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldRequestedModel, v))
}

// RequestedModelContains applies the Contains predicate on the "requested_model" field.
func RequestedModelContains(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContains(FieldRequestedModel, v))
}

// RequestedModelHasPrefix applies the HasPrefix predicate on the "requested_model" field.
func RequestedModelHasPrefix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasPrefix(FieldRequestedModel, v))
}

// RequestedModelHasSuffix applies the HasSuffix predicate on the "requested_model" field.
func RequestedModelHasSuffix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasSuffix(FieldRequestedModel, v))
}

// RequestedModelIsNil applies the IsNil predicate on the "requested_model" field.
func RequestedModelIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldRequestedModel))
}

// RequestedModelNotNil applies the NotNil predicate on the "requested_model" field.
func RequestedModelNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldRequestedModel))
}

// RequestedModelEqualFold applies the EqualFold predicate on the "requested_model" field.
func RequestedModelEqualFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEqualFold(FieldRequestedModel, v))
}

// RequestedModelContainsFold applies the ContainsFold predicate on the "requested_model" field.
func RequestedModelContainsFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContainsFold(FieldRequestedModel, v))
}

// ResolvedModelEQ applies the EQ predicate on the "resolved_model" field.
func ResolvedModelEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldResolvedModel, v))
}

// ResolvedModelNEQ applies the NEQ predicate on the "resolved_model" field.
func ResolvedModelNEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldResolvedModel, v))
}

// ResolvedModelIn applies the In predicate on the "resolved_model" field.
func ResolvedModelIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldResolvedModel, vs...))
}

// ResolvedModelNotIn applies the NotIn predicate on the "resolved_model" field.
func ResolvedModelNotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldResolvedModel, vs...))
}

// ResolvedModelGT applies the GT predicate on the "resolved_model" field.
func ResolvedModelGT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldResolvedModel, v))
}

// ResolvedModelGTE applies the GTE predicate on the "resolved_model" field.
func ResolvedModelGTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldResolvedModel, v))
}

// ResolvedModelLT applies the LT predicate on the "resolved_model" field.
func ResolvedModelLT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldResolvedModel, v))
}

// ResolvedModelLTE applies the LTE predicate on the "resolved_model" field.
func ResolvedModelLTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldResolvedModel, v))
}

// ResolvedModelContains applies the Contains predicate on the "resolved_model" field.
func ResolvedModelContains(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContains(FieldResolvedModel, v))
}

// ResolvedModelHasPrefix applies the HasPrefix predicate on the "resolved_model" field.
func ResolvedModelHasPrefix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasPrefix(FieldResolvedModel, v))
}

// ResolvedModelHasSuffix applies the HasSuffix predicate on the "resolved_model" field.
func ResolvedModelHasSuffix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasSuffix(FieldResolvedModel, v))
}

// ResolvedModelIsNil applies the IsNil predicate on the "resolved_model" field.
func ResolvedModelIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldResolvedModel))
}

// ResolvedModelNotNil applies the NotNil predicate on the "resolved_model" field.
func ResolvedModelNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldResolvedModel))
}

// ResolvedModelEqualFold applies the EqualFold predicate on the "resolved_model" field.
func ResolvedModelEqualFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEqualFold(FieldResolvedModel, v))
}

// ResolvedModelContainsFold applies the ContainsFold predicate on the "resolved_model" field.
func ResolvedModelContainsFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContainsFold(FieldResolvedModel, v))
}

// RequestOutcomeEQ applies the EQ predicate on the "request_outcome" field.
func RequestOutcomeEQ(v RequestOutcome) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestOutcome, v))
}

// RequestOutcomeNEQ applies the NEQ predicate on the "request_outcome" field.
func RequestOutcomeNEQ(v RequestOutcome) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldRequestOutcome, v))
}

// RequestOutcomeIn applies the In predicate on the "request_outcome" field.
func RequestOutcomeIn(vs ...RequestOutcome) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldRequestOutcome, vs...))
}

// RequestOutcomeNotIn applies the NotIn predicate on the "request_outcome" field.
func RequestOutcomeNotIn(vs ...RequestOutcome) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldRequestOutcome, vs...))
}

// RequestOutcomeVersionEQ applies the EQ predicate on the "request_outcome_version" field.
func RequestOutcomeVersionEQ(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestOutcomeVersion, v))
}

// RequestOutcomeVersionNEQ applies the NEQ predicate on the "request_outcome_version" field.
func RequestOutcomeVersionNEQ(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldRequestOutcomeVersion, v))
}

// RequestOutcomeVersionIn applies the In predicate on the "request_outcome_version" field.
func RequestOutcomeVersionIn(vs ...int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldRequestOutcomeVersion, vs...))
}

// RequestOutcomeVersionNotIn applies the NotIn predicate on the "request_outcome_version" field.
func RequestOutcomeVersionNotIn(vs ...int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldRequestOutcomeVersion, vs...))
}

// RequestOutcomeVersionGT applies the GT predicate on the "request_outcome_version" field.
func RequestOutcomeVersionGT(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldRequestOutcomeVersion, v))
}

// RequestOutcomeVersionGTE applies the GTE predicate on the "request_outcome_version" field.
func RequestOutcomeVersionGTE(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldRequestOutcomeVersion, v))
}

// RequestOutcomeVersionLT applies the LT predicate on the "request_outcome_version" field.
func RequestOutcomeVersionLT(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldRequestOutcomeVersion, v))
}

// RequestOutcomeVersionLTE applies the LTE predicate on the "request_outcome_version" field.
func RequestOutcomeVersionLTE(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldRequestOutcomeVersion, v))
}

// ContentStateEQ applies the EQ predicate on the "content_state" field.
func ContentStateEQ(v ContentState) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldContentState, v))
}

// ContentStateNEQ applies the NEQ predicate on the "content_state" field.
func ContentStateNEQ(v ContentState) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldContentState, v))
}

// ContentStateIn applies the In predicate on the "content_state" field.
func ContentStateIn(vs ...ContentState) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldContentState, vs...))
}

// ContentStateNotIn applies the NotIn predicate on the "content_state" field.
func ContentStateNotIn(vs ...ContentState) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldContentState, vs...))
}

// ContentStateVersionEQ applies the EQ predicate on the "content_state_version" field.
func ContentStateVersionEQ(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldContentStateVersion, v))
}

// ContentStateVersionNEQ applies the NEQ predicate on the "content_state_version" field.
func ContentStateVersionNEQ(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldContentStateVersion, v))
}

// ContentStateVersionIn applies the In predicate on the "content_state_version" field.
func ContentStateVersionIn(vs ...int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldContentStateVersion, vs...))
}

// ContentStateVersionNotIn applies the NotIn predicate on the "content_state_version" field.
func ContentStateVersionNotIn(vs ...int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldContentStateVersion, vs...))
}

// ContentStateVersionGT applies the GT predicate on the "content_state_version" field.
func ContentStateVersionGT(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldContentStateVersion, v))
}

// ContentStateVersionGTE applies the GTE predicate on the "content_state_version" field.
func ContentStateVersionGTE(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldContentStateVersion, v))
}

// ContentStateVersionLT applies the LT predicate on the "content_state_version" field.
func ContentStateVersionLT(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldContentStateVersion, v))
}

// ContentStateVersionLTE applies the LTE predicate on the "content_state_version" field.
func ContentStateVersionLTE(v int64) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldContentStateVersion, v))
}

// DownstreamStatusEQ applies the EQ predicate on the "downstream_status" field.
func DownstreamStatusEQ(v int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldDownstreamStatus, v))
}

// DownstreamStatusNEQ applies the NEQ predicate on the "downstream_status" field.
func DownstreamStatusNEQ(v int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldDownstreamStatus, v))
}

// DownstreamStatusIn applies the In predicate on the "downstream_status" field.
func DownstreamStatusIn(vs ...int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldDownstreamStatus, vs...))
}

// DownstreamStatusNotIn applies the NotIn predicate on the "downstream_status" field.
func DownstreamStatusNotIn(vs ...int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldDownstreamStatus, vs...))
}

// DownstreamStatusGT applies the GT predicate on the "downstream_status" field.
func DownstreamStatusGT(v int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldDownstreamStatus, v))
}

// DownstreamStatusGTE applies the GTE predicate on the "downstream_status" field.
func DownstreamStatusGTE(v int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldDownstreamStatus, v))
}

// DownstreamStatusLT applies the LT predicate on the "downstream_status" field.
func DownstreamStatusLT(v int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldDownstreamStatus, v))
}

// DownstreamStatusLTE applies the LTE predicate on the "downstream_status" field.
func DownstreamStatusLTE(v int16) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldDownstreamStatus, v))
}

// DownstreamStatusIsNil applies the IsNil predicate on the "downstream_status" field.
func DownstreamStatusIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldDownstreamStatus))
}

// DownstreamStatusNotNil applies the NotNil predicate on the "downstream_status" field.
func DownstreamStatusNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldDownstreamStatus))
}

// DownstreamWriteResultEQ applies the EQ predicate on the "downstream_write_result" field.
func DownstreamWriteResultEQ(v DownstreamWriteResult) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldDownstreamWriteResult, v))
}

// DownstreamWriteResultNEQ applies the NEQ predicate on the "downstream_write_result" field.
func DownstreamWriteResultNEQ(v DownstreamWriteResult) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldDownstreamWriteResult, v))
}

// DownstreamWriteResultIn applies the In predicate on the "downstream_write_result" field.
func DownstreamWriteResultIn(vs ...DownstreamWriteResult) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldDownstreamWriteResult, vs...))
}

// DownstreamWriteResultNotIn applies the NotIn predicate on the "downstream_write_result" field.
func DownstreamWriteResultNotIn(vs ...DownstreamWriteResult) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldDownstreamWriteResult, vs...))
}

// AdmittedAtEQ applies the EQ predicate on the "admitted_at" field.
func AdmittedAtEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldAdmittedAt, v))
}

// AdmittedAtNEQ applies the NEQ predicate on the "admitted_at" field.
func AdmittedAtNEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldAdmittedAt, v))
}

// AdmittedAtIn applies the In predicate on the "admitted_at" field.
func AdmittedAtIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldAdmittedAt, vs...))
}

// AdmittedAtNotIn applies the NotIn predicate on the "admitted_at" field.
func AdmittedAtNotIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldAdmittedAt, vs...))
}

// AdmittedAtGT applies the GT predicate on the "admitted_at" field.
func AdmittedAtGT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldAdmittedAt, v))
}

// AdmittedAtGTE applies the GTE predicate on the "admitted_at" field.
func AdmittedAtGTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldAdmittedAt, v))
}

// AdmittedAtLT applies the LT predicate on the "admitted_at" field.
func AdmittedAtLT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldAdmittedAt, v))
}

// AdmittedAtLTE applies the LTE predicate on the "admitted_at" field.
func AdmittedAtLTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldAdmittedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldCompletedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldExpiresAt, v))
}

// LastActivityAtEQ applies the EQ predicate on the "last_activity_at" field.
func LastActivityAtEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldLastActivityAt, v))
}

// LastActivityAtNEQ applies the NEQ predicate on the "last_activity_at" field.
func LastActivityAtNEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldLastActivityAt, v))
}

// LastActivityAtIn applies the In predicate on the "last_activity_at" field.
func LastActivityAtIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldLastActivityAt, vs...))
}

// LastActivityAtNotIn applies the NotIn predicate on the "last_activity_at" field.
func LastActivityAtNotIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldLastActivityAt, vs...))
}

// LastActivityAtGT applies the GT predicate on the "last_activity_at" field.
func LastActivityAtGT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldLastActivityAt, v))
}

// LastActivityAtGTE applies the GTE predicate on the "last_activity_at" field.
func LastActivityAtGTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldLastActivityAt, v))
}

// LastActivityAtLT applies the LT predicate on the "last_activity_at" field.
func LastActivityAtLT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldLastActivityAt, v))
}

// LastActivityAtLTE applies the LTE predicate on the "last_activity_at" field.
func LastActivityAtLTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldLastActivityAt, v))
}

// RequestSha256EQ applies the EQ predicate on the "request_sha256" field.
func RequestSha256EQ(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestSha256, v))
}

// RequestSha256NEQ applies the NEQ predicate on the "request_sha256" field.
func RequestSha256NEQ(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldRequestSha256, v))
}

// RequestSha256In applies the In predicate on the "request_sha256" field.
func RequestSha256In(vs ...[]byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldRequestSha256, vs...))
}

// RequestSha256NotIn applies the NotIn predicate on the "request_sha256" field.
func RequestSha256NotIn(vs ...[]byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldRequestSha256, vs...))
}

// RequestSha256GT applies the GT predicate on the "request_sha256" field.
func RequestSha256GT(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldRequestSha256, v))
}

// RequestSha256GTE applies the GTE predicate on the "request_sha256" field.
func RequestSha256GTE(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldRequestSha256, v))
}

// RequestSha256LT applies the LT predicate on the "request_sha256" field.
func RequestSha256LT(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldRequestSha256, v))
}

// RequestSha256LTE applies the LTE predicate on the "request_sha256" field.
func RequestSha256LTE(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldRequestSha256, v))
}

// RequestSha256IsNil applies the IsNil predicate on the "request_sha256" field.
func RequestSha256IsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldRequestSha256))
}

// RequestSha256NotNil applies the NotNil predicate on the "request_sha256" field.
func RequestSha256NotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldRequestSha256))
}

// ResponseSha256EQ applies the EQ predicate on the "response_sha256" field.
func ResponseSha256EQ(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldResponseSha256, v))
}

// ResponseSha256NEQ applies the NEQ predicate on the "response_sha256" field.
func ResponseSha256NEQ(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldResponseSha256, v))
}

// ResponseSha256In applies the In predicate on the "response_sha256" field.
func ResponseSha256In(vs ...[]byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldResponseSha256, vs...))
}

// ResponseSha256NotIn applies the NotIn predicate on the "response_sha256" field.
func ResponseSha256NotIn(vs ...[]byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldResponseSha256, vs...))
}

// ResponseSha256GT applies the GT predicate on the "response_sha256" field.
func ResponseSha256GT(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldResponseSha256, v))
}

// ResponseSha256GTE applies the GTE predicate on the "response_sha256" field.
func ResponseSha256GTE(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldResponseSha256, v))
}

// ResponseSha256LT applies the LT predicate on the "response_sha256" field.
func ResponseSha256LT(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldResponseSha256, v))
}

// ResponseSha256LTE applies the LTE predicate on the "response_sha256" field.
func ResponseSha256LTE(v []byte) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldResponseSha256, v))
}

// ResponseSha256IsNil applies the IsNil predicate on the "response_sha256" field.
func ResponseSha256IsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldResponseSha256))
}

// ResponseSha256NotNil applies the NotNil predicate on the "response_sha256" field.
func ResponseSha256NotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldResponseSha256))
}

// RequestPartCountEQ applies the EQ predicate on the "request_part_count" field.
func RequestPartCountEQ(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldRequestPartCount, v))
}

// RequestPartCountNEQ applies the NEQ predicate on the "request_part_count" field.
func RequestPartCountNEQ(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldRequestPartCount, v))
}

// RequestPartCountIn applies the In predicate on the "request_part_count" field.
func RequestPartCountIn(vs ...int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldRequestPartCount, vs...))
}

// RequestPartCountNotIn applies the NotIn predicate on the "request_part_count" field.
func RequestPartCountNotIn(vs ...int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldRequestPartCount, vs...))
}

// RequestPartCountGT applies the GT predicate on the "request_part_count" field.
func RequestPartCountGT(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldRequestPartCount, v))
}

// RequestPartCountGTE applies the GTE predicate on the "request_part_count" field.
func RequestPartCountGTE(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldRequestPartCount, v))
}

// RequestPartCountLT applies the LT predicate on the "request_part_count" field.
func RequestPartCountLT(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldRequestPartCount, v))
}

// RequestPartCountLTE applies the LTE predicate on the "request_part_count" field.
func RequestPartCountLTE(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldRequestPartCount, v))
}

// ResponsePartCountEQ applies the EQ predicate on the "response_part_count" field.
func ResponsePartCountEQ(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldResponsePartCount, v))
}

// ResponsePartCountNEQ applies the NEQ predicate on the "response_part_count" field.
func ResponsePartCountNEQ(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldResponsePartCount, v))
}

// ResponsePartCountIn applies the In predicate on the "response_part_count" field.
func ResponsePartCountIn(vs ...int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldResponsePartCount, vs...))
}

// ResponsePartCountNotIn applies the NotIn predicate on the "response_part_count" field.
func ResponsePartCountNotIn(vs ...int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldResponsePartCount, vs...))
}

// ResponsePartCountGT applies the GT predicate on the "response_part_count" field.
func ResponsePartCountGT(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldResponsePartCount, v))
}

// ResponsePartCountGTE applies the GTE predicate on the "response_part_count" field.
func ResponsePartCountGTE(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldResponsePartCount, v))
}

// ResponsePartCountLT applies the LT predicate on the "response_part_count" field.
func ResponsePartCountLT(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldResponsePartCount, v))
}

// ResponsePartCountLTE applies the LTE predicate on the "response_part_count" field.
func ResponsePartCountLTE(v int) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldResponsePartCount, v))
}

// SafeErrorSummaryEQ applies the EQ predicate on the "safe_error_summary" field.
func SafeErrorSummaryEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryNEQ applies the NEQ predicate on the "safe_error_summary" field.
func SafeErrorSummaryNEQ(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryIn applies the In predicate on the "safe_error_summary" field.
func SafeErrorSummaryIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldSafeErrorSummary, vs...))
}

// SafeErrorSummaryNotIn applies the NotIn predicate on the "safe_error_summary" field.
func SafeErrorSummaryNotIn(vs ...string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldSafeErrorSummary, vs...))
}

// SafeErrorSummaryGT applies the GT predicate on the "safe_error_summary" field.
func SafeErrorSummaryGT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryGTE applies the GTE predicate on the "safe_error_summary" field.
func SafeErrorSummaryGTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryLT applies the LT predicate on the "safe_error_summary" field.
func SafeErrorSummaryLT(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryLTE applies the LTE predicate on the "safe_error_summary" field.
func SafeErrorSummaryLTE(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryContains applies the Contains predicate on the "safe_error_summary" field.
func SafeErrorSummaryContains(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContains(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryHasPrefix applies the HasPrefix predicate on the "safe_error_summary" field.
func SafeErrorSummaryHasPrefix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasPrefix(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryHasSuffix applies the HasSuffix predicate on the "safe_error_summary" field.
func SafeErrorSummaryHasSuffix(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldHasSuffix(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryIsNil applies the IsNil predicate on the "safe_error_summary" field.
func SafeErrorSummaryIsNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIsNull(FieldSafeErrorSummary))
}

// SafeErrorSummaryNotNil applies the NotNil predicate on the "safe_error_summary" field.
func SafeErrorSummaryNotNil() predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotNull(FieldSafeErrorSummary))
}

// SafeErrorSummaryEqualFold applies the EqualFold predicate on the "safe_error_summary" field.
func SafeErrorSummaryEqualFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEqualFold(FieldSafeErrorSummary, v))
}

// SafeErrorSummaryContainsFold applies the ContainsFold predicate on the "safe_error_summary" field.
func SafeErrorSummaryContainsFold(v string) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldContainsFold(FieldSafeErrorSummary, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasContentParts applies the HasEdge predicate on the "content_parts" edge.
func HasContentParts() predicate.AuditInteraction {
	return predicate.AuditInteraction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ContentPartsTable, ContentPartsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentPartsWith applies the HasEdge predicate on the "content_parts" edge with a given conditions (other predicates).
func HasContentPartsWith(preds ...predicate.AuditContentPart) predicate.AuditInteraction {
	return predicate.AuditInteraction(func(s *sql.Selector) {
		step := newContentPartsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditInteraction) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditInteraction) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditInteraction) predicate.AuditInteraction {
	return predicate.AuditInteraction(sql.NotPredicates(p))
}
