// Code generated by ent, DO NOT EDIT.

package auditcontentpart

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the auditcontentpart type in the database.
	Label = "audit_content_part"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInteractionID holds the string denoting the interaction_id field in the database.
	FieldInteractionID = "interaction_id"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldSequence holds the string denoting the sequence field in the database.
	FieldSequence = "sequence"
	// FieldNonce holds the string denoting the nonce field in the database.
	FieldNonce = "nonce"
	// FieldCiphertext holds the string denoting the ciphertext field in the database.
	FieldCiphertext = "ciphertext"
	// FieldAuthTag holds the string denoting the auth_tag field in the database.
	FieldAuthTag = "auth_tag"
	// FieldKeyVersion holds the string denoting the key_version field in the database.
	FieldKeyVersion = "key_version"
	// FieldAadFormatVersion holds the string denoting the aad_format_version field in the database.
	FieldAadFormatVersion = "aad_format_version"
	// FieldPlaintextLength holds the string denoting the plaintext_length field in the database.
	FieldPlaintextLength = "plaintext_length"
	// FieldCiphertextLength holds the string denoting the ciphertext_length field in the database.
	FieldCiphertextLength = "ciphertext_length"
	// FieldPlaintextSha256 holds the string denoting the plaintext_sha256 field in the database.
	FieldPlaintextSha256 = "plaintext_sha256"
	// FieldCiphertextSha256 holds the string denoting the ciphertext_sha256 field in the database.
	FieldCiphertextSha256 = "ciphertext_sha256"
	// FieldDownstreamWriteResult holds the string denoting the downstream_write_result field in the database.
	FieldDownstreamWriteResult = "downstream_write_result"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeInteraction holds the string denoting the interaction edge name in mutations.
	EdgeInteraction = "interaction"
	// Table holds the table name of the auditcontentpart in the database.
	Table = "audit_content_parts"
	// InteractionTable is the table that holds the interaction relation/edge.
	InteractionTable = "audit_content_parts"
	// InteractionInverseTable is the table name for the AuditInteraction entity.
	// It exists in this package in order to avoid circular dependency with the "auditinteraction" package.
	InteractionInverseTable = "audit_interactions"
	// InteractionColumn is the table column denoting the interaction relation/edge.
	InteractionColumn = "interaction_id"
)

// Columns holds all SQL columns for auditcontentpart fields.
var Columns = []string{
	FieldID,
	FieldInteractionID,
	FieldDirection,
	FieldSequence,
	FieldNonce,
	FieldCiphertext,
	FieldAuthTag,
	FieldKeyVersion,
	FieldAadFormatVersion,
	FieldPlaintextLength,
	FieldCiphertextLength,
	FieldPlaintextSha256,
	FieldCiphertextSha256,
	FieldDownstreamWriteResult,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyVersionValidator is a validator for the "key_version" field. It is called by the builders before save.
	KeyVersionValidator func(string) error
	// AadFormatVersionValidator is a validator for the "aad_format_version" field. It is called by the builders before save.
	AadFormatVersionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Direction defines the type for the "direction" enum field.
type Direction string

// Direction values.
const (
	DirectionRequest  Direction = "request"
	DirectionResponse Direction = "response"
)

func (d Direction) String() string {
	return string(d)
}

// DirectionValidator is a validator for the "direction" field enum values. It is called by the builders before save.
func DirectionValidator(d Direction) error {
	switch d {
	case DirectionRequest, DirectionResponse:
		return nil
	default:
		return fmt.Errorf("auditcontentpart: invalid enum value for direction field: %q", d)
	}
}

// DownstreamWriteResult defines the type for the "downstream_write_result" enum field.
type DownstreamWriteResult string

// DownstreamWriteResultNotApplicable is the default value of the DownstreamWriteResult enum.
const DefaultDownstreamWriteResult = DownstreamWriteResultNotApplicable

// DownstreamWriteResult values.
const (
	DownstreamWriteResultNotApplicable DownstreamWriteResult = "not_applicable"
	DownstreamWriteResultPending       DownstreamWriteResult = "pending"
	DownstreamWriteResultSucceeded     DownstreamWriteResult = "succeeded"
	DownstreamWriteResultFailed        DownstreamWriteResult = "failed"
	DownstreamWriteResultUnknown       DownstreamWriteResult = "unknown"
)

func (dwr DownstreamWriteResult) String() string {
	return string(dwr)
}

// DownstreamWriteResultValidator is a validator for the "downstream_write_result" field enum values. It is called by the builders before save.
func DownstreamWriteResultValidator(dwr DownstreamWriteResult) error {
	switch dwr {
	case DownstreamWriteResultNotApplicable, DownstreamWriteResultPending, DownstreamWriteResultSucceeded, DownstreamWriteResultFailed, DownstreamWriteResultUnknown:
		return nil
	default:
		return fmt.Errorf("auditcontentpart: invalid enum value for downstream_write_result field: %q", dwr)
	}
}

// OrderOption defines the ordering options for the AuditContentPart queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInteractionID orders the results by the interaction_id field.
func ByInteractionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInteractionID, opts...).ToFunc()
}

// ByDirection orders the results by the direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// BySequence orders the results by the sequence field.
func BySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequence, opts...).ToFunc()
}

// ByKeyVersion orders the results by the key_version field.
func ByKeyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyVersion, opts...).ToFunc()
}

// ByAadFormatVersion orders the results by the aad_format_version field.
func ByAadFormatVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAadFormatVersion, opts...).ToFunc()
}

// ByPlaintextLength orders the results by the plaintext_length field.
func ByPlaintextLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaintextLength, opts...).ToFunc()
}

// ByCiphertextLength orders the results by the ciphertext_length field.
func ByCiphertextLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCiphertextLength, opts...).ToFunc()
}

// ByDownstreamWriteResult orders the results by the downstream_write_result field.
func ByDownstreamWriteResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownstreamWriteResult, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByInteractionField orders the results by interaction field.
func ByInteractionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInteractionStep(), sql.OrderByField(field, opts...))
	}
}
func newInteractionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InteractionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InteractionTable, InteractionColumn),
	)
}
