// Code generated by ent, DO NOT EDIT.

package auditcontentpart

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldID, id))
}

// InteractionID applies equality check predicate on the "interaction_id" field. It's identical to InteractionIDEQ.
func InteractionID(v uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldInteractionID, v))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldSequence, v))
}

// Nonce applies equality check predicate on the "nonce" field. It's identical to NonceEQ.
func Nonce(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldNonce, v))
}

// Ciphertext applies equality check predicate on the "ciphertext" field. It's identical to CiphertextEQ.
func Ciphertext(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldCiphertext, v))
}

// AuthTag applies equality check predicate on the "auth_tag" field. It's identical to AuthTagEQ.
func AuthTag(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldAuthTag, v))
}

// KeyVersion applies equality check predicate on the "key_version" field. It's identical to KeyVersionEQ.
func KeyVersion(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldKeyVersion, v))
}

// AadFormatVersion applies equality check predicate on the "aad_format_version" field. It's identical to AadFormatVersionEQ.
func AadFormatVersion(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldAadFormatVersion, v))
}

// PlaintextLength applies equality check predicate on the "plaintext_length" field. It's identical to PlaintextLengthEQ.
func PlaintextLength(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldPlaintextLength, v))
}

// CiphertextLength applies equality check predicate on the "ciphertext_length" field. It's identical to CiphertextLengthEQ.
func CiphertextLength(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldCiphertextLength, v))
}

// PlaintextSha256 applies equality check predicate on the "plaintext_sha256" field. It's identical to PlaintextSha256EQ.
func PlaintextSha256(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldPlaintextSha256, v))
}

// CiphertextSha256 applies equality check predicate on the "ciphertext_sha256" field. It's identical to CiphertextSha256EQ.
func CiphertextSha256(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldCiphertextSha256, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldCreatedAt, v))
}

// InteractionIDEQ applies the EQ predicate on the "interaction_id" field.
func InteractionIDEQ(v uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldInteractionID, v))
}

// InteractionIDNEQ applies the NEQ predicate on the "interaction_id" field.
func InteractionIDNEQ(v uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldInteractionID, v))
}

// InteractionIDIn applies the In predicate on the "interaction_id" field.
func InteractionIDIn(vs ...uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldInteractionID, vs...))
}

// InteractionIDNotIn applies the NotIn predicate on the "interaction_id" field.
func InteractionIDNotIn(vs ...uuid.UUID) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldInteractionID, vs...))
}

// DirectionEQ applies the EQ predicate on the "direction" field.
func DirectionEQ(v Direction) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldDirection, v))
}

// DirectionNEQ applies the NEQ predicate on the "direction" field.
func DirectionNEQ(v Direction) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldDirection, v))
}

// DirectionIn applies the In predicate on the "direction" field.
func DirectionIn(vs ...Direction) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldDirection, vs...))
}

// DirectionNotIn applies the NotIn predicate on the "direction" field.
func DirectionNotIn(vs ...Direction) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldDirection, vs...))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldSequence, v))
}

// NonceEQ applies the EQ predicate on the "nonce" field.
func NonceEQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldNonce, v))
}

// NonceNEQ applies the NEQ predicate on the "nonce" field.
func NonceNEQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldNonce, v))
}

// NonceIn applies the In predicate on the "nonce" field.
func NonceIn(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldNonce, vs...))
}

// NonceNotIn applies the NotIn predicate on the "nonce" field.
func NonceNotIn(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldNonce, vs...))
}

// NonceGT applies the GT predicate on the "nonce" field.
func NonceGT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldNonce, v))
}

// NonceGTE applies the GTE predicate on the "nonce" field.
func NonceGTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldNonce, v))
}

// NonceLT applies the LT predicate on the "nonce" field.
func NonceLT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldNonce, v))
}

// NonceLTE applies the LTE predicate on the "nonce" field.
func NonceLTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldNonce, v))
}

// CiphertextEQ applies the EQ predicate on the "ciphertext" field.
func CiphertextEQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldCiphertext, v))
}

// CiphertextNEQ applies the NEQ predicate on the "ciphertext" field.
func CiphertextNEQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldCiphertext, v))
}

// CiphertextIn applies the In predicate on the "ciphertext" field.
func CiphertextIn(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldCiphertext, vs...))
}

// CiphertextNotIn applies the NotIn predicate on the "ciphertext" field.
func CiphertextNotIn(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldCiphertext, vs...))
}

// CiphertextGT applies the GT predicate on the "ciphertext" field.
func CiphertextGT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldCiphertext, v))
}

// CiphertextGTE applies the GTE predicate on the "ciphertext" field.
func CiphertextGTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldCiphertext, v))
}

// CiphertextLT applies the LT predicate on the "ciphertext" field.
func CiphertextLT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldCiphertext, v))
}

// CiphertextLTE applies the LTE predicate on the "ciphertext" field.
func CiphertextLTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldCiphertext, v))
}

// AuthTagEQ applies the EQ predicate on the "auth_tag" field.
func AuthTagEQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldAuthTag, v))
}

// AuthTagNEQ applies the NEQ predicate on the "auth_tag" field.
func AuthTagNEQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldAuthTag, v))
}

// AuthTagIn applies the In predicate on the "auth_tag" field.
func AuthTagIn(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldAuthTag, vs...))
}

// AuthTagNotIn applies the NotIn predicate on the "auth_tag" field.
func AuthTagNotIn(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldAuthTag, vs...))
}

// AuthTagGT applies the GT predicate on the "auth_tag" field.
func AuthTagGT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldAuthTag, v))
}

// AuthTagGTE applies the GTE predicate on the "auth_tag" field.
func AuthTagGTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldAuthTag, v))
}

// AuthTagLT applies the LT predicate on the "auth_tag" field.
func AuthTagLT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldAuthTag, v))
}

// AuthTagLTE applies the LTE predicate on the "auth_tag" field.
func AuthTagLTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldAuthTag, v))
}

// KeyVersionEQ applies the EQ predicate on the "key_version" field.
func KeyVersionEQ(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldKeyVersion, v))
}

// KeyVersionNEQ applies the NEQ predicate on the "key_version" field.
func KeyVersionNEQ(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldKeyVersion, v))
}

// KeyVersionIn applies the In predicate on the "key_version" field.
func KeyVersionIn(vs ...string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldKeyVersion, vs...))
}

// KeyVersionNotIn applies the NotIn predicate on the "key_version" field.
func KeyVersionNotIn(vs ...string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldKeyVersion, vs...))
}

// KeyVersionGT applies the GT predicate on the "key_version" field.
func KeyVersionGT(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldKeyVersion, v))
}

// KeyVersionGTE applies the GTE predicate on the "key_version" field.
func KeyVersionGTE(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldKeyVersion, v))
}

// KeyVersionLT applies the LT predicate on the "key_version" field.
func KeyVersionLT(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldKeyVersion, v))
}

// KeyVersionLTE applies the LTE predicate on the "key_version" field.
func KeyVersionLTE(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldKeyVersion, v))
}

// KeyVersionContains applies the Contains predicate on the "key_version" field.
func KeyVersionContains(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldContains(FieldKeyVersion, v))
}

// KeyVersionHasPrefix applies the HasPrefix predicate on the "key_version" field.
func KeyVersionHasPrefix(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldHasPrefix(FieldKeyVersion, v))
}

// KeyVersionHasSuffix applies the HasSuffix predicate on the "key_version" field.
func KeyVersionHasSuffix(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldHasSuffix(FieldKeyVersion, v))
}

// KeyVersionEqualFold applies the EqualFold predicate on the "key_version" field.
func KeyVersionEqualFold(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEqualFold(FieldKeyVersion, v))
}

// KeyVersionContainsFold applies the ContainsFold predicate on the "key_version" field.
func KeyVersionContainsFold(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldContainsFold(FieldKeyVersion, v))
}

// AadFormatVersionEQ applies the EQ predicate on the "aad_format_version" field.
func AadFormatVersionEQ(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldAadFormatVersion, v))
}

// AadFormatVersionNEQ applies the NEQ predicate on the "aad_format_version" field.
func AadFormatVersionNEQ(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldAadFormatVersion, v))
}

// AadFormatVersionIn applies the In predicate on the "aad_format_version" field.
func AadFormatVersionIn(vs ...string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldAadFormatVersion, vs...))
}

// AadFormatVersionNotIn applies the NotIn predicate on the "aad_format_version" field.
func AadFormatVersionNotIn(vs ...string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldAadFormatVersion, vs...))
}

// AadFormatVersionGT applies the GT predicate on the "aad_format_version" field.
func AadFormatVersionGT(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldAadFormatVersion, v))
}

// AadFormatVersionGTE applies the GTE predicate on the "aad_format_version" field.
func AadFormatVersionGTE(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldAadFormatVersion, v))
}

// AadFormatVersionLT applies the LT predicate on the "aad_format_version" field.
func AadFormatVersionLT(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldAadFormatVersion, v))
}

// AadFormatVersionLTE applies the LTE predicate on the "aad_format_version" field.
func AadFormatVersionLTE(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldAadFormatVersion, v))
}

// AadFormatVersionContains applies the Contains predicate on the "aad_format_version" field.
func AadFormatVersionContains(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldContains(FieldAadFormatVersion, v))
}

// AadFormatVersionHasPrefix applies the HasPrefix predicate on the "aad_format_version" field.
func AadFormatVersionHasPrefix(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldHasPrefix(FieldAadFormatVersion, v))
}

// AadFormatVersionHasSuffix applies the HasSuffix predicate on the "aad_format_version" field.
func AadFormatVersionHasSuffix(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldHasSuffix(FieldAadFormatVersion, v))
}

// AadFormatVersionEqualFold applies the EqualFold predicate on the "aad_format_version" field.
func AadFormatVersionEqualFold(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEqualFold(FieldAadFormatVersion, v))
}

// AadFormatVersionContainsFold applies the ContainsFold predicate on the "aad_format_version" field.
func AadFormatVersionContainsFold(v string) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldContainsFold(FieldAadFormatVersion, v))
}

// PlaintextLengthEQ applies the EQ predicate on the "plaintext_length" field.
func PlaintextLengthEQ(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldPlaintextLength, v))
}

// PlaintextLengthNEQ applies the NEQ predicate on the "plaintext_length" field.
func PlaintextLengthNEQ(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldPlaintextLength, v))
}

// PlaintextLengthIn applies the In predicate on the "plaintext_length" field.
func PlaintextLengthIn(vs ...int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldPlaintextLength, vs...))
}

// PlaintextLengthNotIn applies the NotIn predicate on the "plaintext_length" field.
func PlaintextLengthNotIn(vs ...int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldPlaintextLength, vs...))
}

// PlaintextLengthGT applies the GT predicate on the "plaintext_length" field.
func PlaintextLengthGT(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldPlaintextLength, v))
}

// PlaintextLengthGTE applies the GTE predicate on the "plaintext_length" field.
func PlaintextLengthGTE(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldPlaintextLength, v))
}

// PlaintextLengthLT applies the LT predicate on the "plaintext_length" field.
func PlaintextLengthLT(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldPlaintextLength, v))
}

// PlaintextLengthLTE applies the LTE predicate on the "plaintext_length" field.
func PlaintextLengthLTE(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldPlaintextLength, v))
}

// CiphertextLengthEQ applies the EQ predicate on the "ciphertext_length" field.
func CiphertextLengthEQ(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldCiphertextLength, v))
}

// CiphertextLengthNEQ applies the NEQ predicate on the "ciphertext_length" field.
func CiphertextLengthNEQ(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldCiphertextLength, v))
}

// CiphertextLengthIn applies the In predicate on the "ciphertext_length" field.
func CiphertextLengthIn(vs ...int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldCiphertextLength, vs...))
}

// CiphertextLengthNotIn applies the NotIn predicate on the "ciphertext_length" field.
func CiphertextLengthNotIn(vs ...int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldCiphertextLength, vs...))
}

// CiphertextLengthGT applies the GT predicate on the "ciphertext_length" field.
func CiphertextLengthGT(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldCiphertextLength, v))
}

// CiphertextLengthGTE applies the GTE predicate on the "ciphertext_length" field.
func CiphertextLengthGTE(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldCiphertextLength, v))
}

// CiphertextLengthLT applies the LT predicate on the "ciphertext_length" field.
func CiphertextLengthLT(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldCiphertextLength, v))
}

// CiphertextLengthLTE applies the LTE predicate on the "ciphertext_length" field.
func CiphertextLengthLTE(v int64) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldCiphertextLength, v))
}

// PlaintextSha256EQ applies the EQ predicate on the "plaintext_sha256" field.
func PlaintextSha256EQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldPlaintextSha256, v))
}

// PlaintextSha256NEQ applies the NEQ predicate on the "plaintext_sha256" field.
func PlaintextSha256NEQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldPlaintextSha256, v))
}

// PlaintextSha256In applies the In predicate on the "plaintext_sha256" field.
func PlaintextSha256In(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldPlaintextSha256, vs...))
}

// PlaintextSha256NotIn applies the NotIn predicate on the "plaintext_sha256" field.
func PlaintextSha256NotIn(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldPlaintextSha256, vs...))
}

// PlaintextSha256GT applies the GT predicate on the "plaintext_sha256" field.
func PlaintextSha256GT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldPlaintextSha256, v))
}

// PlaintextSha256GTE applies the GTE predicate on the "plaintext_sha256" field.
func PlaintextSha256GTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldPlaintextSha256, v))
}

// PlaintextSha256LT applies the LT predicate on the "plaintext_sha256" field.
func PlaintextSha256LT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldPlaintextSha256, v))
}

// PlaintextSha256LTE applies the LTE predicate on the "plaintext_sha256" field.
func PlaintextSha256LTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldPlaintextSha256, v))
}

// CiphertextSha256EQ applies the EQ predicate on the "ciphertext_sha256" field.
func CiphertextSha256EQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldCiphertextSha256, v))
}

// CiphertextSha256NEQ applies the NEQ predicate on the "ciphertext_sha256" field.
func CiphertextSha256NEQ(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldCiphertextSha256, v))
}

// CiphertextSha256In applies the In predicate on the "ciphertext_sha256" field.
func CiphertextSha256In(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldCiphertextSha256, vs...))
}

// CiphertextSha256NotIn applies the NotIn predicate on the "ciphertext_sha256" field.
func CiphertextSha256NotIn(vs ...[]byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldCiphertextSha256, vs...))
}

// CiphertextSha256GT applies the GT predicate on the "ciphertext_sha256" field.
func CiphertextSha256GT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldCiphertextSha256, v))
}

// CiphertextSha256GTE applies the GTE predicate on the "ciphertext_sha256" field.
func CiphertextSha256GTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldCiphertextSha256, v))
}

// CiphertextSha256LT applies the LT predicate on the "ciphertext_sha256" field.
func CiphertextSha256LT(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldCiphertextSha256, v))
}

// CiphertextSha256LTE applies the LTE predicate on the "ciphertext_sha256" field.
func CiphertextSha256LTE(v []byte) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldCiphertextSha256, v))
}

// DownstreamWriteResultEQ applies the EQ predicate on the "downstream_write_result" field.
func DownstreamWriteResultEQ(v DownstreamWriteResult) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldDownstreamWriteResult, v))
}

// DownstreamWriteResultNEQ applies the NEQ predicate on the "downstream_write_result" field.
func DownstreamWriteResultNEQ(v DownstreamWriteResult) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldDownstreamWriteResult, v))
}

// DownstreamWriteResultIn applies the In predicate on the "downstream_write_result" field.
func DownstreamWriteResultIn(vs ...DownstreamWriteResult) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldDownstreamWriteResult, vs...))
}

// DownstreamWriteResultNotIn applies the NotIn predicate on the "downstream_write_result" field.
func DownstreamWriteResultNotIn(vs ...DownstreamWriteResult) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldDownstreamWriteResult, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.FieldLTE(FieldCreatedAt, v))
}

// HasInteraction applies the HasEdge predicate on the "interaction" edge.
func HasInteraction() predicate.AuditContentPart {
	return predicate.AuditContentPart(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InteractionTable, InteractionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInteractionWith applies the HasEdge predicate on the "interaction" edge with a given conditions (other predicates).
func HasInteractionWith(preds ...predicate.AuditInteraction) predicate.AuditContentPart {
	return predicate.AuditContentPart(func(s *sql.Selector) {
		step := newInteractionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditContentPart) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditContentPart) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditContentPart) predicate.AuditContentPart {
	return predicate.AuditContentPart(sql.NotPredicates(p))
}
