// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/auditinteraction"
	"github.com/google/uuid"
)

// AuditInteraction is the model entity for the AuditInteraction schema.
type AuditInteraction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GatewayRequestID holds the value of the "gateway_request_id" field.
	GatewayRequestID uuid.UUID `json:"gateway_request_id,omitempty"`
	// WorkSessionID holds the value of the "work_session_id" field.
	WorkSessionID *uuid.UUID `json:"work_session_id,omitempty"`
	// SubjectUserID holds the value of the "subject_user_id" field.
	SubjectUserID *int64 `json:"subject_user_id,omitempty"`
	// SubjectEmailSnapshot holds the value of the "subject_email_snapshot" field.
	SubjectEmailSnapshot *string `json:"subject_email_snapshot,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// APIKeyFingerprint holds the value of the "api_key_fingerprint" field.
	APIKeyFingerprint *string `json:"api_key_fingerprint,omitempty"`
	// ProfileVersion holds the value of the "profile_version" field.
	ProfileVersion string `json:"profile_version,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol auditinteraction.Protocol `json:"protocol,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Transport holds the value of the "transport" field.
	Transport auditinteraction.Transport `json:"transport,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel *string `json:"requested_model,omitempty"`
	// ResolvedModel holds the value of the "resolved_model" field.
	ResolvedModel *string `json:"resolved_model,omitempty"`
	// RequestOutcome holds the value of the "request_outcome" field.
	RequestOutcome auditinteraction.RequestOutcome `json:"request_outcome,omitempty"`
	// RequestOutcomeVersion holds the value of the "request_outcome_version" field.
	RequestOutcomeVersion int64 `json:"request_outcome_version,omitempty"`
	// ContentState holds the value of the "content_state" field.
	ContentState auditinteraction.ContentState `json:"content_state,omitempty"`
	// ContentStateVersion holds the value of the "content_state_version" field.
	ContentStateVersion int64 `json:"content_state_version,omitempty"`
	// DownstreamStatus holds the value of the "downstream_status" field.
	DownstreamStatus *int16 `json:"downstream_status,omitempty"`
	// DownstreamWriteResult holds the value of the "downstream_write_result" field.
	DownstreamWriteResult auditinteraction.DownstreamWriteResult `json:"downstream_write_result,omitempty"`
	// AdmittedAt holds the value of the "admitted_at" field.
	AdmittedAt time.Time `json:"admitted_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// LastActivityAt holds the value of the "last_activity_at" field.
	LastActivityAt time.Time `json:"last_activity_at,omitempty"`
	// RequestSha256 holds the value of the "request_sha256" field.
	RequestSha256 *[]byte `json:"request_sha256,omitempty"`
	// ResponseSha256 holds the value of the "response_sha256" field.
	ResponseSha256 *[]byte `json:"response_sha256,omitempty"`
	// RequestPartCount holds the value of the "request_part_count" field.
	RequestPartCount int `json:"request_part_count,omitempty"`
	// ResponsePartCount holds the value of the "response_part_count" field.
	ResponsePartCount int `json:"response_part_count,omitempty"`
	// SafeErrorSummary holds the value of the "safe_error_summary" field.
	SafeErrorSummary *string `json:"safe_error_summary,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AuditInteractionQuery when eager-loading is set.
	Edges        AuditInteractionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AuditInteractionEdges holds the relations/edges for other nodes in the graph.
type AuditInteractionEdges struct {
	// ContentParts holds the value of the content_parts edge.
	ContentParts []*AuditContentPart `json:"content_parts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ContentPartsOrErr returns the ContentParts value or an error if the edge
// was not loaded in eager-loading.
func (e AuditInteractionEdges) ContentPartsOrErr() ([]*AuditContentPart, error) {
	if e.loadedTypes[0] {
		return e.ContentParts, nil
	}
	return nil, &NotLoadedError{edge: "content_parts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditInteraction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditinteraction.FieldWorkSessionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case auditinteraction.FieldRequestSha256, auditinteraction.FieldResponseSha256:
			values[i] = new([]byte)
		case auditinteraction.FieldSubjectUserID, auditinteraction.FieldAPIKeyID, auditinteraction.FieldRequestOutcomeVersion, auditinteraction.FieldContentStateVersion, auditinteraction.FieldDownstreamStatus, auditinteraction.FieldRequestPartCount, auditinteraction.FieldResponsePartCount:
			values[i] = new(sql.NullInt64)
		case auditinteraction.FieldSubjectEmailSnapshot, auditinteraction.FieldAPIKeyFingerprint, auditinteraction.FieldProfileVersion, auditinteraction.FieldProtocol, auditinteraction.FieldEndpoint, auditinteraction.FieldMethod, auditinteraction.FieldTransport, auditinteraction.FieldRequestedModel, auditinteraction.FieldResolvedModel, auditinteraction.FieldRequestOutcome, auditinteraction.FieldContentState, auditinteraction.FieldDownstreamWriteResult, auditinteraction.FieldSafeErrorSummary:
			values[i] = new(sql.NullString)
		case auditinteraction.FieldAdmittedAt, auditinteraction.FieldCompletedAt, auditinteraction.FieldExpiresAt, auditinteraction.FieldLastActivityAt, auditinteraction.FieldCreatedAt, auditinteraction.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case auditinteraction.FieldID, auditinteraction.FieldGatewayRequestID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditInteraction fields.
func (_m *AuditInteraction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditinteraction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case auditinteraction.FieldGatewayRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_request_id", values[i])
			} else if value != nil {
				_m.GatewayRequestID = *value
			}
		case auditinteraction.FieldWorkSessionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field work_session_id", values[i])
			} else if value.Valid {
				_m.WorkSessionID = new(uuid.UUID)
				*_m.WorkSessionID = *value.S.(*uuid.UUID)
			}
		case auditinteraction.FieldSubjectUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subject_user_id", values[i])
			} else if value.Valid {
				_m.SubjectUserID = new(int64)
				*_m.SubjectUserID = value.Int64
			}
		case auditinteraction.FieldSubjectEmailSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_email_snapshot", values[i])
			} else if value.Valid {
				_m.SubjectEmailSnapshot = new(string)
				*_m.SubjectEmailSnapshot = value.String
			}
		case auditinteraction.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case auditinteraction.FieldAPIKeyFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_fingerprint", values[i])
			} else if value.Valid {
				_m.APIKeyFingerprint = new(string)
				*_m.APIKeyFingerprint = value.String
			}
		case auditinteraction.FieldProfileVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_version", values[i])
			} else if value.Valid {
				_m.ProfileVersion = value.String
			}
		case auditinteraction.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = auditinteraction.Protocol(value.String)
			}
		case auditinteraction.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case auditinteraction.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case auditinteraction.FieldTransport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transport", values[i])
			} else if value.Valid {
				_m.Transport = auditinteraction.Transport(value.String)
			}
		case auditinteraction.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = new(string)
				*_m.RequestedModel = value.String
			}
		case auditinteraction.FieldResolvedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_model", values[i])
			} else if value.Valid {
				_m.ResolvedModel = new(string)
				*_m.ResolvedModel = value.String
			}
		case auditinteraction.FieldRequestOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_outcome", values[i])
			} else if value.Valid {
				_m.RequestOutcome = auditinteraction.RequestOutcome(value.String)
			}
		case auditinteraction.FieldRequestOutcomeVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_outcome_version", values[i])
			} else if value.Valid {
				_m.RequestOutcomeVersion = value.Int64
			}
		case auditinteraction.FieldContentState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_state", values[i])
			} else if value.Valid {
				_m.ContentState = auditinteraction.ContentState(value.String)
			}
		case auditinteraction.FieldContentStateVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field content_state_version", values[i])
			} else if value.Valid {
				_m.ContentStateVersion = value.Int64
			}
		case auditinteraction.FieldDownstreamStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field downstream_status", values[i])
			} else if value.Valid {
				_m.DownstreamStatus = new(int16)
				*_m.DownstreamStatus = int16(value.Int64)
			}
		case auditinteraction.FieldDownstreamWriteResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field downstream_write_result", values[i])
			} else if value.Valid {
				_m.DownstreamWriteResult = auditinteraction.DownstreamWriteResult(value.String)
			}
		case auditinteraction.FieldAdmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field admitted_at", values[i])
			} else if value.Valid {
				_m.AdmittedAt = value.Time
			}
		case auditinteraction.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case auditinteraction.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case auditinteraction.FieldLastActivityAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_activity_at", values[i])
			} else if value.Valid {
				_m.LastActivityAt = value.Time
			}
		case auditinteraction.FieldRequestSha256:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_sha256", values[i])
			} else if value != nil {
				_m.RequestSha256 = value
			}
		case auditinteraction.FieldResponseSha256:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_sha256", values[i])
			} else if value != nil {
				_m.ResponseSha256 = value
			}
		case auditinteraction.FieldRequestPartCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_part_count", values[i])
			} else if value.Valid {
				_m.RequestPartCount = int(value.Int64)
			}
		case auditinteraction.FieldResponsePartCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_part_count", values[i])
			} else if value.Valid {
				_m.ResponsePartCount = int(value.Int64)
			}
		case auditinteraction.FieldSafeErrorSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field safe_error_summary", values[i])
			} else if value.Valid {
				_m.SafeErrorSummary = new(string)
				*_m.SafeErrorSummary = value.String
			}
		case auditinteraction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case auditinteraction.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditInteraction.
// This includes values selected through modifiers, order, etc.
func (_m *AuditInteraction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryContentParts queries the "content_parts" edge of the AuditInteraction entity.
func (_m *AuditInteraction) QueryContentParts() *AuditContentPartQuery {
	return NewAuditInteractionClient(_m.config).QueryContentParts(_m)
}

// Update returns a builder for updating this AuditInteraction.
// Note that you need to call AuditInteraction.Unwrap() before calling this method if this AuditInteraction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditInteraction) Update() *AuditInteractionUpdateOne {
	return NewAuditInteractionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditInteraction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditInteraction) Unwrap() *AuditInteraction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditInteraction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditInteraction) String() string {
	var builder strings.Builder
	builder.WriteString("AuditInteraction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("gateway_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GatewayRequestID))
	builder.WriteString(", ")
	if v := _m.WorkSessionID; v != nil {
		builder.WriteString("work_session_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SubjectUserID; v != nil {
		builder.WriteString("subject_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SubjectEmailSnapshot; v != nil {
		builder.WriteString("subject_email_snapshot=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyFingerprint; v != nil {
		builder.WriteString("api_key_fingerprint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("profile_version=")
	builder.WriteString(_m.ProfileVersion)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocol))
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("transport=")
	builder.WriteString(fmt.Sprintf("%v", _m.Transport))
	builder.WriteString(", ")
	if v := _m.RequestedModel; v != nil {
		builder.WriteString("requested_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResolvedModel; v != nil {
		builder.WriteString("resolved_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("request_outcome=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestOutcome))
	builder.WriteString(", ")
	builder.WriteString("request_outcome_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestOutcomeVersion))
	builder.WriteString(", ")
	builder.WriteString("content_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContentState))
	builder.WriteString(", ")
	builder.WriteString("content_state_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContentStateVersion))
	builder.WriteString(", ")
	if v := _m.DownstreamStatus; v != nil {
		builder.WriteString("downstream_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("downstream_write_result=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownstreamWriteResult))
	builder.WriteString(", ")
	builder.WriteString("admitted_at=")
	builder.WriteString(_m.AdmittedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_activity_at=")
	builder.WriteString(_m.LastActivityAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RequestSha256; v != nil {
		builder.WriteString("request_sha256=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResponseSha256; v != nil {
		builder.WriteString("response_sha256=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_part_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestPartCount))
	builder.WriteString(", ")
	builder.WriteString("response_part_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponsePartCount))
	builder.WriteString(", ")
	if v := _m.SafeErrorSummary; v != nil {
		builder.WriteString("safe_error_summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuditInteractions is a parsable slice of AuditInteraction.
type AuditInteractions []*AuditInteraction
