// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/auditinteraction"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AuditInteractionDelete is the builder for deleting a AuditInteraction entity.
type AuditInteractionDelete struct {
	config
	hooks    []Hook
	mutation *AuditInteractionMutation
}

// Where appends a list predicates to the AuditInteractionDelete builder.
func (_d *AuditInteractionDelete) Where(ps ...predicate.AuditInteraction) *AuditInteractionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuditInteractionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuditInteractionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuditInteractionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(auditinteraction.Table, sqlgraph.NewFieldSpec(auditinteraction.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuditInteractionDeleteOne is the builder for deleting a single AuditInteraction entity.
type AuditInteractionDeleteOne struct {
	_d *AuditInteractionDelete
}

// Where appends a list predicates to the AuditInteractionDelete builder.
func (_d *AuditInteractionDeleteOne) Where(ps ...predicate.AuditInteraction) *AuditInteractionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuditInteractionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{auditinteraction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuditInteractionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
