// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/autocandidatepool"
	"github.com/google/uuid"
)

// AutoCandidatePool is the model entity for the AutoCandidatePool schema.
type AutoCandidatePool struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Generation holds the value of the "generation" field.
	Generation int64 `json:"generation,omitempty"`
	// Tier holds the value of the "tier" field.
	Tier autocandidatepool.Tier `json:"tier,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// CatalogEntryID holds the value of the "catalog_entry_id" field.
	CatalogEntryID uuid.UUID `json:"catalog_entry_id,omitempty"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// ValidUntil holds the value of the "valid_until" field.
	ValidUntil *time.Time `json:"valid_until,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AutoCandidatePool) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case autocandidatepool.FieldGeneration, autocandidatepool.FieldPosition:
			values[i] = new(sql.NullInt64)
		case autocandidatepool.FieldTier:
			values[i] = new(sql.NullString)
		case autocandidatepool.FieldValidFrom, autocandidatepool.FieldValidUntil, autocandidatepool.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case autocandidatepool.FieldID, autocandidatepool.FieldCatalogEntryID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AutoCandidatePool fields.
func (_m *AutoCandidatePool) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case autocandidatepool.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case autocandidatepool.FieldGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field generation", values[i])
			} else if value.Valid {
				_m.Generation = value.Int64
			}
		case autocandidatepool.FieldTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				_m.Tier = autocandidatepool.Tier(value.String)
			}
		case autocandidatepool.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case autocandidatepool.FieldCatalogEntryID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field catalog_entry_id", values[i])
			} else if value != nil {
				_m.CatalogEntryID = *value
			}
		case autocandidatepool.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case autocandidatepool.FieldValidUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_until", values[i])
			} else if value.Valid {
				_m.ValidUntil = new(time.Time)
				*_m.ValidUntil = value.Time
			}
		case autocandidatepool.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AutoCandidatePool.
// This includes values selected through modifiers, order, etc.
func (_m *AutoCandidatePool) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AutoCandidatePool.
// Note that you need to call AutoCandidatePool.Unwrap() before calling this method if this AutoCandidatePool
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AutoCandidatePool) Update() *AutoCandidatePoolUpdateOne {
	return NewAutoCandidatePoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AutoCandidatePool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AutoCandidatePool) Unwrap() *AutoCandidatePool {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AutoCandidatePool is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AutoCandidatePool) String() string {
	var builder strings.Builder
	builder.WriteString("AutoCandidatePool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Generation))
	builder.WriteString(", ")
	builder.WriteString("tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tier))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("catalog_entry_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CatalogEntryID))
	builder.WriteString(", ")
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidUntil; v != nil {
		builder.WriteString("valid_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AutoCandidatePools is a parsable slice of AutoCandidatePool.
type AutoCandidatePools []*AutoCandidatePool
