// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/gatewayinferencerun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GatewayInferenceRunUpdate is the builder for updating GatewayInferenceRun entities.
type GatewayInferenceRunUpdate struct {
	config
	hooks    []Hook
	mutation *GatewayInferenceRunMutation
}

// Where appends a list predicates to the GatewayInferenceRunUpdate builder.
func (_u *GatewayInferenceRunUpdate) Where(ps ...predicate.GatewayInferenceRun) *GatewayInferenceRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the GatewayInferenceRunMutation object of the builder.
func (_u *GatewayInferenceRunUpdate) Mutation() *GatewayInferenceRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GatewayInferenceRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GatewayInferenceRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GatewayInferenceRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GatewayInferenceRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GatewayInferenceRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gatewayinferencerun.Table, gatewayinferencerun.Columns, sqlgraph.NewFieldSpec(gatewayinferencerun.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ProviderRequestIDCleared() {
		_spec.ClearField(gatewayinferencerun.FieldProviderRequestID, field.TypeString)
	}
	if _u.mutation.InputUnitsCleared() {
		_spec.ClearField(gatewayinferencerun.FieldInputUnits, field.TypeInt64)
	}
	if _u.mutation.OutputUnitsCleared() {
		_spec.ClearField(gatewayinferencerun.FieldOutputUnits, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gatewayinferencerun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GatewayInferenceRunUpdateOne is the builder for updating a single GatewayInferenceRun entity.
type GatewayInferenceRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GatewayInferenceRunMutation
}

// Mutation returns the GatewayInferenceRunMutation object of the builder.
func (_u *GatewayInferenceRunUpdateOne) Mutation() *GatewayInferenceRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the GatewayInferenceRunUpdate builder.
func (_u *GatewayInferenceRunUpdateOne) Where(ps ...predicate.GatewayInferenceRun) *GatewayInferenceRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GatewayInferenceRunUpdateOne) Select(field string, fields ...string) *GatewayInferenceRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GatewayInferenceRun entity.
func (_u *GatewayInferenceRunUpdateOne) Save(ctx context.Context) (*GatewayInferenceRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GatewayInferenceRunUpdateOne) SaveX(ctx context.Context) *GatewayInferenceRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GatewayInferenceRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GatewayInferenceRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GatewayInferenceRunUpdateOne) sqlSave(ctx context.Context) (_node *GatewayInferenceRun, err error) {
	_spec := sqlgraph.NewUpdateSpec(gatewayinferencerun.Table, gatewayinferencerun.Columns, sqlgraph.NewFieldSpec(gatewayinferencerun.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GatewayInferenceRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gatewayinferencerun.FieldID)
		for _, f := range fields {
			if !gatewayinferencerun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gatewayinferencerun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ProviderRequestIDCleared() {
		_spec.ClearField(gatewayinferencerun.FieldProviderRequestID, field.TypeString)
	}
	if _u.mutation.InputUnitsCleared() {
		_spec.ClearField(gatewayinferencerun.FieldInputUnits, field.TypeInt64)
	}
	if _u.mutation.OutputUnitsCleared() {
		_spec.ClearField(gatewayinferencerun.FieldOutputUnits, field.TypeInt64)
	}
	_node = &GatewayInferenceRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gatewayinferencerun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
