// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/governanceevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// GovernanceEventCreate is the builder for creating a GovernanceEvent entity.
type GovernanceEventCreate struct {
	config
	mutation *GovernanceEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOperationID sets the "operation_id" field.
func (_c *GovernanceEventCreate) SetOperationID(v uuid.UUID) *GovernanceEventCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetEventSequence sets the "event_sequence" field.
func (_c *GovernanceEventCreate) SetEventSequence(v int) *GovernanceEventCreate {
	_c.mutation.SetEventSequence(v)
	return _c
}

// SetActorKind sets the "actor_kind" field.
func (_c *GovernanceEventCreate) SetActorKind(v governanceevent.ActorKind) *GovernanceEventCreate {
	_c.mutation.SetActorKind(v)
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *GovernanceEventCreate) SetActorUserID(v int64) *GovernanceEventCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_c *GovernanceEventCreate) SetNillableActorUserID(v *int64) *GovernanceEventCreate {
	if v != nil {
		_c.SetActorUserID(*v)
	}
	return _c
}

// SetDeploymentOperatorID sets the "deployment_operator_id" field.
func (_c *GovernanceEventCreate) SetDeploymentOperatorID(v string) *GovernanceEventCreate {
	_c.mutation.SetDeploymentOperatorID(v)
	return _c
}

// SetNillableDeploymentOperatorID sets the "deployment_operator_id" field if the given value is not nil.
func (_c *GovernanceEventCreate) SetNillableDeploymentOperatorID(v *string) *GovernanceEventCreate {
	if v != nil {
		_c.SetDeploymentOperatorID(*v)
	}
	return _c
}

// SetTargetKind sets the "target_kind" field.
func (_c *GovernanceEventCreate) SetTargetKind(v string) *GovernanceEventCreate {
	_c.mutation.SetTargetKind(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *GovernanceEventCreate) SetTargetID(v string) *GovernanceEventCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *GovernanceEventCreate) SetAction(v string) *GovernanceEventCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *GovernanceEventCreate) SetResult(v governanceevent.Result) *GovernanceEventCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *GovernanceEventCreate) SetReason(v string) *GovernanceEventCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *GovernanceEventCreate) SetNillableReason(v *string) *GovernanceEventCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetBeforeSummary sets the "before_summary" field.
func (_c *GovernanceEventCreate) SetBeforeSummary(v map[string]interface{}) *GovernanceEventCreate {
	_c.mutation.SetBeforeSummary(v)
	return _c
}

// SetAfterSummary sets the "after_summary" field.
func (_c *GovernanceEventCreate) SetAfterSummary(v map[string]interface{}) *GovernanceEventCreate {
	_c.mutation.SetAfterSummary(v)
	return _c
}

// SetRecoveryNonceFingerprint sets the "recovery_nonce_fingerprint" field.
func (_c *GovernanceEventCreate) SetRecoveryNonceFingerprint(v string) *GovernanceEventCreate {
	_c.mutation.SetRecoveryNonceFingerprint(v)
	return _c
}

// SetNillableRecoveryNonceFingerprint sets the "recovery_nonce_fingerprint" field if the given value is not nil.
func (_c *GovernanceEventCreate) SetNillableRecoveryNonceFingerprint(v *string) *GovernanceEventCreate {
	if v != nil {
		_c.SetRecoveryNonceFingerprint(*v)
	}
	return _c
}

// SetGatewayRequestID sets the "gateway_request_id" field.
func (_c *GovernanceEventCreate) SetGatewayRequestID(v string) *GovernanceEventCreate {
	_c.mutation.SetGatewayRequestID(v)
	return _c
}

// SetNillableGatewayRequestID sets the "gateway_request_id" field if the given value is not nil.
func (_c *GovernanceEventCreate) SetNillableGatewayRequestID(v *string) *GovernanceEventCreate {
	if v != nil {
		_c.SetGatewayRequestID(*v)
	}
	return _c
}

// SetSafeErrorSummary sets the "safe_error_summary" field.
func (_c *GovernanceEventCreate) SetSafeErrorSummary(v string) *GovernanceEventCreate {
	_c.mutation.SetSafeErrorSummary(v)
	return _c
}

// SetNillableSafeErrorSummary sets the "safe_error_summary" field if the given value is not nil.
func (_c *GovernanceEventCreate) SetNillableSafeErrorSummary(v *string) *GovernanceEventCreate {
	if v != nil {
		_c.SetSafeErrorSummary(*v)
	}
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *GovernanceEventCreate) SetOccurredAt(v time.Time) *GovernanceEventCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *GovernanceEventCreate) SetID(v uuid.UUID) *GovernanceEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GovernanceEventCreate) SetNillableID(v *uuid.UUID) *GovernanceEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetActorID sets the "actor" edge to the User entity by ID.
func (_c *GovernanceEventCreate) SetActorID(id int64) *GovernanceEventCreate {
	_c.mutation.SetActorID(id)
	return _c
}

// SetNillableActorID sets the "actor" edge to the User entity by ID if the given value is not nil.
func (_c *GovernanceEventCreate) SetNillableActorID(id *int64) *GovernanceEventCreate {
	if id != nil {
		_c = _c.SetActorID(*id)
	}
	return _c
}

// SetActor sets the "actor" edge to the User entity.
func (_c *GovernanceEventCreate) SetActor(v *User) *GovernanceEventCreate {
	return _c.SetActorID(v.ID)
}

// Mutation returns the GovernanceEventMutation object of the builder.
func (_c *GovernanceEventCreate) Mutation() *GovernanceEventMutation {
	return _c.mutation
}

// Save creates the GovernanceEvent in the database.
func (_c *GovernanceEventCreate) Save(ctx context.Context) (*GovernanceEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GovernanceEventCreate) SaveX(ctx context.Context) *GovernanceEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GovernanceEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GovernanceEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GovernanceEventCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := governanceevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GovernanceEventCreate) check() error {
	if _, ok := _c.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "GovernanceEvent.operation_id"`)}
	}
	if _, ok := _c.mutation.EventSequence(); !ok {
		return &ValidationError{Name: "event_sequence", err: errors.New(`ent: missing required field "GovernanceEvent.event_sequence"`)}
	}
	if _, ok := _c.mutation.ActorKind(); !ok {
		return &ValidationError{Name: "actor_kind", err: errors.New(`ent: missing required field "GovernanceEvent.actor_kind"`)}
	}
	if v, ok := _c.mutation.ActorKind(); ok {
		if err := governanceevent.ActorKindValidator(v); err != nil {
			return &ValidationError{Name: "actor_kind", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.actor_kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeploymentOperatorID(); ok {
		if err := governanceevent.DeploymentOperatorIDValidator(v); err != nil {
			return &ValidationError{Name: "deployment_operator_id", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.deployment_operator_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetKind(); !ok {
		return &ValidationError{Name: "target_kind", err: errors.New(`ent: missing required field "GovernanceEvent.target_kind"`)}
	}
	if v, ok := _c.mutation.TargetKind(); ok {
		if err := governanceevent.TargetKindValidator(v); err != nil {
			return &ValidationError{Name: "target_kind", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.target_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "GovernanceEvent.target_id"`)}
	}
	if v, ok := _c.mutation.TargetID(); ok {
		if err := governanceevent.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.target_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "GovernanceEvent.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := governanceevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "GovernanceEvent.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := governanceevent.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.result": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := governanceevent.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RecoveryNonceFingerprint(); ok {
		if err := governanceevent.RecoveryNonceFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "recovery_nonce_fingerprint", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.recovery_nonce_fingerprint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.GatewayRequestID(); ok {
		if err := governanceevent.GatewayRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "gateway_request_id", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.gateway_request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SafeErrorSummary(); ok {
		if err := governanceevent.SafeErrorSummaryValidator(v); err != nil {
			return &ValidationError{Name: "safe_error_summary", err: fmt.Errorf(`ent: validator failed for field "GovernanceEvent.safe_error_summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "GovernanceEvent.occurred_at"`)}
	}
	return nil
}

func (_c *GovernanceEventCreate) sqlSave(ctx context.Context) (*GovernanceEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GovernanceEventCreate) createSpec() (*GovernanceEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &GovernanceEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(governanceevent.Table, sqlgraph.NewFieldSpec(governanceevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(governanceevent.FieldOperationID, field.TypeUUID, value)
		_node.OperationID = value
	}
	if value, ok := _c.mutation.EventSequence(); ok {
		_spec.SetField(governanceevent.FieldEventSequence, field.TypeInt, value)
		_node.EventSequence = value
	}
	if value, ok := _c.mutation.ActorKind(); ok {
		_spec.SetField(governanceevent.FieldActorKind, field.TypeEnum, value)
		_node.ActorKind = value
	}
	if value, ok := _c.mutation.DeploymentOperatorID(); ok {
		_spec.SetField(governanceevent.FieldDeploymentOperatorID, field.TypeString, value)
		_node.DeploymentOperatorID = &value
	}
	if value, ok := _c.mutation.TargetKind(); ok {
		_spec.SetField(governanceevent.FieldTargetKind, field.TypeString, value)
		_node.TargetKind = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(governanceevent.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(governanceevent.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(governanceevent.FieldResult, field.TypeEnum, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(governanceevent.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.BeforeSummary(); ok {
		_spec.SetField(governanceevent.FieldBeforeSummary, field.TypeJSON, value)
		_node.BeforeSummary = value
	}
	if value, ok := _c.mutation.AfterSummary(); ok {
		_spec.SetField(governanceevent.FieldAfterSummary, field.TypeJSON, value)
		_node.AfterSummary = value
	}
	if value, ok := _c.mutation.RecoveryNonceFingerprint(); ok {
		_spec.SetField(governanceevent.FieldRecoveryNonceFingerprint, field.TypeString, value)
		_node.RecoveryNonceFingerprint = &value
	}
	if value, ok := _c.mutation.GatewayRequestID(); ok {
		_spec.SetField(governanceevent.FieldGatewayRequestID, field.TypeString, value)
		_node.GatewayRequestID = &value
	}
	if value, ok := _c.mutation.SafeErrorSummary(); ok {
		_spec.SetField(governanceevent.FieldSafeErrorSummary, field.TypeString, value)
		_node.SafeErrorSummary = &value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(governanceevent.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if nodes := _c.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   governanceevent.ActorTable,
			Columns: []string{governanceevent.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActorUserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GovernanceEvent.Create().
//		SetOperationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GovernanceEventUpsert) {
//			SetOperationID(v+v).
//		}).
//		Exec(ctx)
func (_c *GovernanceEventCreate) OnConflict(opts ...sql.ConflictOption) *GovernanceEventUpsertOne {
	_c.conflict = opts
	return &GovernanceEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GovernanceEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GovernanceEventCreate) OnConflictColumns(columns ...string) *GovernanceEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GovernanceEventUpsertOne{
		create: _c,
	}
}

type (
	// GovernanceEventUpsertOne is the builder for "upsert"-ing
	//  one GovernanceEvent node.
	GovernanceEventUpsertOne struct {
		create *GovernanceEventCreate
	}

	// GovernanceEventUpsert is the "OnConflict" setter.
	GovernanceEventUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GovernanceEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(governanceevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GovernanceEventUpsertOne) UpdateNewValues() *GovernanceEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(governanceevent.FieldID)
		}
		if _, exists := u.create.mutation.OperationID(); exists {
			s.SetIgnore(governanceevent.FieldOperationID)
		}
		if _, exists := u.create.mutation.EventSequence(); exists {
			s.SetIgnore(governanceevent.FieldEventSequence)
		}
		if _, exists := u.create.mutation.ActorKind(); exists {
			s.SetIgnore(governanceevent.FieldActorKind)
		}
		if _, exists := u.create.mutation.ActorUserID(); exists {
			s.SetIgnore(governanceevent.FieldActorUserID)
		}
		if _, exists := u.create.mutation.DeploymentOperatorID(); exists {
			s.SetIgnore(governanceevent.FieldDeploymentOperatorID)
		}
		if _, exists := u.create.mutation.TargetKind(); exists {
			s.SetIgnore(governanceevent.FieldTargetKind)
		}
		if _, exists := u.create.mutation.TargetID(); exists {
			s.SetIgnore(governanceevent.FieldTargetID)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(governanceevent.FieldAction)
		}
		if _, exists := u.create.mutation.Result(); exists {
			s.SetIgnore(governanceevent.FieldResult)
		}
		if _, exists := u.create.mutation.Reason(); exists {
			s.SetIgnore(governanceevent.FieldReason)
		}
		if _, exists := u.create.mutation.BeforeSummary(); exists {
			s.SetIgnore(governanceevent.FieldBeforeSummary)
		}
		if _, exists := u.create.mutation.AfterSummary(); exists {
			s.SetIgnore(governanceevent.FieldAfterSummary)
		}
		if _, exists := u.create.mutation.RecoveryNonceFingerprint(); exists {
			s.SetIgnore(governanceevent.FieldRecoveryNonceFingerprint)
		}
		if _, exists := u.create.mutation.GatewayRequestID(); exists {
			s.SetIgnore(governanceevent.FieldGatewayRequestID)
		}
		if _, exists := u.create.mutation.SafeErrorSummary(); exists {
			s.SetIgnore(governanceevent.FieldSafeErrorSummary)
		}
		if _, exists := u.create.mutation.OccurredAt(); exists {
			s.SetIgnore(governanceevent.FieldOccurredAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GovernanceEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GovernanceEventUpsertOne) Ignore() *GovernanceEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GovernanceEventUpsertOne) DoNothing() *GovernanceEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GovernanceEventCreate.OnConflict
// documentation for more info.
func (u *GovernanceEventUpsertOne) Update(set func(*GovernanceEventUpsert)) *GovernanceEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GovernanceEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *GovernanceEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GovernanceEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GovernanceEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GovernanceEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GovernanceEventUpsertOne.ID is not supported by MySQL driver. Use GovernanceEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GovernanceEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GovernanceEventCreateBulk is the builder for creating many GovernanceEvent entities in bulk.
type GovernanceEventCreateBulk struct {
	config
	err      error
	builders []*GovernanceEventCreate
	conflict []sql.ConflictOption
}

// Save creates the GovernanceEvent entities in the database.
func (_c *GovernanceEventCreateBulk) Save(ctx context.Context) ([]*GovernanceEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GovernanceEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GovernanceEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GovernanceEventCreateBulk) SaveX(ctx context.Context) []*GovernanceEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GovernanceEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GovernanceEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GovernanceEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GovernanceEventUpsert) {
//			SetOperationID(v+v).
//		}).
//		Exec(ctx)
func (_c *GovernanceEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *GovernanceEventUpsertBulk {
	_c.conflict = opts
	return &GovernanceEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GovernanceEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GovernanceEventCreateBulk) OnConflictColumns(columns ...string) *GovernanceEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GovernanceEventUpsertBulk{
		create: _c,
	}
}

// GovernanceEventUpsertBulk is the builder for "upsert"-ing
// a bulk of GovernanceEvent nodes.
type GovernanceEventUpsertBulk struct {
	create *GovernanceEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GovernanceEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(governanceevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GovernanceEventUpsertBulk) UpdateNewValues() *GovernanceEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(governanceevent.FieldID)
			}
			if _, exists := b.mutation.OperationID(); exists {
				s.SetIgnore(governanceevent.FieldOperationID)
			}
			if _, exists := b.mutation.EventSequence(); exists {
				s.SetIgnore(governanceevent.FieldEventSequence)
			}
			if _, exists := b.mutation.ActorKind(); exists {
				s.SetIgnore(governanceevent.FieldActorKind)
			}
			if _, exists := b.mutation.ActorUserID(); exists {
				s.SetIgnore(governanceevent.FieldActorUserID)
			}
			if _, exists := b.mutation.DeploymentOperatorID(); exists {
				s.SetIgnore(governanceevent.FieldDeploymentOperatorID)
			}
			if _, exists := b.mutation.TargetKind(); exists {
				s.SetIgnore(governanceevent.FieldTargetKind)
			}
			if _, exists := b.mutation.TargetID(); exists {
				s.SetIgnore(governanceevent.FieldTargetID)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(governanceevent.FieldAction)
			}
			if _, exists := b.mutation.Result(); exists {
				s.SetIgnore(governanceevent.FieldResult)
			}
			if _, exists := b.mutation.Reason(); exists {
				s.SetIgnore(governanceevent.FieldReason)
			}
			if _, exists := b.mutation.BeforeSummary(); exists {
				s.SetIgnore(governanceevent.FieldBeforeSummary)
			}
			if _, exists := b.mutation.AfterSummary(); exists {
				s.SetIgnore(governanceevent.FieldAfterSummary)
			}
			if _, exists := b.mutation.RecoveryNonceFingerprint(); exists {
				s.SetIgnore(governanceevent.FieldRecoveryNonceFingerprint)
			}
			if _, exists := b.mutation.GatewayRequestID(); exists {
				s.SetIgnore(governanceevent.FieldGatewayRequestID)
			}
			if _, exists := b.mutation.SafeErrorSummary(); exists {
				s.SetIgnore(governanceevent.FieldSafeErrorSummary)
			}
			if _, exists := b.mutation.OccurredAt(); exists {
				s.SetIgnore(governanceevent.FieldOccurredAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GovernanceEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GovernanceEventUpsertBulk) Ignore() *GovernanceEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GovernanceEventUpsertBulk) DoNothing() *GovernanceEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GovernanceEventCreateBulk.OnConflict
// documentation for more info.
func (u *GovernanceEventUpsertBulk) Update(set func(*GovernanceEventUpsert)) *GovernanceEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GovernanceEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *GovernanceEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GovernanceEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GovernanceEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GovernanceEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
