// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/governanceevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// GovernanceEvent is the model entity for the GovernanceEvent schema.
type GovernanceEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OperationID holds the value of the "operation_id" field.
	OperationID uuid.UUID `json:"operation_id,omitempty"`
	// EventSequence holds the value of the "event_sequence" field.
	EventSequence int `json:"event_sequence,omitempty"`
	// ActorKind holds the value of the "actor_kind" field.
	ActorKind governanceevent.ActorKind `json:"actor_kind,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID *int64 `json:"actor_user_id,omitempty"`
	// DeploymentOperatorID holds the value of the "deployment_operator_id" field.
	DeploymentOperatorID *string `json:"deployment_operator_id,omitempty"`
	// TargetKind holds the value of the "target_kind" field.
	TargetKind string `json:"target_kind,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID string `json:"target_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Result holds the value of the "result" field.
	Result governanceevent.Result `json:"result,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// BeforeSummary holds the value of the "before_summary" field.
	BeforeSummary map[string]interface{} `json:"before_summary,omitempty"`
	// AfterSummary holds the value of the "after_summary" field.
	AfterSummary map[string]interface{} `json:"after_summary,omitempty"`
	// RecoveryNonceFingerprint holds the value of the "recovery_nonce_fingerprint" field.
	RecoveryNonceFingerprint *string `json:"recovery_nonce_fingerprint,omitempty"`
	// GatewayRequestID holds the value of the "gateway_request_id" field.
	GatewayRequestID *string `json:"gateway_request_id,omitempty"`
	// SafeErrorSummary holds the value of the "safe_error_summary" field.
	SafeErrorSummary *string `json:"safe_error_summary,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GovernanceEventQuery when eager-loading is set.
	Edges        GovernanceEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GovernanceEventEdges holds the relations/edges for other nodes in the graph.
type GovernanceEventEdges struct {
	// Actor holds the value of the actor edge.
	Actor *User `json:"actor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ActorOrErr returns the Actor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GovernanceEventEdges) ActorOrErr() (*User, error) {
	if e.Actor != nil {
		return e.Actor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "actor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GovernanceEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case governanceevent.FieldBeforeSummary, governanceevent.FieldAfterSummary:
			values[i] = new([]byte)
		case governanceevent.FieldEventSequence, governanceevent.FieldActorUserID:
			values[i] = new(sql.NullInt64)
		case governanceevent.FieldActorKind, governanceevent.FieldDeploymentOperatorID, governanceevent.FieldTargetKind, governanceevent.FieldTargetID, governanceevent.FieldAction, governanceevent.FieldResult, governanceevent.FieldReason, governanceevent.FieldRecoveryNonceFingerprint, governanceevent.FieldGatewayRequestID, governanceevent.FieldSafeErrorSummary:
			values[i] = new(sql.NullString)
		case governanceevent.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		case governanceevent.FieldID, governanceevent.FieldOperationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GovernanceEvent fields.
func (_m *GovernanceEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case governanceevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case governanceevent.FieldOperationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field operation_id", values[i])
			} else if value != nil {
				_m.OperationID = *value
			}
		case governanceevent.FieldEventSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field event_sequence", values[i])
			} else if value.Valid {
				_m.EventSequence = int(value.Int64)
			}
		case governanceevent.FieldActorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_kind", values[i])
			} else if value.Valid {
				_m.ActorKind = governanceevent.ActorKind(value.String)
			}
		case governanceevent.FieldActorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				_m.ActorUserID = new(int64)
				*_m.ActorUserID = value.Int64
			}
		case governanceevent.FieldDeploymentOperatorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deployment_operator_id", values[i])
			} else if value.Valid {
				_m.DeploymentOperatorID = new(string)
				*_m.DeploymentOperatorID = value.String
			}
		case governanceevent.FieldTargetKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_kind", values[i])
			} else if value.Valid {
				_m.TargetKind = value.String
			}
		case governanceevent.FieldTargetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = value.String
			}
		case governanceevent.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case governanceevent.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = governanceevent.Result(value.String)
			}
		case governanceevent.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case governanceevent.FieldBeforeSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field before_summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BeforeSummary); err != nil {
					return fmt.Errorf("unmarshal field before_summary: %w", err)
				}
			}
		case governanceevent.FieldAfterSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field after_summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AfterSummary); err != nil {
					return fmt.Errorf("unmarshal field after_summary: %w", err)
				}
			}
		case governanceevent.FieldRecoveryNonceFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recovery_nonce_fingerprint", values[i])
			} else if value.Valid {
				_m.RecoveryNonceFingerprint = new(string)
				*_m.RecoveryNonceFingerprint = value.String
			}
		case governanceevent.FieldGatewayRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_request_id", values[i])
			} else if value.Valid {
				_m.GatewayRequestID = new(string)
				*_m.GatewayRequestID = value.String
			}
		case governanceevent.FieldSafeErrorSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field safe_error_summary", values[i])
			} else if value.Valid {
				_m.SafeErrorSummary = new(string)
				*_m.SafeErrorSummary = value.String
			}
		case governanceevent.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GovernanceEvent.
// This includes values selected through modifiers, order, etc.
func (_m *GovernanceEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActor queries the "actor" edge of the GovernanceEvent entity.
func (_m *GovernanceEvent) QueryActor() *UserQuery {
	return NewGovernanceEventClient(_m.config).QueryActor(_m)
}

// Update returns a builder for updating this GovernanceEvent.
// Note that you need to call GovernanceEvent.Unwrap() before calling this method if this GovernanceEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GovernanceEvent) Update() *GovernanceEventUpdateOne {
	return NewGovernanceEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GovernanceEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GovernanceEvent) Unwrap() *GovernanceEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GovernanceEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GovernanceEvent) String() string {
	var builder strings.Builder
	builder.WriteString("GovernanceEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("operation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperationID))
	builder.WriteString(", ")
	builder.WriteString("event_sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventSequence))
	builder.WriteString(", ")
	builder.WriteString("actor_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActorKind))
	builder.WriteString(", ")
	if v := _m.ActorUserID; v != nil {
		builder.WriteString("actor_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeploymentOperatorID; v != nil {
		builder.WriteString("deployment_operator_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("target_kind=")
	builder.WriteString(_m.TargetKind)
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(_m.TargetID)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(fmt.Sprintf("%v", _m.Result))
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("before_summary=")
	builder.WriteString(fmt.Sprintf("%v", _m.BeforeSummary))
	builder.WriteString(", ")
	builder.WriteString("after_summary=")
	builder.WriteString(fmt.Sprintf("%v", _m.AfterSummary))
	builder.WriteString(", ")
	if v := _m.RecoveryNonceFingerprint; v != nil {
		builder.WriteString("recovery_nonce_fingerprint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GatewayRequestID; v != nil {
		builder.WriteString("gateway_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SafeErrorSummary; v != nil {
		builder.WriteString("safe_error_summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GovernanceEvents is a parsable slice of GovernanceEvent.
type GovernanceEvents []*GovernanceEvent
