// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogentry"
	"github.com/google/uuid"
)

// ModelCatalogEntry is the model entity for the ModelCatalogEntry schema.
type ModelCatalogEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Generation holds the value of the "generation" field.
	Generation int64 `json:"generation,omitempty"`
	// LogicalModel holds the value of the "logical_model" field.
	LogicalModel string `json:"logical_model,omitempty"`
	// ProviderModel holds the value of the "provider_model" field.
	ProviderModel string `json:"provider_model,omitempty"`
	// Tier holds the value of the "tier" field.
	Tier modelcatalogentry.Tier `json:"tier,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities []string `json:"capabilities,omitempty"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// ValidUntil holds the value of the "valid_until" field.
	ValidUntil *time.Time `json:"valid_until,omitempty"`
	// EmergencyDisabled holds the value of the "emergency_disabled" field.
	EmergencyDisabled bool `json:"emergency_disabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelCatalogEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelcatalogentry.FieldCapabilities:
			values[i] = new([]byte)
		case modelcatalogentry.FieldEmergencyDisabled:
			values[i] = new(sql.NullBool)
		case modelcatalogentry.FieldGeneration:
			values[i] = new(sql.NullInt64)
		case modelcatalogentry.FieldLogicalModel, modelcatalogentry.FieldProviderModel, modelcatalogentry.FieldTier:
			values[i] = new(sql.NullString)
		case modelcatalogentry.FieldValidFrom, modelcatalogentry.FieldValidUntil, modelcatalogentry.FieldCreatedAt, modelcatalogentry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case modelcatalogentry.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelCatalogEntry fields.
func (_m *ModelCatalogEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelcatalogentry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case modelcatalogentry.FieldGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field generation", values[i])
			} else if value.Valid {
				_m.Generation = value.Int64
			}
		case modelcatalogentry.FieldLogicalModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logical_model", values[i])
			} else if value.Valid {
				_m.LogicalModel = value.String
			}
		case modelcatalogentry.FieldProviderModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_model", values[i])
			} else if value.Valid {
				_m.ProviderModel = value.String
			}
		case modelcatalogentry.FieldTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				_m.Tier = modelcatalogentry.Tier(value.String)
			}
		case modelcatalogentry.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case modelcatalogentry.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case modelcatalogentry.FieldValidUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_until", values[i])
			} else if value.Valid {
				_m.ValidUntil = new(time.Time)
				*_m.ValidUntil = value.Time
			}
		case modelcatalogentry.FieldEmergencyDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field emergency_disabled", values[i])
			} else if value.Valid {
				_m.EmergencyDisabled = value.Bool
			}
		case modelcatalogentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelcatalogentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelCatalogEntry.
// This includes values selected through modifiers, order, etc.
func (_m *ModelCatalogEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelCatalogEntry.
// Note that you need to call ModelCatalogEntry.Unwrap() before calling this method if this ModelCatalogEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelCatalogEntry) Update() *ModelCatalogEntryUpdateOne {
	return NewModelCatalogEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelCatalogEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelCatalogEntry) Unwrap() *ModelCatalogEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelCatalogEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelCatalogEntry) String() string {
	var builder strings.Builder
	builder.WriteString("ModelCatalogEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Generation))
	builder.WriteString(", ")
	builder.WriteString("logical_model=")
	builder.WriteString(_m.LogicalModel)
	builder.WriteString(", ")
	builder.WriteString("provider_model=")
	builder.WriteString(_m.ProviderModel)
	builder.WriteString(", ")
	builder.WriteString("tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tier))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidUntil; v != nil {
		builder.WriteString("valid_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("emergency_disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmergencyDisabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ModelCatalogEntries is a parsable slice of ModelCatalogEntry.
type ModelCatalogEntries []*ModelCatalogEntry
