// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/routedecision"
	"github.com/google/uuid"
)

// RouteDecision is the model entity for the RouteDecision schema.
type RouteDecision struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GatewayRequestID holds the value of the "gateway_request_id" field.
	GatewayRequestID uuid.UUID `json:"gateway_request_id,omitempty"`
	// WorkSessionID holds the value of the "work_session_id" field.
	WorkSessionID uuid.UUID `json:"work_session_id,omitempty"`
	// EmployeeUserID holds the value of the "employee_user_id" field.
	EmployeeUserID int64 `json:"employee_user_id,omitempty"`
	// ProfileVersion holds the value of the "profile_version" field.
	ProfileVersion string `json:"profile_version,omitempty"`
	// ConfigVersion holds the value of the "config_version" field.
	ConfigVersion int64 `json:"config_version,omitempty"`
	// RequiredCapabilities holds the value of the "required_capabilities" field.
	RequiredCapabilities []string `json:"required_capabilities,omitempty"`
	// TaskComplexity holds the value of the "task_complexity" field.
	TaskComplexity routedecision.TaskComplexity `json:"task_complexity,omitempty"`
	// Certainty holds the value of the "certainty" field.
	Certainty routedecision.Certainty `json:"certainty,omitempty"`
	// Explanation holds the value of the "explanation" field.
	Explanation string `json:"explanation,omitempty"`
	// DecisionSource holds the value of the "decision_source" field.
	DecisionSource routedecision.DecisionSource `json:"decision_source,omitempty"`
	// RuleVersion holds the value of the "rule_version" field.
	RuleVersion string `json:"rule_version,omitempty"`
	// ClassifierRunID holds the value of the "classifier_run_id" field.
	ClassifierRunID *uuid.UUID `json:"classifier_run_id,omitempty"`
	// ClassifierVersion holds the value of the "classifier_version" field.
	ClassifierVersion *string `json:"classifier_version,omitempty"`
	// ClassifierStatus holds the value of the "classifier_status" field.
	ClassifierStatus routedecision.ClassifierStatus `json:"classifier_status,omitempty"`
	// ClassifierLatencyMs holds the value of the "classifier_latency_ms" field.
	ClassifierLatencyMs int64 `json:"classifier_latency_ms,omitempty"`
	// RequestedTier holds the value of the "requested_tier" field.
	RequestedTier routedecision.RequestedTier `json:"requested_tier,omitempty"`
	// EffectiveTier holds the value of the "effective_tier" field.
	EffectiveTier routedecision.EffectiveTier `json:"effective_tier,omitempty"`
	// CandidatePool holds the value of the "candidate_pool" field.
	CandidatePool []map[string]interface{} `json:"candidate_pool,omitempty"`
	// ActualLogicalModel holds the value of the "actual_logical_model" field.
	ActualLogicalModel *string `json:"actual_logical_model,omitempty"`
	// ActualProviderModel holds the value of the "actual_provider_model" field.
	ActualProviderModel *string `json:"actual_provider_model,omitempty"`
	// ChangeReason holds the value of the "change_reason" field.
	ChangeReason string `json:"change_reason,omitempty"`
	// TechnicalRetryCount holds the value of the "technical_retry_count" field.
	TechnicalRetryCount int16 `json:"technical_retry_count,omitempty"`
	// TechnicalRetryReason holds the value of the "technical_retry_reason" field.
	TechnicalRetryReason *string `json:"technical_retry_reason,omitempty"`
	// DecisionResult holds the value of the "decision_result" field.
	DecisionResult routedecision.DecisionResult `json:"decision_result,omitempty"`
	// RoutingLatencyMs holds the value of the "routing_latency_ms" field.
	RoutingLatencyMs int64 `json:"routing_latency_ms,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RouteDecision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case routedecision.FieldClassifierRunID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case routedecision.FieldRequiredCapabilities, routedecision.FieldCandidatePool:
			values[i] = new([]byte)
		case routedecision.FieldEmployeeUserID, routedecision.FieldConfigVersion, routedecision.FieldClassifierLatencyMs, routedecision.FieldTechnicalRetryCount, routedecision.FieldRoutingLatencyMs:
			values[i] = new(sql.NullInt64)
		case routedecision.FieldProfileVersion, routedecision.FieldTaskComplexity, routedecision.FieldCertainty, routedecision.FieldExplanation, routedecision.FieldDecisionSource, routedecision.FieldRuleVersion, routedecision.FieldClassifierVersion, routedecision.FieldClassifierStatus, routedecision.FieldRequestedTier, routedecision.FieldEffectiveTier, routedecision.FieldActualLogicalModel, routedecision.FieldActualProviderModel, routedecision.FieldChangeReason, routedecision.FieldTechnicalRetryReason, routedecision.FieldDecisionResult:
			values[i] = new(sql.NullString)
		case routedecision.FieldCreatedAt, routedecision.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case routedecision.FieldID, routedecision.FieldGatewayRequestID, routedecision.FieldWorkSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RouteDecision fields.
func (_m *RouteDecision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case routedecision.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case routedecision.FieldGatewayRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_request_id", values[i])
			} else if value != nil {
				_m.GatewayRequestID = *value
			}
		case routedecision.FieldWorkSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field work_session_id", values[i])
			} else if value != nil {
				_m.WorkSessionID = *value
			}
		case routedecision.FieldEmployeeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field employee_user_id", values[i])
			} else if value.Valid {
				_m.EmployeeUserID = value.Int64
			}
		case routedecision.FieldProfileVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_version", values[i])
			} else if value.Valid {
				_m.ProfileVersion = value.String
			}
		case routedecision.FieldConfigVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field config_version", values[i])
			} else if value.Valid {
				_m.ConfigVersion = value.Int64
			}
		case routedecision.FieldRequiredCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field required_capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequiredCapabilities); err != nil {
					return fmt.Errorf("unmarshal field required_capabilities: %w", err)
				}
			}
		case routedecision.FieldTaskComplexity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_complexity", values[i])
			} else if value.Valid {
				_m.TaskComplexity = routedecision.TaskComplexity(value.String)
			}
		case routedecision.FieldCertainty:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field certainty", values[i])
			} else if value.Valid {
				_m.Certainty = routedecision.Certainty(value.String)
			}
		case routedecision.FieldExplanation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field explanation", values[i])
			} else if value.Valid {
				_m.Explanation = value.String
			}
		case routedecision.FieldDecisionSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field decision_source", values[i])
			} else if value.Valid {
				_m.DecisionSource = routedecision.DecisionSource(value.String)
			}
		case routedecision.FieldRuleVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_version", values[i])
			} else if value.Valid {
				_m.RuleVersion = value.String
			}
		case routedecision.FieldClassifierRunID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_run_id", values[i])
			} else if value.Valid {
				_m.ClassifierRunID = new(uuid.UUID)
				*_m.ClassifierRunID = *value.S.(*uuid.UUID)
			}
		case routedecision.FieldClassifierVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_version", values[i])
			} else if value.Valid {
				_m.ClassifierVersion = new(string)
				*_m.ClassifierVersion = value.String
			}
		case routedecision.FieldClassifierStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_status", values[i])
			} else if value.Valid {
				_m.ClassifierStatus = routedecision.ClassifierStatus(value.String)
			}
		case routedecision.FieldClassifierLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_latency_ms", values[i])
			} else if value.Valid {
				_m.ClassifierLatencyMs = value.Int64
			}
		case routedecision.FieldRequestedTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_tier", values[i])
			} else if value.Valid {
				_m.RequestedTier = routedecision.RequestedTier(value.String)
			}
		case routedecision.FieldEffectiveTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field effective_tier", values[i])
			} else if value.Valid {
				_m.EffectiveTier = routedecision.EffectiveTier(value.String)
			}
		case routedecision.FieldCandidatePool:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field candidate_pool", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CandidatePool); err != nil {
					return fmt.Errorf("unmarshal field candidate_pool: %w", err)
				}
			}
		case routedecision.FieldActualLogicalModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actual_logical_model", values[i])
			} else if value.Valid {
				_m.ActualLogicalModel = new(string)
				*_m.ActualLogicalModel = value.String
			}
		case routedecision.FieldActualProviderModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actual_provider_model", values[i])
			} else if value.Valid {
				_m.ActualProviderModel = new(string)
				*_m.ActualProviderModel = value.String
			}
		case routedecision.FieldChangeReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_reason", values[i])
			} else if value.Valid {
				_m.ChangeReason = value.String
			}
		case routedecision.FieldTechnicalRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field technical_retry_count", values[i])
			} else if value.Valid {
				_m.TechnicalRetryCount = int16(value.Int64)
			}
		case routedecision.FieldTechnicalRetryReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field technical_retry_reason", values[i])
			} else if value.Valid {
				_m.TechnicalRetryReason = new(string)
				*_m.TechnicalRetryReason = value.String
			}
		case routedecision.FieldDecisionResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field decision_result", values[i])
			} else if value.Valid {
				_m.DecisionResult = routedecision.DecisionResult(value.String)
			}
		case routedecision.FieldRoutingLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field routing_latency_ms", values[i])
			} else if value.Valid {
				_m.RoutingLatencyMs = value.Int64
			}
		case routedecision.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case routedecision.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RouteDecision.
// This includes values selected through modifiers, order, etc.
func (_m *RouteDecision) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RouteDecision.
// Note that you need to call RouteDecision.Unwrap() before calling this method if this RouteDecision
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RouteDecision) Update() *RouteDecisionUpdateOne {
	return NewRouteDecisionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RouteDecision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RouteDecision) Unwrap() *RouteDecision {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RouteDecision is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RouteDecision) String() string {
	var builder strings.Builder
	builder.WriteString("RouteDecision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("gateway_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GatewayRequestID))
	builder.WriteString(", ")
	builder.WriteString("work_session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkSessionID))
	builder.WriteString(", ")
	builder.WriteString("employee_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmployeeUserID))
	builder.WriteString(", ")
	builder.WriteString("profile_version=")
	builder.WriteString(_m.ProfileVersion)
	builder.WriteString(", ")
	builder.WriteString("config_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigVersion))
	builder.WriteString(", ")
	builder.WriteString("required_capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiredCapabilities))
	builder.WriteString(", ")
	builder.WriteString("task_complexity=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskComplexity))
	builder.WriteString(", ")
	builder.WriteString("certainty=")
	builder.WriteString(fmt.Sprintf("%v", _m.Certainty))
	builder.WriteString(", ")
	builder.WriteString("explanation=")
	builder.WriteString(_m.Explanation)
	builder.WriteString(", ")
	builder.WriteString("decision_source=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecisionSource))
	builder.WriteString(", ")
	builder.WriteString("rule_version=")
	builder.WriteString(_m.RuleVersion)
	builder.WriteString(", ")
	if v := _m.ClassifierRunID; v != nil {
		builder.WriteString("classifier_run_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ClassifierVersion; v != nil {
		builder.WriteString("classifier_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("classifier_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClassifierStatus))
	builder.WriteString(", ")
	builder.WriteString("classifier_latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClassifierLatencyMs))
	builder.WriteString(", ")
	builder.WriteString("requested_tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedTier))
	builder.WriteString(", ")
	builder.WriteString("effective_tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.EffectiveTier))
	builder.WriteString(", ")
	builder.WriteString("candidate_pool=")
	builder.WriteString(fmt.Sprintf("%v", _m.CandidatePool))
	builder.WriteString(", ")
	if v := _m.ActualLogicalModel; v != nil {
		builder.WriteString("actual_logical_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ActualProviderModel; v != nil {
		builder.WriteString("actual_provider_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("change_reason=")
	builder.WriteString(_m.ChangeReason)
	builder.WriteString(", ")
	builder.WriteString("technical_retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TechnicalRetryCount))
	builder.WriteString(", ")
	if v := _m.TechnicalRetryReason; v != nil {
		builder.WriteString("technical_retry_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("decision_result=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecisionResult))
	builder.WriteString(", ")
	builder.WriteString("routing_latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoutingLatencyMs))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RouteDecisions is a parsable slice of RouteDecision.
type RouteDecisions []*RouteDecision
