// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/superadminseat"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SuperAdminSeatCreate is the builder for creating a SuperAdminSeat entity.
type SuperAdminSeatCreate struct {
	config
	mutation *SuperAdminSeatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *SuperAdminSeatCreate) SetUserID(v int64) *SuperAdminSeatCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *SuperAdminSeatCreate) SetVersion(v int64) *SuperAdminSeatCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *SuperAdminSeatCreate) SetNillableVersion(v *int64) *SuperAdminSeatCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SuperAdminSeatCreate) SetUpdatedAt(v time.Time) *SuperAdminSeatCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SuperAdminSeatCreate) SetID(v int16) *SuperAdminSeatCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SuperAdminSeatCreate) SetUser(v *User) *SuperAdminSeatCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SuperAdminSeatMutation object of the builder.
func (_c *SuperAdminSeatCreate) Mutation() *SuperAdminSeatMutation {
	return _c.mutation
}

// Save creates the SuperAdminSeat in the database.
func (_c *SuperAdminSeatCreate) Save(ctx context.Context) (*SuperAdminSeat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SuperAdminSeatCreate) SaveX(ctx context.Context) *SuperAdminSeat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SuperAdminSeatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SuperAdminSeatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SuperAdminSeatCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := superadminseat.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SuperAdminSeatCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SuperAdminSeat.user_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SuperAdminSeat.version"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SuperAdminSeat.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SuperAdminSeat.user"`)}
	}
	return nil
}

func (_c *SuperAdminSeatCreate) sqlSave(ctx context.Context) (*SuperAdminSeat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int16(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SuperAdminSeatCreate) createSpec() (*SuperAdminSeat, *sqlgraph.CreateSpec) {
	var (
		_node = &SuperAdminSeat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(superadminseat.Table, sqlgraph.NewFieldSpec(superadminseat.FieldID, field.TypeInt16))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(superadminseat.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(superadminseat.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   superadminseat.UserTable,
			Columns: []string{superadminseat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SuperAdminSeat.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SuperAdminSeatUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SuperAdminSeatCreate) OnConflict(opts ...sql.ConflictOption) *SuperAdminSeatUpsertOne {
	_c.conflict = opts
	return &SuperAdminSeatUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SuperAdminSeat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SuperAdminSeatCreate) OnConflictColumns(columns ...string) *SuperAdminSeatUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SuperAdminSeatUpsertOne{
		create: _c,
	}
}

type (
	// SuperAdminSeatUpsertOne is the builder for "upsert"-ing
	//  one SuperAdminSeat node.
	SuperAdminSeatUpsertOne struct {
		create *SuperAdminSeatCreate
	}

	// SuperAdminSeatUpsert is the "OnConflict" setter.
	SuperAdminSeatUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *SuperAdminSeatUpsert) SetUserID(v int64) *SuperAdminSeatUpsert {
	u.Set(superadminseat.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SuperAdminSeatUpsert) UpdateUserID() *SuperAdminSeatUpsert {
	u.SetExcluded(superadminseat.FieldUserID)
	return u
}

// SetVersion sets the "version" field.
func (u *SuperAdminSeatUpsert) SetVersion(v int64) *SuperAdminSeatUpsert {
	u.Set(superadminseat.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SuperAdminSeatUpsert) UpdateVersion() *SuperAdminSeatUpsert {
	u.SetExcluded(superadminseat.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *SuperAdminSeatUpsert) AddVersion(v int64) *SuperAdminSeatUpsert {
	u.Add(superadminseat.FieldVersion, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SuperAdminSeatUpsert) SetUpdatedAt(v time.Time) *SuperAdminSeatUpsert {
	u.Set(superadminseat.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SuperAdminSeatUpsert) UpdateUpdatedAt() *SuperAdminSeatUpsert {
	u.SetExcluded(superadminseat.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SuperAdminSeat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(superadminseat.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SuperAdminSeatUpsertOne) UpdateNewValues() *SuperAdminSeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(superadminseat.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SuperAdminSeat.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SuperAdminSeatUpsertOne) Ignore() *SuperAdminSeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SuperAdminSeatUpsertOne) DoNothing() *SuperAdminSeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SuperAdminSeatCreate.OnConflict
// documentation for more info.
func (u *SuperAdminSeatUpsertOne) Update(set func(*SuperAdminSeatUpsert)) *SuperAdminSeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SuperAdminSeatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SuperAdminSeatUpsertOne) SetUserID(v int64) *SuperAdminSeatUpsertOne {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SuperAdminSeatUpsertOne) UpdateUserID() *SuperAdminSeatUpsertOne {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.UpdateUserID()
	})
}

// SetVersion sets the "version" field.
func (u *SuperAdminSeatUpsertOne) SetVersion(v int64) *SuperAdminSeatUpsertOne {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SuperAdminSeatUpsertOne) AddVersion(v int64) *SuperAdminSeatUpsertOne {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SuperAdminSeatUpsertOne) UpdateVersion() *SuperAdminSeatUpsertOne {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SuperAdminSeatUpsertOne) SetUpdatedAt(v time.Time) *SuperAdminSeatUpsertOne {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SuperAdminSeatUpsertOne) UpdateUpdatedAt() *SuperAdminSeatUpsertOne {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SuperAdminSeatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SuperAdminSeatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SuperAdminSeatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SuperAdminSeatUpsertOne) ID(ctx context.Context) (id int16, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SuperAdminSeatUpsertOne) IDX(ctx context.Context) int16 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SuperAdminSeatCreateBulk is the builder for creating many SuperAdminSeat entities in bulk.
type SuperAdminSeatCreateBulk struct {
	config
	err      error
	builders []*SuperAdminSeatCreate
	conflict []sql.ConflictOption
}

// Save creates the SuperAdminSeat entities in the database.
func (_c *SuperAdminSeatCreateBulk) Save(ctx context.Context) ([]*SuperAdminSeat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SuperAdminSeat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SuperAdminSeatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int16(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SuperAdminSeatCreateBulk) SaveX(ctx context.Context) []*SuperAdminSeat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SuperAdminSeatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SuperAdminSeatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SuperAdminSeat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SuperAdminSeatUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SuperAdminSeatCreateBulk) OnConflict(opts ...sql.ConflictOption) *SuperAdminSeatUpsertBulk {
	_c.conflict = opts
	return &SuperAdminSeatUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SuperAdminSeat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SuperAdminSeatCreateBulk) OnConflictColumns(columns ...string) *SuperAdminSeatUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SuperAdminSeatUpsertBulk{
		create: _c,
	}
}

// SuperAdminSeatUpsertBulk is the builder for "upsert"-ing
// a bulk of SuperAdminSeat nodes.
type SuperAdminSeatUpsertBulk struct {
	create *SuperAdminSeatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SuperAdminSeat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(superadminseat.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SuperAdminSeatUpsertBulk) UpdateNewValues() *SuperAdminSeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(superadminseat.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SuperAdminSeat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SuperAdminSeatUpsertBulk) Ignore() *SuperAdminSeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SuperAdminSeatUpsertBulk) DoNothing() *SuperAdminSeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SuperAdminSeatCreateBulk.OnConflict
// documentation for more info.
func (u *SuperAdminSeatUpsertBulk) Update(set func(*SuperAdminSeatUpsert)) *SuperAdminSeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SuperAdminSeatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SuperAdminSeatUpsertBulk) SetUserID(v int64) *SuperAdminSeatUpsertBulk {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SuperAdminSeatUpsertBulk) UpdateUserID() *SuperAdminSeatUpsertBulk {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.UpdateUserID()
	})
}

// SetVersion sets the "version" field.
func (u *SuperAdminSeatUpsertBulk) SetVersion(v int64) *SuperAdminSeatUpsertBulk {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SuperAdminSeatUpsertBulk) AddVersion(v int64) *SuperAdminSeatUpsertBulk {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SuperAdminSeatUpsertBulk) UpdateVersion() *SuperAdminSeatUpsertBulk {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SuperAdminSeatUpsertBulk) SetUpdatedAt(v time.Time) *SuperAdminSeatUpsertBulk {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SuperAdminSeatUpsertBulk) UpdateUpdatedAt() *SuperAdminSeatUpsertBulk {
	return u.Update(func(s *SuperAdminSeatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SuperAdminSeatUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SuperAdminSeatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SuperAdminSeatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SuperAdminSeatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
