// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/worksession"
	"github.com/google/uuid"
)

// WorkSessionUpdate is the builder for updating WorkSession entities.
type WorkSessionUpdate struct {
	config
	hooks    []Hook
	mutation *WorkSessionMutation
}

// Where appends a list predicates to the WorkSessionUpdate builder.
func (_u *WorkSessionUpdate) Where(ps ...predicate.WorkSession) *WorkSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuotaGraceEligible sets the "quota_grace_eligible" field.
func (_u *WorkSessionUpdate) SetQuotaGraceEligible(v bool) *WorkSessionUpdate {
	_u.mutation.SetQuotaGraceEligible(v)
	return _u
}

// SetNillableQuotaGraceEligible sets the "quota_grace_eligible" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableQuotaGraceEligible(v *bool) *WorkSessionUpdate {
	if v != nil {
		_u.SetQuotaGraceEligible(*v)
	}
	return _u
}

// SetSelectedLogicalModel sets the "selected_logical_model" field.
func (_u *WorkSessionUpdate) SetSelectedLogicalModel(v string) *WorkSessionUpdate {
	_u.mutation.SetSelectedLogicalModel(v)
	return _u
}

// SetNillableSelectedLogicalModel sets the "selected_logical_model" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableSelectedLogicalModel(v *string) *WorkSessionUpdate {
	if v != nil {
		_u.SetSelectedLogicalModel(*v)
	}
	return _u
}

// ClearSelectedLogicalModel clears the value of the "selected_logical_model" field.
func (_u *WorkSessionUpdate) ClearSelectedLogicalModel() *WorkSessionUpdate {
	_u.mutation.ClearSelectedLogicalModel()
	return _u
}

// SetSelectedTier sets the "selected_tier" field.
func (_u *WorkSessionUpdate) SetSelectedTier(v worksession.SelectedTier) *WorkSessionUpdate {
	_u.mutation.SetSelectedTier(v)
	return _u
}

// SetNillableSelectedTier sets the "selected_tier" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableSelectedTier(v *worksession.SelectedTier) *WorkSessionUpdate {
	if v != nil {
		_u.SetSelectedTier(*v)
	}
	return _u
}

// ClearSelectedTier clears the value of the "selected_tier" field.
func (_u *WorkSessionUpdate) ClearSelectedTier() *WorkSessionUpdate {
	_u.mutation.ClearSelectedTier()
	return _u
}

// SetSelectedComplexity sets the "selected_complexity" field.
func (_u *WorkSessionUpdate) SetSelectedComplexity(v worksession.SelectedComplexity) *WorkSessionUpdate {
	_u.mutation.SetSelectedComplexity(v)
	return _u
}

// SetNillableSelectedComplexity sets the "selected_complexity" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableSelectedComplexity(v *worksession.SelectedComplexity) *WorkSessionUpdate {
	if v != nil {
		_u.SetSelectedComplexity(*v)
	}
	return _u
}

// ClearSelectedComplexity clears the value of the "selected_complexity" field.
func (_u *WorkSessionUpdate) ClearSelectedComplexity() *WorkSessionUpdate {
	_u.mutation.ClearSelectedComplexity()
	return _u
}

// SetRequiredCapabilities sets the "required_capabilities" field.
func (_u *WorkSessionUpdate) SetRequiredCapabilities(v []string) *WorkSessionUpdate {
	_u.mutation.SetRequiredCapabilities(v)
	return _u
}

// AppendRequiredCapabilities appends value to the "required_capabilities" field.
func (_u *WorkSessionUpdate) AppendRequiredCapabilities(v []string) *WorkSessionUpdate {
	_u.mutation.AppendRequiredCapabilities(v)
	return _u
}

// SetRoutingVersion sets the "routing_version" field.
func (_u *WorkSessionUpdate) SetRoutingVersion(v int64) *WorkSessionUpdate {
	_u.mutation.ResetRoutingVersion()
	_u.mutation.SetRoutingVersion(v)
	return _u
}

// SetNillableRoutingVersion sets the "routing_version" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableRoutingVersion(v *int64) *WorkSessionUpdate {
	if v != nil {
		_u.SetRoutingVersion(*v)
	}
	return _u
}

// AddRoutingVersion adds value to the "routing_version" field.
func (_u *WorkSessionUpdate) AddRoutingVersion(v int64) *WorkSessionUpdate {
	_u.mutation.AddRoutingVersion(v)
	return _u
}

// SetLastGatewayRequestID sets the "last_gateway_request_id" field.
func (_u *WorkSessionUpdate) SetLastGatewayRequestID(v uuid.UUID) *WorkSessionUpdate {
	_u.mutation.SetLastGatewayRequestID(v)
	return _u
}

// SetNillableLastGatewayRequestID sets the "last_gateway_request_id" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableLastGatewayRequestID(v *uuid.UUID) *WorkSessionUpdate {
	if v != nil {
		_u.SetLastGatewayRequestID(*v)
	}
	return _u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_u *WorkSessionUpdate) SetLastActivityAt(v time.Time) *WorkSessionUpdate {
	_u.mutation.SetLastActivityAt(v)
	return _u
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableLastActivityAt(v *time.Time) *WorkSessionUpdate {
	if v != nil {
		_u.SetLastActivityAt(*v)
	}
	return _u
}

// Mutation returns the WorkSessionMutation object of the builder.
func (_u *WorkSessionUpdate) Mutation() *WorkSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkSessionUpdate) check() error {
	if v, ok := _u.mutation.SelectedLogicalModel(); ok {
		if err := worksession.SelectedLogicalModelValidator(v); err != nil {
			return &ValidationError{Name: "selected_logical_model", err: fmt.Errorf(`ent: validator failed for field "WorkSession.selected_logical_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SelectedTier(); ok {
		if err := worksession.SelectedTierValidator(v); err != nil {
			return &ValidationError{Name: "selected_tier", err: fmt.Errorf(`ent: validator failed for field "WorkSession.selected_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SelectedComplexity(); ok {
		if err := worksession.SelectedComplexityValidator(v); err != nil {
			return &ValidationError{Name: "selected_complexity", err: fmt.Errorf(`ent: validator failed for field "WorkSession.selected_complexity": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(worksession.Table, worksession.Columns, sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SessionKeyHmacCleared() {
		_spec.ClearField(worksession.FieldSessionKeyHmac, field.TypeBytes)
	}
	if _u.mutation.HmacKeyVersionCleared() {
		_spec.ClearField(worksession.FieldHmacKeyVersion, field.TypeString)
	}
	if value, ok := _u.mutation.QuotaGraceEligible(); ok {
		_spec.SetField(worksession.FieldQuotaGraceEligible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SelectedLogicalModel(); ok {
		_spec.SetField(worksession.FieldSelectedLogicalModel, field.TypeString, value)
	}
	if _u.mutation.SelectedLogicalModelCleared() {
		_spec.ClearField(worksession.FieldSelectedLogicalModel, field.TypeString)
	}
	if value, ok := _u.mutation.SelectedTier(); ok {
		_spec.SetField(worksession.FieldSelectedTier, field.TypeEnum, value)
	}
	if _u.mutation.SelectedTierCleared() {
		_spec.ClearField(worksession.FieldSelectedTier, field.TypeEnum)
	}
	if value, ok := _u.mutation.SelectedComplexity(); ok {
		_spec.SetField(worksession.FieldSelectedComplexity, field.TypeEnum, value)
	}
	if _u.mutation.SelectedComplexityCleared() {
		_spec.ClearField(worksession.FieldSelectedComplexity, field.TypeEnum)
	}
	if value, ok := _u.mutation.RequiredCapabilities(); ok {
		_spec.SetField(worksession.FieldRequiredCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequiredCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, worksession.FieldRequiredCapabilities, value)
		})
	}
	if value, ok := _u.mutation.RoutingVersion(); ok {
		_spec.SetField(worksession.FieldRoutingVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRoutingVersion(); ok {
		_spec.AddField(worksession.FieldRoutingVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastGatewayRequestID(); ok {
		_spec.SetField(worksession.FieldLastGatewayRequestID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.LastActivityAt(); ok {
		_spec.SetField(worksession.FieldLastActivityAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worksession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkSessionUpdateOne is the builder for updating a single WorkSession entity.
type WorkSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkSessionMutation
}

// SetQuotaGraceEligible sets the "quota_grace_eligible" field.
func (_u *WorkSessionUpdateOne) SetQuotaGraceEligible(v bool) *WorkSessionUpdateOne {
	_u.mutation.SetQuotaGraceEligible(v)
	return _u
}

// SetNillableQuotaGraceEligible sets the "quota_grace_eligible" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableQuotaGraceEligible(v *bool) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetQuotaGraceEligible(*v)
	}
	return _u
}

// SetSelectedLogicalModel sets the "selected_logical_model" field.
func (_u *WorkSessionUpdateOne) SetSelectedLogicalModel(v string) *WorkSessionUpdateOne {
	_u.mutation.SetSelectedLogicalModel(v)
	return _u
}

// SetNillableSelectedLogicalModel sets the "selected_logical_model" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableSelectedLogicalModel(v *string) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetSelectedLogicalModel(*v)
	}
	return _u
}

// ClearSelectedLogicalModel clears the value of the "selected_logical_model" field.
func (_u *WorkSessionUpdateOne) ClearSelectedLogicalModel() *WorkSessionUpdateOne {
	_u.mutation.ClearSelectedLogicalModel()
	return _u
}

// SetSelectedTier sets the "selected_tier" field.
func (_u *WorkSessionUpdateOne) SetSelectedTier(v worksession.SelectedTier) *WorkSessionUpdateOne {
	_u.mutation.SetSelectedTier(v)
	return _u
}

// SetNillableSelectedTier sets the "selected_tier" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableSelectedTier(v *worksession.SelectedTier) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetSelectedTier(*v)
	}
	return _u
}

// ClearSelectedTier clears the value of the "selected_tier" field.
func (_u *WorkSessionUpdateOne) ClearSelectedTier() *WorkSessionUpdateOne {
	_u.mutation.ClearSelectedTier()
	return _u
}

// SetSelectedComplexity sets the "selected_complexity" field.
func (_u *WorkSessionUpdateOne) SetSelectedComplexity(v worksession.SelectedComplexity) *WorkSessionUpdateOne {
	_u.mutation.SetSelectedComplexity(v)
	return _u
}

// SetNillableSelectedComplexity sets the "selected_complexity" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableSelectedComplexity(v *worksession.SelectedComplexity) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetSelectedComplexity(*v)
	}
	return _u
}

// ClearSelectedComplexity clears the value of the "selected_complexity" field.
func (_u *WorkSessionUpdateOne) ClearSelectedComplexity() *WorkSessionUpdateOne {
	_u.mutation.ClearSelectedComplexity()
	return _u
}

// SetRequiredCapabilities sets the "required_capabilities" field.
func (_u *WorkSessionUpdateOne) SetRequiredCapabilities(v []string) *WorkSessionUpdateOne {
	_u.mutation.SetRequiredCapabilities(v)
	return _u
}

// AppendRequiredCapabilities appends value to the "required_capabilities" field.
func (_u *WorkSessionUpdateOne) AppendRequiredCapabilities(v []string) *WorkSessionUpdateOne {
	_u.mutation.AppendRequiredCapabilities(v)
	return _u
}

// SetRoutingVersion sets the "routing_version" field.
func (_u *WorkSessionUpdateOne) SetRoutingVersion(v int64) *WorkSessionUpdateOne {
	_u.mutation.ResetRoutingVersion()
	_u.mutation.SetRoutingVersion(v)
	return _u
}

// SetNillableRoutingVersion sets the "routing_version" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableRoutingVersion(v *int64) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetRoutingVersion(*v)
	}
	return _u
}

// AddRoutingVersion adds value to the "routing_version" field.
func (_u *WorkSessionUpdateOne) AddRoutingVersion(v int64) *WorkSessionUpdateOne {
	_u.mutation.AddRoutingVersion(v)
	return _u
}

// SetLastGatewayRequestID sets the "last_gateway_request_id" field.
func (_u *WorkSessionUpdateOne) SetLastGatewayRequestID(v uuid.UUID) *WorkSessionUpdateOne {
	_u.mutation.SetLastGatewayRequestID(v)
	return _u
}

// SetNillableLastGatewayRequestID sets the "last_gateway_request_id" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableLastGatewayRequestID(v *uuid.UUID) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetLastGatewayRequestID(*v)
	}
	return _u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_u *WorkSessionUpdateOne) SetLastActivityAt(v time.Time) *WorkSessionUpdateOne {
	_u.mutation.SetLastActivityAt(v)
	return _u
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableLastActivityAt(v *time.Time) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetLastActivityAt(*v)
	}
	return _u
}

// Mutation returns the WorkSessionMutation object of the builder.
func (_u *WorkSessionUpdateOne) Mutation() *WorkSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkSessionUpdate builder.
func (_u *WorkSessionUpdateOne) Where(ps ...predicate.WorkSession) *WorkSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkSessionUpdateOne) Select(field string, fields ...string) *WorkSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkSession entity.
func (_u *WorkSessionUpdateOne) Save(ctx context.Context) (*WorkSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkSessionUpdateOne) SaveX(ctx context.Context) *WorkSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkSessionUpdateOne) check() error {
	if v, ok := _u.mutation.SelectedLogicalModel(); ok {
		if err := worksession.SelectedLogicalModelValidator(v); err != nil {
			return &ValidationError{Name: "selected_logical_model", err: fmt.Errorf(`ent: validator failed for field "WorkSession.selected_logical_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SelectedTier(); ok {
		if err := worksession.SelectedTierValidator(v); err != nil {
			return &ValidationError{Name: "selected_tier", err: fmt.Errorf(`ent: validator failed for field "WorkSession.selected_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SelectedComplexity(); ok {
		if err := worksession.SelectedComplexityValidator(v); err != nil {
			return &ValidationError{Name: "selected_complexity", err: fmt.Errorf(`ent: validator failed for field "WorkSession.selected_complexity": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkSessionUpdateOne) sqlSave(ctx context.Context) (_node *WorkSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(worksession.Table, worksession.Columns, sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, worksession.FieldID)
		for _, f := range fields {
			if !worksession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != worksession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SessionKeyHmacCleared() {
		_spec.ClearField(worksession.FieldSessionKeyHmac, field.TypeBytes)
	}
	if _u.mutation.HmacKeyVersionCleared() {
		_spec.ClearField(worksession.FieldHmacKeyVersion, field.TypeString)
	}
	if value, ok := _u.mutation.QuotaGraceEligible(); ok {
		_spec.SetField(worksession.FieldQuotaGraceEligible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SelectedLogicalModel(); ok {
		_spec.SetField(worksession.FieldSelectedLogicalModel, field.TypeString, value)
	}
	if _u.mutation.SelectedLogicalModelCleared() {
		_spec.ClearField(worksession.FieldSelectedLogicalModel, field.TypeString)
	}
	if value, ok := _u.mutation.SelectedTier(); ok {
		_spec.SetField(worksession.FieldSelectedTier, field.TypeEnum, value)
	}
	if _u.mutation.SelectedTierCleared() {
		_spec.ClearField(worksession.FieldSelectedTier, field.TypeEnum)
	}
	if value, ok := _u.mutation.SelectedComplexity(); ok {
		_spec.SetField(worksession.FieldSelectedComplexity, field.TypeEnum, value)
	}
	if _u.mutation.SelectedComplexityCleared() {
		_spec.ClearField(worksession.FieldSelectedComplexity, field.TypeEnum)
	}
	if value, ok := _u.mutation.RequiredCapabilities(); ok {
		_spec.SetField(worksession.FieldRequiredCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequiredCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, worksession.FieldRequiredCapabilities, value)
		})
	}
	if value, ok := _u.mutation.RoutingVersion(); ok {
		_spec.SetField(worksession.FieldRoutingVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRoutingVersion(); ok {
		_spec.AddField(worksession.FieldRoutingVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastGatewayRequestID(); ok {
		_spec.SetField(worksession.FieldLastGatewayRequestID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.LastActivityAt(); ok {
		_spec.SetField(worksession.FieldLastActivityAt, field.TypeTime, value)
	}
	_node = &WorkSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worksession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
