// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/worksession"
	"github.com/google/uuid"
)

// WorkSession is the model entity for the WorkSession schema.
type WorkSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// EmployeeUserID holds the value of the "employee_user_id" field.
	EmployeeUserID int64 `json:"employee_user_id,omitempty"`
	// ProfileVersion holds the value of the "profile_version" field.
	ProfileVersion string `json:"profile_version,omitempty"`
	// SignalSource holds the value of the "signal_source" field.
	SignalSource string `json:"signal_source,omitempty"`
	// SignalStatus holds the value of the "signal_status" field.
	SignalStatus worksession.SignalStatus `json:"signal_status,omitempty"`
	// SessionKeyHmac holds the value of the "session_key_hmac" field.
	SessionKeyHmac *[]byte `json:"session_key_hmac,omitempty"`
	// HmacKeyVersion holds the value of the "hmac_key_version" field.
	HmacKeyVersion *string `json:"hmac_key_version,omitempty"`
	// Reliability holds the value of the "reliability" field.
	Reliability worksession.Reliability `json:"reliability,omitempty"`
	// RoutingMode holds the value of the "routing_mode" field.
	RoutingMode worksession.RoutingMode `json:"routing_mode,omitempty"`
	// ConfigVersion holds the value of the "config_version" field.
	ConfigVersion int64 `json:"config_version,omitempty"`
	// AnalysisEligible holds the value of the "analysis_eligible" field.
	AnalysisEligible bool `json:"analysis_eligible,omitempty"`
	// QuotaGraceEligible holds the value of the "quota_grace_eligible" field.
	QuotaGraceEligible bool `json:"quota_grace_eligible,omitempty"`
	// Status holds the value of the "status" field.
	Status worksession.Status `json:"status,omitempty"`
	// SelectedLogicalModel holds the value of the "selected_logical_model" field.
	SelectedLogicalModel *string `json:"selected_logical_model,omitempty"`
	// SelectedTier holds the value of the "selected_tier" field.
	SelectedTier *worksession.SelectedTier `json:"selected_tier,omitempty"`
	// SelectedComplexity holds the value of the "selected_complexity" field.
	SelectedComplexity *worksession.SelectedComplexity `json:"selected_complexity,omitempty"`
	// RequiredCapabilities holds the value of the "required_capabilities" field.
	RequiredCapabilities []string `json:"required_capabilities,omitempty"`
	// RoutingVersion holds the value of the "routing_version" field.
	RoutingVersion int64 `json:"routing_version,omitempty"`
	// FirstGatewayRequestID holds the value of the "first_gateway_request_id" field.
	FirstGatewayRequestID uuid.UUID `json:"first_gateway_request_id,omitempty"`
	// LastGatewayRequestID holds the value of the "last_gateway_request_id" field.
	LastGatewayRequestID uuid.UUID `json:"last_gateway_request_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// LastActivityAt holds the value of the "last_activity_at" field.
	LastActivityAt time.Time `json:"last_activity_at,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case worksession.FieldSessionKeyHmac, worksession.FieldRequiredCapabilities:
			values[i] = new([]byte)
		case worksession.FieldAnalysisEligible, worksession.FieldQuotaGraceEligible:
			values[i] = new(sql.NullBool)
		case worksession.FieldEmployeeUserID, worksession.FieldConfigVersion, worksession.FieldRoutingVersion:
			values[i] = new(sql.NullInt64)
		case worksession.FieldTenantID, worksession.FieldProfileVersion, worksession.FieldSignalSource, worksession.FieldSignalStatus, worksession.FieldHmacKeyVersion, worksession.FieldReliability, worksession.FieldRoutingMode, worksession.FieldStatus, worksession.FieldSelectedLogicalModel, worksession.FieldSelectedTier, worksession.FieldSelectedComplexity:
			values[i] = new(sql.NullString)
		case worksession.FieldCreatedAt, worksession.FieldLastActivityAt:
			values[i] = new(sql.NullTime)
		case worksession.FieldID, worksession.FieldFirstGatewayRequestID, worksession.FieldLastGatewayRequestID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkSession fields.
func (_m *WorkSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case worksession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case worksession.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case worksession.FieldEmployeeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field employee_user_id", values[i])
			} else if value.Valid {
				_m.EmployeeUserID = value.Int64
			}
		case worksession.FieldProfileVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_version", values[i])
			} else if value.Valid {
				_m.ProfileVersion = value.String
			}
		case worksession.FieldSignalSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signal_source", values[i])
			} else if value.Valid {
				_m.SignalSource = value.String
			}
		case worksession.FieldSignalStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signal_status", values[i])
			} else if value.Valid {
				_m.SignalStatus = worksession.SignalStatus(value.String)
			}
		case worksession.FieldSessionKeyHmac:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field session_key_hmac", values[i])
			} else if value != nil {
				_m.SessionKeyHmac = value
			}
		case worksession.FieldHmacKeyVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hmac_key_version", values[i])
			} else if value.Valid {
				_m.HmacKeyVersion = new(string)
				*_m.HmacKeyVersion = value.String
			}
		case worksession.FieldReliability:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reliability", values[i])
			} else if value.Valid {
				_m.Reliability = worksession.Reliability(value.String)
			}
		case worksession.FieldRoutingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field routing_mode", values[i])
			} else if value.Valid {
				_m.RoutingMode = worksession.RoutingMode(value.String)
			}
		case worksession.FieldConfigVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field config_version", values[i])
			} else if value.Valid {
				_m.ConfigVersion = value.Int64
			}
		case worksession.FieldAnalysisEligible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field analysis_eligible", values[i])
			} else if value.Valid {
				_m.AnalysisEligible = value.Bool
			}
		case worksession.FieldQuotaGraceEligible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field quota_grace_eligible", values[i])
			} else if value.Valid {
				_m.QuotaGraceEligible = value.Bool
			}
		case worksession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = worksession.Status(value.String)
			}
		case worksession.FieldSelectedLogicalModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field selected_logical_model", values[i])
			} else if value.Valid {
				_m.SelectedLogicalModel = new(string)
				*_m.SelectedLogicalModel = value.String
			}
		case worksession.FieldSelectedTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field selected_tier", values[i])
			} else if value.Valid {
				_m.SelectedTier = new(worksession.SelectedTier)
				*_m.SelectedTier = worksession.SelectedTier(value.String)
			}
		case worksession.FieldSelectedComplexity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field selected_complexity", values[i])
			} else if value.Valid {
				_m.SelectedComplexity = new(worksession.SelectedComplexity)
				*_m.SelectedComplexity = worksession.SelectedComplexity(value.String)
			}
		case worksession.FieldRequiredCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field required_capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequiredCapabilities); err != nil {
					return fmt.Errorf("unmarshal field required_capabilities: %w", err)
				}
			}
		case worksession.FieldRoutingVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field routing_version", values[i])
			} else if value.Valid {
				_m.RoutingVersion = value.Int64
			}
		case worksession.FieldFirstGatewayRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field first_gateway_request_id", values[i])
			} else if value != nil {
				_m.FirstGatewayRequestID = *value
			}
		case worksession.FieldLastGatewayRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field last_gateway_request_id", values[i])
			} else if value != nil {
				_m.LastGatewayRequestID = *value
			}
		case worksession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case worksession.FieldLastActivityAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_activity_at", values[i])
			} else if value.Valid {
				_m.LastActivityAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkSession.
// This includes values selected through modifiers, order, etc.
func (_m *WorkSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WorkSession.
// Note that you need to call WorkSession.Unwrap() before calling this method if this WorkSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkSession) Update() *WorkSessionUpdateOne {
	return NewWorkSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkSession) Unwrap() *WorkSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkSession) String() string {
	var builder strings.Builder
	builder.WriteString("WorkSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("employee_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmployeeUserID))
	builder.WriteString(", ")
	builder.WriteString("profile_version=")
	builder.WriteString(_m.ProfileVersion)
	builder.WriteString(", ")
	builder.WriteString("signal_source=")
	builder.WriteString(_m.SignalSource)
	builder.WriteString(", ")
	builder.WriteString("signal_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.SignalStatus))
	builder.WriteString(", ")
	if v := _m.SessionKeyHmac; v != nil {
		builder.WriteString("session_key_hmac=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.HmacKeyVersion; v != nil {
		builder.WriteString("hmac_key_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("reliability=")
	builder.WriteString(fmt.Sprintf("%v", _m.Reliability))
	builder.WriteString(", ")
	builder.WriteString("routing_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoutingMode))
	builder.WriteString(", ")
	builder.WriteString("config_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigVersion))
	builder.WriteString(", ")
	builder.WriteString("analysis_eligible=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnalysisEligible))
	builder.WriteString(", ")
	builder.WriteString("quota_grace_eligible=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaGraceEligible))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.SelectedLogicalModel; v != nil {
		builder.WriteString("selected_logical_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SelectedTier; v != nil {
		builder.WriteString("selected_tier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SelectedComplexity; v != nil {
		builder.WriteString("selected_complexity=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("required_capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiredCapabilities))
	builder.WriteString(", ")
	builder.WriteString("routing_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoutingVersion))
	builder.WriteString(", ")
	builder.WriteString("first_gateway_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FirstGatewayRequestID))
	builder.WriteString(", ")
	builder.WriteString("last_gateway_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastGatewayRequestID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_activity_at=")
	builder.WriteString(_m.LastActivityAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WorkSessions is a parsable slice of WorkSession.
type WorkSessions []*WorkSession
