// Code generated by ent, DO NOT EDIT.

package worksession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldTenantID, v))
}

// EmployeeUserID applies equality check predicate on the "employee_user_id" field. It's identical to EmployeeUserIDEQ.
func EmployeeUserID(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldEmployeeUserID, v))
}

// ProfileVersion applies equality check predicate on the "profile_version" field. It's identical to ProfileVersionEQ.
func ProfileVersion(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldProfileVersion, v))
}

// SignalSource applies equality check predicate on the "signal_source" field. It's identical to SignalSourceEQ.
func SignalSource(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSignalSource, v))
}

// SessionKeyHmac applies equality check predicate on the "session_key_hmac" field. It's identical to SessionKeyHmacEQ.
func SessionKeyHmac(v []byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSessionKeyHmac, v))
}

// HmacKeyVersion applies equality check predicate on the "hmac_key_version" field. It's identical to HmacKeyVersionEQ.
func HmacKeyVersion(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldHmacKeyVersion, v))
}

// ConfigVersion applies equality check predicate on the "config_version" field. It's identical to ConfigVersionEQ.
func ConfigVersion(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldConfigVersion, v))
}

// AnalysisEligible applies equality check predicate on the "analysis_eligible" field. It's identical to AnalysisEligibleEQ.
func AnalysisEligible(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldAnalysisEligible, v))
}

// QuotaGraceEligible applies equality check predicate on the "quota_grace_eligible" field. It's identical to QuotaGraceEligibleEQ.
func QuotaGraceEligible(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldQuotaGraceEligible, v))
}

// SelectedLogicalModel applies equality check predicate on the "selected_logical_model" field. It's identical to SelectedLogicalModelEQ.
func SelectedLogicalModel(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSelectedLogicalModel, v))
}

// RoutingVersion applies equality check predicate on the "routing_version" field. It's identical to RoutingVersionEQ.
func RoutingVersion(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldRoutingVersion, v))
}

// FirstGatewayRequestID applies equality check predicate on the "first_gateway_request_id" field. It's identical to FirstGatewayRequestIDEQ.
func FirstGatewayRequestID(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldFirstGatewayRequestID, v))
}

// LastGatewayRequestID applies equality check predicate on the "last_gateway_request_id" field. It's identical to LastGatewayRequestIDEQ.
func LastGatewayRequestID(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldLastGatewayRequestID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldCreatedAt, v))
}

// LastActivityAt applies equality check predicate on the "last_activity_at" field. It's identical to LastActivityAtEQ.
func LastActivityAt(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldLastActivityAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContainsFold(FieldTenantID, v))
}

// EmployeeUserIDEQ applies the EQ predicate on the "employee_user_id" field.
func EmployeeUserIDEQ(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldEmployeeUserID, v))
}

// EmployeeUserIDNEQ applies the NEQ predicate on the "employee_user_id" field.
func EmployeeUserIDNEQ(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldEmployeeUserID, v))
}

// EmployeeUserIDIn applies the In predicate on the "employee_user_id" field.
func EmployeeUserIDIn(vs ...int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldEmployeeUserID, vs...))
}

// EmployeeUserIDNotIn applies the NotIn predicate on the "employee_user_id" field.
func EmployeeUserIDNotIn(vs ...int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldEmployeeUserID, vs...))
}

// EmployeeUserIDGT applies the GT predicate on the "employee_user_id" field.
func EmployeeUserIDGT(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldEmployeeUserID, v))
}

// EmployeeUserIDGTE applies the GTE predicate on the "employee_user_id" field.
func EmployeeUserIDGTE(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldEmployeeUserID, v))
}

// EmployeeUserIDLT applies the LT predicate on the "employee_user_id" field.
func EmployeeUserIDLT(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldEmployeeUserID, v))
}

// EmployeeUserIDLTE applies the LTE predicate on the "employee_user_id" field.
func EmployeeUserIDLTE(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldEmployeeUserID, v))
}

// ProfileVersionEQ applies the EQ predicate on the "profile_version" field.
func ProfileVersionEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldProfileVersion, v))
}

// ProfileVersionNEQ applies the NEQ predicate on the "profile_version" field.
func ProfileVersionNEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldProfileVersion, v))
}

// ProfileVersionIn applies the In predicate on the "profile_version" field.
func ProfileVersionIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldProfileVersion, vs...))
}

// ProfileVersionNotIn applies the NotIn predicate on the "profile_version" field.
func ProfileVersionNotIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldProfileVersion, vs...))
}

// ProfileVersionGT applies the GT predicate on the "profile_version" field.
func ProfileVersionGT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldProfileVersion, v))
}

// ProfileVersionGTE applies the GTE predicate on the "profile_version" field.
func ProfileVersionGTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldProfileVersion, v))
}

// ProfileVersionLT applies the LT predicate on the "profile_version" field.
func ProfileVersionLT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldProfileVersion, v))
}

// ProfileVersionLTE applies the LTE predicate on the "profile_version" field.
func ProfileVersionLTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldProfileVersion, v))
}

// ProfileVersionContains applies the Contains predicate on the "profile_version" field.
func ProfileVersionContains(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContains(FieldProfileVersion, v))
}

// ProfileVersionHasPrefix applies the HasPrefix predicate on the "profile_version" field.
func ProfileVersionHasPrefix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasPrefix(FieldProfileVersion, v))
}

// ProfileVersionHasSuffix applies the HasSuffix predicate on the "profile_version" field.
func ProfileVersionHasSuffix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasSuffix(FieldProfileVersion, v))
}

// ProfileVersionEqualFold applies the EqualFold predicate on the "profile_version" field.
func ProfileVersionEqualFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEqualFold(FieldProfileVersion, v))
}

// ProfileVersionContainsFold applies the ContainsFold predicate on the "profile_version" field.
func ProfileVersionContainsFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContainsFold(FieldProfileVersion, v))
}

// SignalSourceEQ applies the EQ predicate on the "signal_source" field.
func SignalSourceEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSignalSource, v))
}

// SignalSourceNEQ applies the NEQ predicate on the "signal_source" field.
func SignalSourceNEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldSignalSource, v))
}

// SignalSourceIn applies the In predicate on the "signal_source" field.
func SignalSourceIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldSignalSource, vs...))
}

// SignalSourceNotIn applies the NotIn predicate on the "signal_source" field.
func SignalSourceNotIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldSignalSource, vs...))
}

// SignalSourceGT applies the GT predicate on the "signal_source" field.
func SignalSourceGT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldSignalSource, v))
}

// SignalSourceGTE applies the GTE predicate on the "signal_source" field.
func SignalSourceGTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldSignalSource, v))
}

// SignalSourceLT applies the LT predicate on the "signal_source" field.
func SignalSourceLT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldSignalSource, v))
}

// SignalSourceLTE applies the LTE predicate on the "signal_source" field.
func SignalSourceLTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldSignalSource, v))
}

// SignalSourceContains applies the Contains predicate on the "signal_source" field.
func SignalSourceContains(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContains(FieldSignalSource, v))
}

// SignalSourceHasPrefix applies the HasPrefix predicate on the "signal_source" field.
func SignalSourceHasPrefix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasPrefix(FieldSignalSource, v))
}

// SignalSourceHasSuffix applies the HasSuffix predicate on the "signal_source" field.
func SignalSourceHasSuffix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasSuffix(FieldSignalSource, v))
}

// SignalSourceEqualFold applies the EqualFold predicate on the "signal_source" field.
func SignalSourceEqualFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEqualFold(FieldSignalSource, v))
}

// SignalSourceContainsFold applies the ContainsFold predicate on the "signal_source" field.
func SignalSourceContainsFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContainsFold(FieldSignalSource, v))
}

// SignalStatusEQ applies the EQ predicate on the "signal_status" field.
func SignalStatusEQ(v SignalStatus) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSignalStatus, v))
}

// SignalStatusNEQ applies the NEQ predicate on the "signal_status" field.
func SignalStatusNEQ(v SignalStatus) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldSignalStatus, v))
}

// SignalStatusIn applies the In predicate on the "signal_status" field.
func SignalStatusIn(vs ...SignalStatus) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldSignalStatus, vs...))
}

// SignalStatusNotIn applies the NotIn predicate on the "signal_status" field.
func SignalStatusNotIn(vs ...SignalStatus) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldSignalStatus, vs...))
}

// SessionKeyHmacEQ applies the EQ predicate on the "session_key_hmac" field.
func SessionKeyHmacEQ(v []byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSessionKeyHmac, v))
}

// SessionKeyHmacNEQ applies the NEQ predicate on the "session_key_hmac" field.
func SessionKeyHmacNEQ(v []byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldSessionKeyHmac, v))
}

// SessionKeyHmacIn applies the In predicate on the "session_key_hmac" field.
func SessionKeyHmacIn(vs ...[]byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldSessionKeyHmac, vs...))
}

// SessionKeyHmacNotIn applies the NotIn predicate on the "session_key_hmac" field.
func SessionKeyHmacNotIn(vs ...[]byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldSessionKeyHmac, vs...))
}

// SessionKeyHmacGT applies the GT predicate on the "session_key_hmac" field.
func SessionKeyHmacGT(v []byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldSessionKeyHmac, v))
}

// SessionKeyHmacGTE applies the GTE predicate on the "session_key_hmac" field.
func SessionKeyHmacGTE(v []byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldSessionKeyHmac, v))
}

// SessionKeyHmacLT applies the LT predicate on the "session_key_hmac" field.
func SessionKeyHmacLT(v []byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldSessionKeyHmac, v))
}

// SessionKeyHmacLTE applies the LTE predicate on the "session_key_hmac" field.
func SessionKeyHmacLTE(v []byte) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldSessionKeyHmac, v))
}

// SessionKeyHmacIsNil applies the IsNil predicate on the "session_key_hmac" field.
func SessionKeyHmacIsNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIsNull(FieldSessionKeyHmac))
}

// SessionKeyHmacNotNil applies the NotNil predicate on the "session_key_hmac" field.
func SessionKeyHmacNotNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotNull(FieldSessionKeyHmac))
}

// HmacKeyVersionEQ applies the EQ predicate on the "hmac_key_version" field.
func HmacKeyVersionEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldHmacKeyVersion, v))
}

// HmacKeyVersionNEQ applies the NEQ predicate on the "hmac_key_version" field.
func HmacKeyVersionNEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldHmacKeyVersion, v))
}

// HmacKeyVersionIn applies the In predicate on the "hmac_key_version" field.
func HmacKeyVersionIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldHmacKeyVersion, vs...))
}

// HmacKeyVersionNotIn applies the NotIn predicate on the "hmac_key_version" field.
func HmacKeyVersionNotIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldHmacKeyVersion, vs...))
}

// HmacKeyVersionGT applies the GT predicate on the "hmac_key_version" field.
func HmacKeyVersionGT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldHmacKeyVersion, v))
}

// HmacKeyVersionGTE applies the GTE predicate on the "hmac_key_version" field.
func HmacKeyVersionGTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldHmacKeyVersion, v))
}

// HmacKeyVersionLT applies the LT predicate on the "hmac_key_version" field.
func HmacKeyVersionLT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldHmacKeyVersion, v))
}

// HmacKeyVersionLTE applies the LTE predicate on the "hmac_key_version" field.
func HmacKeyVersionLTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldHmacKeyVersion, v))
}

// HmacKeyVersionContains applies the Contains predicate on the "hmac_key_version" field.
func HmacKeyVersionContains(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContains(FieldHmacKeyVersion, v))
}

// HmacKeyVersionHasPrefix applies the HasPrefix predicate on the "hmac_key_version" field.
func HmacKeyVersionHasPrefix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasPrefix(FieldHmacKeyVersion, v))
}

// HmacKeyVersionHasSuffix applies the HasSuffix predicate on the "hmac_key_version" field.
func HmacKeyVersionHasSuffix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasSuffix(FieldHmacKeyVersion, v))
}

// HmacKeyVersionIsNil applies the IsNil predicate on the "hmac_key_version" field.
func HmacKeyVersionIsNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIsNull(FieldHmacKeyVersion))
}

// HmacKeyVersionNotNil applies the NotNil predicate on the "hmac_key_version" field.
func HmacKeyVersionNotNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotNull(FieldHmacKeyVersion))
}

// HmacKeyVersionEqualFold applies the EqualFold predicate on the "hmac_key_version" field.
func HmacKeyVersionEqualFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEqualFold(FieldHmacKeyVersion, v))
}

// HmacKeyVersionContainsFold applies the ContainsFold predicate on the "hmac_key_version" field.
func HmacKeyVersionContainsFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContainsFold(FieldHmacKeyVersion, v))
}

// ReliabilityEQ applies the EQ predicate on the "reliability" field.
func ReliabilityEQ(v Reliability) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldReliability, v))
}

// ReliabilityNEQ applies the NEQ predicate on the "reliability" field.
func ReliabilityNEQ(v Reliability) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldReliability, v))
}

// ReliabilityIn applies the In predicate on the "reliability" field.
func ReliabilityIn(vs ...Reliability) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldReliability, vs...))
}

// ReliabilityNotIn applies the NotIn predicate on the "reliability" field.
func ReliabilityNotIn(vs ...Reliability) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldReliability, vs...))
}

// RoutingModeEQ applies the EQ predicate on the "routing_mode" field.
func RoutingModeEQ(v RoutingMode) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldRoutingMode, v))
}

// RoutingModeNEQ applies the NEQ predicate on the "routing_mode" field.
func RoutingModeNEQ(v RoutingMode) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldRoutingMode, v))
}

// RoutingModeIn applies the In predicate on the "routing_mode" field.
func RoutingModeIn(vs ...RoutingMode) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldRoutingMode, vs...))
}

// RoutingModeNotIn applies the NotIn predicate on the "routing_mode" field.
func RoutingModeNotIn(vs ...RoutingMode) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldRoutingMode, vs...))
}

// ConfigVersionEQ applies the EQ predicate on the "config_version" field.
func ConfigVersionEQ(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldConfigVersion, v))
}

// ConfigVersionNEQ applies the NEQ predicate on the "config_version" field.
func ConfigVersionNEQ(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldConfigVersion, v))
}

// ConfigVersionIn applies the In predicate on the "config_version" field.
func ConfigVersionIn(vs ...int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldConfigVersion, vs...))
}

// ConfigVersionNotIn applies the NotIn predicate on the "config_version" field.
func ConfigVersionNotIn(vs ...int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldConfigVersion, vs...))
}

// ConfigVersionGT applies the GT predicate on the "config_version" field.
func ConfigVersionGT(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldConfigVersion, v))
}

// ConfigVersionGTE applies the GTE predicate on the "config_version" field.
func ConfigVersionGTE(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldConfigVersion, v))
}

// ConfigVersionLT applies the LT predicate on the "config_version" field.
func ConfigVersionLT(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldConfigVersion, v))
}

// ConfigVersionLTE applies the LTE predicate on the "config_version" field.
func ConfigVersionLTE(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldConfigVersion, v))
}

// AnalysisEligibleEQ applies the EQ predicate on the "analysis_eligible" field.
func AnalysisEligibleEQ(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldAnalysisEligible, v))
}

// AnalysisEligibleNEQ applies the NEQ predicate on the "analysis_eligible" field.
func AnalysisEligibleNEQ(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldAnalysisEligible, v))
}

// QuotaGraceEligibleEQ applies the EQ predicate on the "quota_grace_eligible" field.
func QuotaGraceEligibleEQ(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldQuotaGraceEligible, v))
}

// QuotaGraceEligibleNEQ applies the NEQ predicate on the "quota_grace_eligible" field.
func QuotaGraceEligibleNEQ(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldQuotaGraceEligible, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldStatus, vs...))
}

// SelectedLogicalModelEQ applies the EQ predicate on the "selected_logical_model" field.
func SelectedLogicalModelEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelNEQ applies the NEQ predicate on the "selected_logical_model" field.
func SelectedLogicalModelNEQ(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelIn applies the In predicate on the "selected_logical_model" field.
func SelectedLogicalModelIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldSelectedLogicalModel, vs...))
}

// SelectedLogicalModelNotIn applies the NotIn predicate on the "selected_logical_model" field.
func SelectedLogicalModelNotIn(vs ...string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldSelectedLogicalModel, vs...))
}

// SelectedLogicalModelGT applies the GT predicate on the "selected_logical_model" field.
func SelectedLogicalModelGT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelGTE applies the GTE predicate on the "selected_logical_model" field.
func SelectedLogicalModelGTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelLT applies the LT predicate on the "selected_logical_model" field.
func SelectedLogicalModelLT(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelLTE applies the LTE predicate on the "selected_logical_model" field.
func SelectedLogicalModelLTE(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelContains applies the Contains predicate on the "selected_logical_model" field.
func SelectedLogicalModelContains(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContains(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelHasPrefix applies the HasPrefix predicate on the "selected_logical_model" field.
func SelectedLogicalModelHasPrefix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasPrefix(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelHasSuffix applies the HasSuffix predicate on the "selected_logical_model" field.
func SelectedLogicalModelHasSuffix(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldHasSuffix(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelIsNil applies the IsNil predicate on the "selected_logical_model" field.
func SelectedLogicalModelIsNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIsNull(FieldSelectedLogicalModel))
}

// SelectedLogicalModelNotNil applies the NotNil predicate on the "selected_logical_model" field.
func SelectedLogicalModelNotNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotNull(FieldSelectedLogicalModel))
}

// SelectedLogicalModelEqualFold applies the EqualFold predicate on the "selected_logical_model" field.
func SelectedLogicalModelEqualFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEqualFold(FieldSelectedLogicalModel, v))
}

// SelectedLogicalModelContainsFold applies the ContainsFold predicate on the "selected_logical_model" field.
func SelectedLogicalModelContainsFold(v string) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldContainsFold(FieldSelectedLogicalModel, v))
}

// SelectedTierEQ applies the EQ predicate on the "selected_tier" field.
func SelectedTierEQ(v SelectedTier) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSelectedTier, v))
}

// SelectedTierNEQ applies the NEQ predicate on the "selected_tier" field.
func SelectedTierNEQ(v SelectedTier) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldSelectedTier, v))
}

// SelectedTierIn applies the In predicate on the "selected_tier" field.
func SelectedTierIn(vs ...SelectedTier) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldSelectedTier, vs...))
}

// SelectedTierNotIn applies the NotIn predicate on the "selected_tier" field.
func SelectedTierNotIn(vs ...SelectedTier) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldSelectedTier, vs...))
}

// SelectedTierIsNil applies the IsNil predicate on the "selected_tier" field.
func SelectedTierIsNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIsNull(FieldSelectedTier))
}

// SelectedTierNotNil applies the NotNil predicate on the "selected_tier" field.
func SelectedTierNotNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotNull(FieldSelectedTier))
}

// SelectedComplexityEQ applies the EQ predicate on the "selected_complexity" field.
func SelectedComplexityEQ(v SelectedComplexity) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldSelectedComplexity, v))
}

// SelectedComplexityNEQ applies the NEQ predicate on the "selected_complexity" field.
func SelectedComplexityNEQ(v SelectedComplexity) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldSelectedComplexity, v))
}

// SelectedComplexityIn applies the In predicate on the "selected_complexity" field.
func SelectedComplexityIn(vs ...SelectedComplexity) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldSelectedComplexity, vs...))
}

// SelectedComplexityNotIn applies the NotIn predicate on the "selected_complexity" field.
func SelectedComplexityNotIn(vs ...SelectedComplexity) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldSelectedComplexity, vs...))
}

// SelectedComplexityIsNil applies the IsNil predicate on the "selected_complexity" field.
func SelectedComplexityIsNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIsNull(FieldSelectedComplexity))
}

// SelectedComplexityNotNil applies the NotNil predicate on the "selected_complexity" field.
func SelectedComplexityNotNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotNull(FieldSelectedComplexity))
}

// RoutingVersionEQ applies the EQ predicate on the "routing_version" field.
func RoutingVersionEQ(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldRoutingVersion, v))
}

// RoutingVersionNEQ applies the NEQ predicate on the "routing_version" field.
func RoutingVersionNEQ(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldRoutingVersion, v))
}

// RoutingVersionIn applies the In predicate on the "routing_version" field.
func RoutingVersionIn(vs ...int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldRoutingVersion, vs...))
}

// RoutingVersionNotIn applies the NotIn predicate on the "routing_version" field.
func RoutingVersionNotIn(vs ...int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldRoutingVersion, vs...))
}

// RoutingVersionGT applies the GT predicate on the "routing_version" field.
func RoutingVersionGT(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldRoutingVersion, v))
}

// RoutingVersionGTE applies the GTE predicate on the "routing_version" field.
func RoutingVersionGTE(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldRoutingVersion, v))
}

// RoutingVersionLT applies the LT predicate on the "routing_version" field.
func RoutingVersionLT(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldRoutingVersion, v))
}

// RoutingVersionLTE applies the LTE predicate on the "routing_version" field.
func RoutingVersionLTE(v int64) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldRoutingVersion, v))
}

// FirstGatewayRequestIDEQ applies the EQ predicate on the "first_gateway_request_id" field.
func FirstGatewayRequestIDEQ(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldFirstGatewayRequestID, v))
}

// FirstGatewayRequestIDNEQ applies the NEQ predicate on the "first_gateway_request_id" field.
func FirstGatewayRequestIDNEQ(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldFirstGatewayRequestID, v))
}

// FirstGatewayRequestIDIn applies the In predicate on the "first_gateway_request_id" field.
func FirstGatewayRequestIDIn(vs ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldFirstGatewayRequestID, vs...))
}

// FirstGatewayRequestIDNotIn applies the NotIn predicate on the "first_gateway_request_id" field.
func FirstGatewayRequestIDNotIn(vs ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldFirstGatewayRequestID, vs...))
}

// FirstGatewayRequestIDGT applies the GT predicate on the "first_gateway_request_id" field.
func FirstGatewayRequestIDGT(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldFirstGatewayRequestID, v))
}

// FirstGatewayRequestIDGTE applies the GTE predicate on the "first_gateway_request_id" field.
func FirstGatewayRequestIDGTE(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldFirstGatewayRequestID, v))
}

// FirstGatewayRequestIDLT applies the LT predicate on the "first_gateway_request_id" field.
func FirstGatewayRequestIDLT(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldFirstGatewayRequestID, v))
}

// FirstGatewayRequestIDLTE applies the LTE predicate on the "first_gateway_request_id" field.
func FirstGatewayRequestIDLTE(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldFirstGatewayRequestID, v))
}

// LastGatewayRequestIDEQ applies the EQ predicate on the "last_gateway_request_id" field.
func LastGatewayRequestIDEQ(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldLastGatewayRequestID, v))
}

// LastGatewayRequestIDNEQ applies the NEQ predicate on the "last_gateway_request_id" field.
func LastGatewayRequestIDNEQ(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldLastGatewayRequestID, v))
}

// LastGatewayRequestIDIn applies the In predicate on the "last_gateway_request_id" field.
func LastGatewayRequestIDIn(vs ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldLastGatewayRequestID, vs...))
}

// LastGatewayRequestIDNotIn applies the NotIn predicate on the "last_gateway_request_id" field.
func LastGatewayRequestIDNotIn(vs ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldLastGatewayRequestID, vs...))
}

// LastGatewayRequestIDGT applies the GT predicate on the "last_gateway_request_id" field.
func LastGatewayRequestIDGT(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldLastGatewayRequestID, v))
}

// LastGatewayRequestIDGTE applies the GTE predicate on the "last_gateway_request_id" field.
func LastGatewayRequestIDGTE(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldLastGatewayRequestID, v))
}

// LastGatewayRequestIDLT applies the LT predicate on the "last_gateway_request_id" field.
func LastGatewayRequestIDLT(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldLastGatewayRequestID, v))
}

// LastGatewayRequestIDLTE applies the LTE predicate on the "last_gateway_request_id" field.
func LastGatewayRequestIDLTE(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldLastGatewayRequestID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldCreatedAt, v))
}

// LastActivityAtEQ applies the EQ predicate on the "last_activity_at" field.
func LastActivityAtEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldLastActivityAt, v))
}

// LastActivityAtNEQ applies the NEQ predicate on the "last_activity_at" field.
func LastActivityAtNEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldLastActivityAt, v))
}

// LastActivityAtIn applies the In predicate on the "last_activity_at" field.
func LastActivityAtIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldLastActivityAt, vs...))
}

// LastActivityAtNotIn applies the NotIn predicate on the "last_activity_at" field.
func LastActivityAtNotIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldLastActivityAt, vs...))
}

// LastActivityAtGT applies the GT predicate on the "last_activity_at" field.
func LastActivityAtGT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldLastActivityAt, v))
}

// LastActivityAtGTE applies the GTE predicate on the "last_activity_at" field.
func LastActivityAtGTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldLastActivityAt, v))
}

// LastActivityAtLT applies the LT predicate on the "last_activity_at" field.
func LastActivityAtLT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldLastActivityAt, v))
}

// LastActivityAtLTE applies the LTE predicate on the "last_activity_at" field.
func LastActivityAtLTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldLastActivityAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkSession) predicate.WorkSession {
	return predicate.WorkSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkSession) predicate.WorkSession {
	return predicate.WorkSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkSession) predicate.WorkSession {
	return predicate.WorkSession(sql.NotPredicates(p))
}
