// Code generated by ent, DO NOT EDIT.

package worksession

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the worksession type in the database.
	Label = "work_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldEmployeeUserID holds the string denoting the employee_user_id field in the database.
	FieldEmployeeUserID = "employee_user_id"
	// FieldProfileVersion holds the string denoting the profile_version field in the database.
	FieldProfileVersion = "profile_version"
	// FieldSignalSource holds the string denoting the signal_source field in the database.
	FieldSignalSource = "signal_source"
	// FieldSignalStatus holds the string denoting the signal_status field in the database.
	FieldSignalStatus = "signal_status"
	// FieldSessionKeyHmac holds the string denoting the session_key_hmac field in the database.
	FieldSessionKeyHmac = "session_key_hmac"
	// FieldHmacKeyVersion holds the string denoting the hmac_key_version field in the database.
	FieldHmacKeyVersion = "hmac_key_version"
	// FieldReliability holds the string denoting the reliability field in the database.
	FieldReliability = "reliability"
	// FieldRoutingMode holds the string denoting the routing_mode field in the database.
	FieldRoutingMode = "routing_mode"
	// FieldConfigVersion holds the string denoting the config_version field in the database.
	FieldConfigVersion = "config_version"
	// FieldAnalysisEligible holds the string denoting the analysis_eligible field in the database.
	FieldAnalysisEligible = "analysis_eligible"
	// FieldQuotaGraceEligible holds the string denoting the quota_grace_eligible field in the database.
	FieldQuotaGraceEligible = "quota_grace_eligible"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSelectedLogicalModel holds the string denoting the selected_logical_model field in the database.
	FieldSelectedLogicalModel = "selected_logical_model"
	// FieldSelectedTier holds the string denoting the selected_tier field in the database.
	FieldSelectedTier = "selected_tier"
	// FieldSelectedComplexity holds the string denoting the selected_complexity field in the database.
	FieldSelectedComplexity = "selected_complexity"
	// FieldRequiredCapabilities holds the string denoting the required_capabilities field in the database.
	FieldRequiredCapabilities = "required_capabilities"
	// FieldRoutingVersion holds the string denoting the routing_version field in the database.
	FieldRoutingVersion = "routing_version"
	// FieldFirstGatewayRequestID holds the string denoting the first_gateway_request_id field in the database.
	FieldFirstGatewayRequestID = "first_gateway_request_id"
	// FieldLastGatewayRequestID holds the string denoting the last_gateway_request_id field in the database.
	FieldLastGatewayRequestID = "last_gateway_request_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldLastActivityAt holds the string denoting the last_activity_at field in the database.
	FieldLastActivityAt = "last_activity_at"
	// Table holds the table name of the worksession in the database.
	Table = "work_sessions"
)

// Columns holds all SQL columns for worksession fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldEmployeeUserID,
	FieldProfileVersion,
	FieldSignalSource,
	FieldSignalStatus,
	FieldSessionKeyHmac,
	FieldHmacKeyVersion,
	FieldReliability,
	FieldRoutingMode,
	FieldConfigVersion,
	FieldAnalysisEligible,
	FieldQuotaGraceEligible,
	FieldStatus,
	FieldSelectedLogicalModel,
	FieldSelectedTier,
	FieldSelectedComplexity,
	FieldRequiredCapabilities,
	FieldRoutingVersion,
	FieldFirstGatewayRequestID,
	FieldLastGatewayRequestID,
	FieldCreatedAt,
	FieldLastActivityAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// ProfileVersionValidator is a validator for the "profile_version" field. It is called by the builders before save.
	ProfileVersionValidator func(string) error
	// SignalSourceValidator is a validator for the "signal_source" field. It is called by the builders before save.
	SignalSourceValidator func(string) error
	// HmacKeyVersionValidator is a validator for the "hmac_key_version" field. It is called by the builders before save.
	HmacKeyVersionValidator func(string) error
	// DefaultAnalysisEligible holds the default value on creation for the "analysis_eligible" field.
	DefaultAnalysisEligible bool
	// DefaultQuotaGraceEligible holds the default value on creation for the "quota_grace_eligible" field.
	DefaultQuotaGraceEligible bool
	// SelectedLogicalModelValidator is a validator for the "selected_logical_model" field. It is called by the builders before save.
	SelectedLogicalModelValidator func(string) error
	// DefaultRequiredCapabilities holds the default value on creation for the "required_capabilities" field.
	DefaultRequiredCapabilities []string
	// DefaultRoutingVersion holds the default value on creation for the "routing_version" field.
	DefaultRoutingVersion int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultLastActivityAt holds the default value on creation for the "last_activity_at" field.
	DefaultLastActivityAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// SignalStatus defines the type for the "signal_status" enum field.
type SignalStatus string

// SignalStatus values.
const (
	SignalStatusVerified  SignalStatus = "verified"
	SignalStatusMissing   SignalStatus = "missing"
	SignalStatusMalformed SignalStatus = "malformed"
)

func (ss SignalStatus) String() string {
	return string(ss)
}

// SignalStatusValidator is a validator for the "signal_status" field enum values. It is called by the builders before save.
func SignalStatusValidator(ss SignalStatus) error {
	switch ss {
	case SignalStatusVerified, SignalStatusMissing, SignalStatusMalformed:
		return nil
	default:
		return fmt.Errorf("worksession: invalid enum value for signal_status field: %q", ss)
	}
}

// Reliability defines the type for the "reliability" enum field.
type Reliability string

// Reliability values.
const (
	ReliabilityReliable   Reliability = "reliable"
	ReliabilityUnreliable Reliability = "unreliable"
)

func (r Reliability) String() string {
	return string(r)
}

// ReliabilityValidator is a validator for the "reliability" field enum values. It is called by the builders before save.
func ReliabilityValidator(r Reliability) error {
	switch r {
	case ReliabilityReliable, ReliabilityUnreliable:
		return nil
	default:
		return fmt.Errorf("worksession: invalid enum value for reliability field: %q", r)
	}
}

// RoutingMode defines the type for the "routing_mode" enum field.
type RoutingMode string

// RoutingMode values.
const (
	RoutingModeExplicit RoutingMode = "explicit"
	RoutingModeAuto     RoutingMode = "auto"
)

func (rm RoutingMode) String() string {
	return string(rm)
}

// RoutingModeValidator is a validator for the "routing_mode" field enum values. It is called by the builders before save.
func RoutingModeValidator(rm RoutingMode) error {
	switch rm {
	case RoutingModeExplicit, RoutingModeAuto:
		return nil
	default:
		return fmt.Errorf("worksession: invalid enum value for routing_mode field: %q", rm)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusActive        Status = "active"
	StatusRequestScoped Status = "request_scoped"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusRequestScoped:
		return nil
	default:
		return fmt.Errorf("worksession: invalid enum value for status field: %q", s)
	}
}

// SelectedTier defines the type for the "selected_tier" enum field.
type SelectedTier string

// SelectedTier values.
const (
	SelectedTierEconomy  SelectedTier = "economy"
	SelectedTierGeneral  SelectedTier = "general"
	SelectedTierAdvanced SelectedTier = "advanced"
)

func (st SelectedTier) String() string {
	return string(st)
}

// SelectedTierValidator is a validator for the "selected_tier" field enum values. It is called by the builders before save.
func SelectedTierValidator(st SelectedTier) error {
	switch st {
	case SelectedTierEconomy, SelectedTierGeneral, SelectedTierAdvanced:
		return nil
	default:
		return fmt.Errorf("worksession: invalid enum value for selected_tier field: %q", st)
	}
}

// SelectedComplexity defines the type for the "selected_complexity" enum field.
type SelectedComplexity string

// SelectedComplexity values.
const (
	SelectedComplexitySimple  SelectedComplexity = "simple"
	SelectedComplexityGeneral SelectedComplexity = "general"
	SelectedComplexityComplex SelectedComplexity = "complex"
)

func (sc SelectedComplexity) String() string {
	return string(sc)
}

// SelectedComplexityValidator is a validator for the "selected_complexity" field enum values. It is called by the builders before save.
func SelectedComplexityValidator(sc SelectedComplexity) error {
	switch sc {
	case SelectedComplexitySimple, SelectedComplexityGeneral, SelectedComplexityComplex:
		return nil
	default:
		return fmt.Errorf("worksession: invalid enum value for selected_complexity field: %q", sc)
	}
}

// OrderOption defines the ordering options for the WorkSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByEmployeeUserID orders the results by the employee_user_id field.
func ByEmployeeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmployeeUserID, opts...).ToFunc()
}

// ByProfileVersion orders the results by the profile_version field.
func ByProfileVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileVersion, opts...).ToFunc()
}

// BySignalSource orders the results by the signal_source field.
func BySignalSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignalSource, opts...).ToFunc()
}

// BySignalStatus orders the results by the signal_status field.
func BySignalStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignalStatus, opts...).ToFunc()
}

// ByHmacKeyVersion orders the results by the hmac_key_version field.
func ByHmacKeyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHmacKeyVersion, opts...).ToFunc()
}

// ByReliability orders the results by the reliability field.
func ByReliability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReliability, opts...).ToFunc()
}

// ByRoutingMode orders the results by the routing_mode field.
func ByRoutingMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoutingMode, opts...).ToFunc()
}

// ByConfigVersion orders the results by the config_version field.
func ByConfigVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigVersion, opts...).ToFunc()
}

// ByAnalysisEligible orders the results by the analysis_eligible field.
func ByAnalysisEligible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalysisEligible, opts...).ToFunc()
}

// ByQuotaGraceEligible orders the results by the quota_grace_eligible field.
func ByQuotaGraceEligible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaGraceEligible, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySelectedLogicalModel orders the results by the selected_logical_model field.
func BySelectedLogicalModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelectedLogicalModel, opts...).ToFunc()
}

// BySelectedTier orders the results by the selected_tier field.
func BySelectedTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelectedTier, opts...).ToFunc()
}

// BySelectedComplexity orders the results by the selected_complexity field.
func BySelectedComplexity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelectedComplexity, opts...).ToFunc()
}

// ByRoutingVersion orders the results by the routing_version field.
func ByRoutingVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoutingVersion, opts...).ToFunc()
}

// ByFirstGatewayRequestID orders the results by the first_gateway_request_id field.
func ByFirstGatewayRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstGatewayRequestID, opts...).ToFunc()
}

// ByLastGatewayRequestID orders the results by the last_gateway_request_id field.
func ByLastGatewayRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastGatewayRequestID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByLastActivityAt orders the results by the last_activity_at field.
func ByLastActivityAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActivityAt, opts...).ToFunc()
}
